#!/usr/bin/env bash
set -e

echo "Running cargo fmt..."
staged=$(git diff --cached --name-only)
nix develop --command bash -c 'cargo fmt --all'
if [ -n "$staged" ]; then
  echo "$staged" | xargs git add
fi

echo "Running cargo clippy..."
nix develop --command bash -c 'cargo clippy --all-targets --all-features -- -D warnings'

echo "Pre-commit checks passed!"
