//! Minimal 2D geometry primitives used by the fence arrangement builder.
//!
//! Coordinates are `f64`. This is a deliberate, documented choice (see
//! `Point` docs below) rather than an oversight: exact/symbolic coordinates
//! would require a different robustness strategy throughout, not just a
//! generic parameter here.

/// A point in the plane.
///
/// Coordinates are `f64`. A configuration in this problem is described by
/// closed-form constants (unit lengths, regular-polygon vertices involving
/// `sin`/`cos`/`cot`), so exact rational or even algebraic-number
/// coordinates would not eliminate the need for tolerance-based comparison
/// downstream — `sin(pi/9)` is irrational and any exact representation
/// still has to be compared to other irrational quantities with some
/// notion of "close enough". We therefore standardize on `f64` plus an
/// explicit, tunable [`crate::Tolerance`] used consistently by every
/// geometric predicate (length check, incidence check, vertex merge,
/// crossing detection). A future symbolic backend (e.g. exact arithmetic
/// over the field generated by the constructible points of a
/// configuration) is possible but would need its own intersection and
/// face-tracing logic, not a drop-in swap of the coordinate type — so we
/// do not pre-emptively generify `Point` over a numeric trait.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

impl Point {
    pub fn new(x: f64, y: f64) -> Self {
        Point { x, y }
    }

    pub fn scale(self, s: f64) -> Point {
        Point::new(self.x * s, self.y * s)
    }

    pub fn dot(self, other: Point) -> f64 {
        self.x * other.x + self.y * other.y
    }

    /// 2D "cross product": the z-component of the 3D cross product of the
    /// two vectors extended into the plane z=0.
    pub fn cross(self, other: Point) -> f64 {
        self.x * other.y - self.y * other.x
    }

    pub fn norm(self) -> f64 {
        self.dot(self).sqrt()
    }

    pub fn dist(self, other: Point) -> f64 {
        (self - other).norm()
    }
}

impl std::ops::Sub for Point {
    type Output = Point;
    fn sub(self, other: Point) -> Point {
        Point::new(self.x - other.x, self.y - other.y)
    }
}

impl std::ops::Add for Point {
    type Output = Point;
    fn add(self, other: Point) -> Point {
        Point::new(self.x + other.x, self.y + other.y)
    }
}

/// A straight segment between two points.
#[derive(Debug, Clone, Copy)]
pub struct Segment {
    pub a: Point,
    pub b: Point,
}

impl Segment {
    pub fn new(a: Point, b: Point) -> Self {
        Segment { a, b }
    }

    pub fn length(&self) -> f64 {
        self.a.dist(self.b)
    }

    pub fn direction(&self) -> Point {
        self.b - self.a
    }

    /// Point at parameter `t` along the segment (`t=0` is `a`, `t=1` is `b`).
    pub fn at(&self, t: f64) -> Point {
        self.a + self.direction().scale(t)
    }

    /// The parameter `t` of `p`'s projection onto the (infinite) line
    /// through this segment, and the perpendicular distance from `p` to
    /// that line. Returns `None` if the segment is degenerate (zero
    /// length).
    fn project(&self, p: Point) -> Option<(f64, f64)> {
        let d = self.direction();
        let len2 = d.dot(d);
        if len2 < 1e-30 {
            return None;
        }
        let t = (p - self.a).dot(d) / len2;
        let closest = self.a + d.scale(t);
        let dist = p.dist(closest);
        Some((t, dist))
    }

    /// Does `p` lie on this segment (including its endpoints), within
    /// `tol` of perpendicular distance from the segment, allowing the
    /// parameter to overshoot the `[0,1]` range by up to `param_slack`
    /// (as a fraction of the segment's own length)?
    pub fn contains_point(&self, p: Point, tol: f64) -> bool {
        match self.project(p) {
            Some((t, dist)) => {
                let len = self.length();
                let param_slack = if len > 1e-30 { tol / len } else { 0.0 };
                dist <= tol && t >= -param_slack && t <= 1.0 + param_slack
            }
            None => self.a.dist(p) <= tol,
        }
    }

    /// Parameter `t` (unclamped) of `p`'s projection onto this segment's
    /// line, used only for ordering cut points along a segment once they
    /// are already known to lie on it.
    pub fn param_of(&self, p: Point) -> f64 {
        self.project(p).map(|(t, _)| t).unwrap_or(0.0)
    }

    /// Intersection of the two *infinite lines* through `self` and
    /// `other`, restricted to parameters within `[-slack, 1+slack]` on
    /// both segments (`slack` given as a parameter-space tolerance).
    /// Returns `None` for parallel/near-parallel lines (including the
    /// colinear-overlap case) — colinear overlapping fences are not
    /// supported by this arrangement builder; see module docs.
    pub fn intersect(&self, other: &Segment, slack: f64) -> Option<Point> {
        let d1 = self.direction();
        let d2 = other.direction();
        let denom = d1.cross(d2);
        // Threshold chosen relative to the (near-unit) segment lengths
        // used throughout this problem; not a general-purpose robust
        // predicate.
        if denom.abs() < 1e-12 {
            return None;
        }
        let diff = other.a - self.a;
        let t = diff.cross(d2) / denom;
        let u = diff.cross(d1) / denom;
        if t >= -slack && t <= 1.0 + slack && u >= -slack && u <= 1.0 + slack {
            Some(self.at(t.clamp(0.0, 1.0)))
        } else {
            None
        }
    }
}
