/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Polynomial.Taylor
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.RingTheory.Nilpotent.Basic
import Langlands.NakayamaMonogenic

/-!
# A primitive element theorem for nilpotent extensions of a field extension

`NakayamaMonogenic.lean` reduces tower monogenicity (`𝒪_L = 𝒪_K[a]`) to a residue-level question:
do the powers of `a := β + c • π` span `𝒪_N ⧸ 𝔪_K 𝒪_N` over `κ_K`? That residue algebra is *not* a
field — it is a non-reduced Artinian local `κ_K`-algebra (`κ_M[T] ⧸ (T ^ e)` classically), so
`Mathlib.FieldTheory.PrimitiveElement` does not apply. This file proves the generation fact that
does apply, in a form that does not presuppose the polynomial-quotient presentation.

## Main results

* `LocalField.adjoin_add_nilpotent_eq_top` : let `k ⊆ κ` be fields, `A` a commutative `κ`-algebra
  (compatibly a `k`-algebra), `π : A` with `π ^ e = 0`, and suppose `A = κ + π A` (every element of
  `A` is a `κ`-scalar plus a multiple of `π`). If `β` generates `κ` over `k` and `minpoly k β` is
  separable, then `β + π` generates `A` as a `k`-algebra.
* `LocalField.exists_adjoin_add_nilpotent_eq_top` : the same with `β` produced by the primitive
  element theorem, for `κ / k` finite separable.

## The argument

This is the classical proof, and it is *not* a re-run of the field-theoretic primitive element
theorem — separability enters through a Hensel/Newton-flavoured step rather than through counting
embeddings. Write `g := minpoly k β` and `a := β + π`, and set `t := g(a) ∈ k[a]`.

Taylor-expanding `g` at `β` gives `t = g(β) + g'(β) π + π ^ 2 (⋯) = π · w` with
`w ≡ g'(β) mod π`. Separability of `g` gives `g'(β) ≠ 0`, so `w` is a unit plus a nilpotent, hence a
unit. Therefore `t` and `π` generate the *same* ideal, and `t` lies in the subalgebra `k[a]`.

Now `A = k[a] + π A`: any `c : κ` is `p(β)` for some `p ∈ k[X]` (as `β` generates `κ`), and
`p(a) - p(β)` is divisible by `a - β = π`, so `c ∈ k[a] + π A`; combined with the hypothesis
`A = κ + π A` this gives `A = k[a] + π A = k[a] + t A`. Substituting that identity into itself `e`
times gives `A = k[a] + t ^ e A`, and `t ^ e = π ^ e w ^ e = 0`, so `A = k[a]`.

The single element `a = β + π` therefore does double duty — it generates the residue field extension
*and* the nilpotent direction — exactly as the tower argument needs, with no separate scalar `c`
required (`c = 1` works). What makes it work is that `g(a)`, the obstruction to `a` already being a
lift of `β`, is itself a generator of the nilpotent ideal precisely when `g` is separable.

## Relation to the tower

To apply this to `A := 𝒪_N ⧸ 𝔪_K 𝒪_N` one still needs, for the two-step tower `K ⊆ M ⊆ N` of
`UnramifiedExtension.lean` / `TotallyRamifiedEisenstein.lean`:

* the `κ_M`-algebra structure on `A` — i.e. that `𝔪_M` maps into `𝔪_K 𝒪_N`, which is the
  unramifiedness of `M / K` (`𝔪_K 𝒪_M = 𝔪_M`) pushed up to `𝒪_N`;
* `π ^ e = 0` in `A`, i.e. `π ^ e ∈ 𝔪_K 𝒪_N`;
* `A = κ_M + π A`, i.e. `𝒪_N = 𝒪_M + 𝔪_N` (equality of residue fields of `M` and `N`).

None of those three is proved in this repo yet; see `ROADMAP.md`'s twenty-sixth pass entry. This
file deliberately states the algebra in a presentation-free form so that discharging them does *not*
require first constructing the ring isomorphism `𝒪_N ⧸ 𝔪_K 𝒪_N ≅ κ_M[T] ⧸ (T ^ e)` that
`NakayamaMonogenic.lean`'s "what remains" item (1) called for.
-/

namespace LocalField

open Polynomial

variable {k κ A : Type*} [Field k] [Field κ] [CommRing A]
  [Algebra k κ] [Algebra κ A] [Algebra k A] [IsScalarTower k κ A]

section

variable (k κ A)

/-- Evaluating a `k`-polynomial at an element of `A` coming from `κ` factors through `κ`. -/
private theorem aeval_algebraMap_eq (β : κ) (p : k[X]) :
    aeval (algebraMap κ A β) p = algebraMap κ A (aeval β p) := by
  simpa using Polynomial.aeval_algHom_apply (IsScalarTower.toAlgHom k κ A) β p

end

private theorem aeval_eq_eval_map (p : k[X]) (x : A) :
    aeval x p = (p.map (algebraMap k A)).eval x := by
  rw [eval_map, aeval_def]

/-- **The Newton/Hensel step.** If `minpoly k β` is separable and `π` is nilpotent, then
`(minpoly k β)` evaluated at `β + π` equals `π` times a *unit*. Consequently `g (β + π)`, which
visibly lies in the `k`-subalgebra generated by `β + π`, generates the same ideal as `π`. -/
theorem exists_isUnit_aeval_minpoly_eq {β : κ} (hsep : (minpoly k β).Separable) {π : A}
    (hnil : IsNilpotent π) :
    ∃ w : A, IsUnit w ∧ aeval (algebraMap κ A β + π) (minpoly k β) = π * w := by
  classical
  set r : A := algebraMap κ A β with hr
  set G : A[X] := (minpoly k β).map (algebraMap k A) with hG
  set q : A[X] := taylor r G with hq
  -- the constant term of the Taylor expansion is `g (β) = 0`
  have hq0 : q.coeff 0 = 0 := by
    rw [hq, taylor_coeff_zero, hG, ← aeval_eq_eval_map, hr, aeval_algebraMap_eq k κ A,
      minpoly.aeval, map_zero]
  -- the linear term is `g' (β)`, a unit by separability
  have hq1 : IsUnit (q.coeff 1) := by
    have hd : G.derivative = (derivative (minpoly k β)).map (algebraMap k A) :=
      derivative_map _ _
    have : q.coeff 1 = algebraMap κ A (aeval β (derivative (minpoly k β))) := by
      rw [hq, taylor_coeff_one, hd, ← aeval_eq_eval_map, hr, aeval_algebraMap_eq k κ A]
    rw [this]
    exact (isUnit_iff_ne_zero.mpr
      (hsep.aeval_derivative_ne_zero (minpoly.aeval k β))).map (algebraMap κ A)
  refine ⟨q.divX.eval π, ?_, ?_⟩
  · -- `q.divX.eval π ≡ q.coeff 1` modulo the nilpotent `π`
    obtain ⟨z, hz⟩ : π ∣ q.divX.eval π - q.divX.eval 0 := by
      simpa using sub_dvd_eval_sub π 0 q.divX
    have h0 : q.divX.eval 0 = q.coeff 1 := by
      rw [← coeff_zero_eq_eval_zero, coeff_divX]
    have : q.divX.eval π = q.coeff 1 + π * z := by
      rw [← h0]; linear_combination hz
    rw [this]
    exact IsNilpotent.isUnit_add_left_of_commute
      ((Commute.all π z).isNilpotent_mul_right hnil) hq1 (Commute.all _ _)
  · -- `g (β + π) = q (π) = π * q.divX (π)`, using `q.coeff 0 = 0`
    have hqe : q.eval π = aeval (r + π) (minpoly k β) := by
      rw [hq, taylor_eval, aeval_eq_eval_map, ← hG, add_comm]
    have := congrArg (Polynomial.eval π) (X_mul_divX_add q)
    simp only [eval_add, eval_mul, eval_X, eval_C, hq0, add_zero] at this
    rw [← hqe, ← this]

/-- **Primitive element for a nilpotent extension of a field extension.**
`k ⊆ κ` fields, `A` a `κ`-algebra (compatibly a `k`-algebra), `π : A` nilpotent with `π ^ e = 0`,
and `A = κ + π A`. If `β` generates `κ` over `k` with `minpoly k β` separable, then `β + π`
generates `A` as a `k`-algebra.

This is the Artinian analogue of `Field.exists_primitive_element` needed by the tower-monogenicity
argument; the field-theoretic version does not apply because `A` is non-reduced. -/
theorem adjoin_add_nilpotent_eq_top {β : κ} (hgen : Algebra.adjoin k ({β} : Set κ) = ⊤)
    (hsep : (minpoly k β).Separable) {π : A} {e : ℕ} (hnil : π ^ e = 0)
    (hsurj : ∀ x : A, ∃ (c : κ) (y : A), x = algebraMap κ A c + π * y) :
    Algebra.adjoin k ({algebraMap κ A β + π} : Set A) = ⊤ := by
  classical
  set a : A := algebraMap κ A β + π with ha
  set R : Subalgebra k A := Algebra.adjoin k ({a} : Set A) with hR
  obtain ⟨w, hwu, hwt⟩ := exists_isUnit_aeval_minpoly_eq hsep (π := π) ⟨e, hnil⟩
  set t : A := aeval a (minpoly k β) with ht
  have htR : t ∈ R := by rw [ht, hR]; exact Polynomial.aeval_mem_adjoin_singleton _ _
  -- `π ∈ t A`, since `t = π * w` with `w` a unit
  obtain ⟨v, hv⟩ : ∃ v : A, π = t * v := ⟨↑hwu.unit⁻¹, by rw [hwt]; simp [mul_assoc]⟩
  -- Step 1 : `A = R + t A`.
  have step : ∀ x : A, ∃ ρ ∈ R, ∃ y : A, x = ρ + t * y := by
    intro x
    obtain ⟨c, y, hxy⟩ := hsurj x
    -- write `c = p (β)` and compare `p (a)` with `p (β)`
    have hc : c ∈ Algebra.adjoin k ({β} : Set κ) := hgen ▸ Algebra.mem_top
    rw [Algebra.adjoin_singleton_eq_range_aeval] at hc
    obtain ⟨p, hp⟩ := hc
    have hp' : aeval β p = c := hp
    obtain ⟨z, hz⟩ : π ∣ aeval a p - aeval (algebraMap κ A β) p := by
      have := sub_dvd_eval_sub a (algebraMap κ A β) (p.map (algebraMap k A))
      rw [← aeval_eq_eval_map, ← aeval_eq_eval_map] at this
      simpa [ha] using this
    have hcA : algebraMap κ A c = aeval a p - π * z := by
      rw [← hp', ← aeval_algebraMap_eq k κ A]
      linear_combination -hz
    refine ⟨aeval a p, Polynomial.aeval_mem_adjoin_singleton _ _, v * (y - z), ?_⟩
    rw [hxy, hcA, hv]; ring
  -- Step 2 : iterate, `A = R + t ^ n A` for every `n`.
  have iter : ∀ (n : ℕ) (x : A), ∃ ρ ∈ R, ∃ y : A, x = ρ + t ^ n * y := by
    intro n
    induction n with
    | zero => intro x; exact ⟨0, zero_mem _, x, by simp⟩
    | succ n ih =>
      intro x
      obtain ⟨ρ, hρ, y, hy⟩ := ih x
      obtain ⟨ρ', hρ', y', hy'⟩ := step y
      exact ⟨ρ + t ^ n * ρ', add_mem hρ (mul_mem (pow_mem htR n) hρ'), y', by
        rw [hy, hy']; ring⟩
  -- Step 3 : at `n = e` the tail vanishes, since `t ^ e = π ^ e * w ^ e = 0`.
  have hte : t ^ e = 0 := by rw [hwt, mul_pow, hnil, zero_mul]
  refine top_unique fun x _ => ?_
  obtain ⟨ρ, hρ, y, hy⟩ := iter e x
  rw [hy, hte, zero_mul, add_zero]
  exact hρ

/-- Existence form: for `κ / k` finite separable and `A` as above, *some* element generates `A` as a
`k`-algebra. The generator is `β + π` for `β` any primitive element of `κ / k` — no auxiliary scalar
on `π` is needed. -/
theorem exists_adjoin_add_nilpotent_eq_top [Algebra.IsSeparable k κ] [FiniteDimensional k κ]
    {π : A} {e : ℕ} (hnil : π ^ e = 0)
    (hsurj : ∀ x : A, ∃ (c : κ) (y : A), x = algebraMap κ A c + π * y) :
    ∃ a : A, Algebra.adjoin k ({a} : Set A) = ⊤ := by
  obtain ⟨β, hβ⟩ := Field.exists_primitive_element k κ
  refine ⟨algebraMap κ A β + π, adjoin_add_nilpotent_eq_top ?_ ?_ hnil hsurj⟩
  · have : (IntermediateField.adjoin k ({β} : Set κ)).toSubalgebra = (⊤ : Subalgebra k κ) := by
      rw [hβ]; rfl
    rw [← this, IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsIntegral.isIntegral β).isAlgebraic]
  · exact Algebra.IsSeparable.isSeparable k β

section Composite

open IsLocalRing

/-- **The composite monogenicity criterion**, combining this file's Artinian primitive element
theorem with `LocalField.adjoin_eq_top_of_adjoin_quotient_eq_top`.

Let `R` be local, `S` a finite `R`-algebra, and write `A := S ⧸ 𝔪_R S` for the residue algebra.
Suppose `A` contains a field `κ`, finite and separable over the residue field `R ⧸ 𝔪_R`, and an
element `π` with `π ^ e = 0` such that `A = κ + π A`. Then `S` is monogenic over `R`.

For the local-field tower `K ⊆ M ⊆ N` this is exactly the shape needed, with `κ := κ_M`, `π` the
image of a uniformizer of `N`, and `e` the ramification index — and, crucially, *without* having to
first exhibit `A` as `κ_M[T] ⧸ (T ^ e)`. -/
theorem exists_adjoin_eq_top_of_residue_nilpotent {R S : Type*} [CommRing R] [IsLocalRing R]
    [CommRing S] [Algebra R S] [Module.Finite R S]
    {κ : Type*} [Field κ] [Algebra (R ⧸ maximalIdeal R) κ]
    [Algebra κ (S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R))]
    [IsScalarTower (R ⧸ maximalIdeal R) κ (S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R))]
    [Algebra.IsSeparable (R ⧸ maximalIdeal R) κ] [Module.Finite (R ⧸ maximalIdeal R) κ]
    {π : S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R)} {e : ℕ} (hnil : π ^ e = 0)
    (hsurj : ∀ x : S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R),
      ∃ (c : κ) (y : S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R)),
        x = algebraMap κ _ c + π * y) :
    ∃ β : S, Algebra.adjoin R ({β} : Set S) = ⊤ := by
  letI : Field (R ⧸ maximalIdeal R) := Ideal.Quotient.field _
  obtain ⟨a, ha⟩ :=
    exists_adjoin_add_nilpotent_eq_top (k := R ⧸ maximalIdeal R) (κ := κ) hnil hsurj
  obtain ⟨β, rfl⟩ := Ideal.Quotient.mk_surjective a
  exact ⟨β, adjoin_eq_top_of_adjoin_quotient_eq_top β ha⟩

end Composite

end LocalField
