import Langlands.CyclicSubgroups
import Mathlib.FieldTheory.Galois.Basic

/-!
# Unique subfield of each degree dividing the degree, for a cyclic Galois extension

The field-theoretic translation of `IsCyclic.existsUnique_subgroup_card_eq`
(`Langlands.CyclicSubgroups`) through the (finite) Galois correspondence
(`IsGalois.intermediateFieldEquivSubgroup`): if `E/F` is a finite Galois extension with cyclic
Galois group, then for every divisor `e` of `[E:F]` there is a *unique* intermediate field of
degree `e` over `F`. This is the field-theoretic content behind the classical fact that the
subfields of `GF(q^n)` are exactly `GF(q^d)` for `d ∣ n` (Lidl & Niederreiter, *Finite Fields*,
Theorem 2.6): `GF(q^n)/GF(q)` is Galois with cyclic Galois group (generated by Frobenius) of order
`n`, so this theorem, specialized to `F := GF(q)`, `E := GF(q^n)`, gives existence and uniqueness of
the degree-`d` subfield for every `d ∣ n`. (`d ∣ n ↔ GF(q^d) ⊆ GF(q^n)`, i.e. the "subfield lattice
matches divisibility" half of Theorem 2.6, follows for free: both sides are the unique subfield of
their respective degrees, and `IsGalois.intermediateFieldEquivSubgroup` being an *order* iso, not
just a bijection, would let this file's uniqueness result be upgraded to the order-embedding
statement -- not done here since it isn't needed for `Langlands.WeilGroup`.)

Not found in Mathlib by a Loogle search of `IntermediateField`/`GaloisField`/`Subfield` combinations
(no subfield-of-a-fixed-field-by-degree classification, only the abstract "`GaloisField p n` is
non-canonically unique up to isomorphism" statement in `Mathlib.FieldTheory.Finite.GaloisField`).

## Main result

* `IsGalois.existsUnique_intermediateField_finrank_eq` : for `E/F` finite Galois with
  `IsCyclic Gal(E/F)`, and `e ∣ Module.finrank F E`, there is a unique `M : IntermediateField F E`
  with `Module.finrank F M = e`.
* `IntermediateField.finrank_comap_val_of_le` : general field theory, no Galois needed --
  restricting an intermediate field `M ≤ E'` to the smaller ambient field `E'` (via
  `IntermediateField.comap E'.val`, i.e. pulling `M` back along the tautological inclusion
  `E' →ₐ[F] E`) preserves its degree over `F`. This is the tool needed to compare two intermediate
  fields of a *fixed* finite Galois extension of `E` (rather than of `E` itself) using
  `existsUnique_intermediateField_finrank_eq`, e.g. to compare degree-`e` subfields `M₁ M₂ ≤ E` that
  are not assumed finite/Galois over `F` themselves by relating them to their sup `M₁ ⊔ M₂`
  (finite/Galois whenever `M₁`, `M₂` are). An exhaustive Loogle search initially missed this (only
  `IntermediateField.extendScalars`, which rebases the *bottom* of a tower, turned up under
  "restrict"-flavoured queries); it is assembled from `IntermediateField.comap`,
  `IntermediateField.map_comap_eq_self`, and `IntermediateField.equivMap`, all already in Mathlib.

## Proof idea

Transport `IsCyclic.existsUnique_subgroup_card_eq` along the Galois correspondence: a subgroup `H`
of order `d := n / e` (where `n := [E:F]`) corresponds to the intermediate field `fixedField H`,
whose fixing subgroup is `H` again (`IntermediateField.fixingSubgroup_fixedField`, valid for *any*
subgroup of a finite Galois group, not just closed ones as in the infinite-degree case), which has
`Nat.card H = d` elements (by construction) and hence `Module.finrank (fixedField H) E = d` (by
`IsGalois.card_fixingSubgroup_eq_finrank`), hence -- by the tower law `Module.finrank_mul_finrank`
and `n = e * d` -- `Module.finrank F (fixedField H) = e`. Uniqueness is the same computation read
backwards, ending in `IsGalois.fixedField_eq_iff_fixingSubgroup_eq` to convert the subgroup-level
uniqueness (`IsCyclic.existsUnique_subgroup_card_eq`'s `∃!`) into field-level uniqueness.
-/

@[expose] public section

/-- **Restricting an intermediate field to a smaller ambient intermediate field preserves its
degree.** Given `M ≤ E'` (both `IntermediateField F E`), `IntermediateField.comap E'.val M` is `M`
viewed as an intermediate field of `E'` instead of `E`; its `F`-degree agrees with that of `M`
since it is `F`-algebra isomorphic to `M` (`IntermediateField.equivMap`, using
`IntermediateField.map_comap_eq_self` to identify `(comap E'.val M).map E'.val` with `M` again). -/
theorem IntermediateField.finrank_comap_val_of_le {F E : Type*} [Field F] [Field E] [Algebra F E]
    {E' M : IntermediateField F E} (h : M ≤ E') :
    Module.finrank F (IntermediateField.comap E'.val M) = Module.finrank F M := by
  have hM : M ≤ E'.val.fieldRange := by rw [IntermediateField.fieldRange_val]; exact h
  have hmap : IntermediateField.map E'.val (IntermediateField.comap E'.val M) = M :=
    IntermediateField.map_comap_eq_self hM
  have hequiv := (IntermediateField.comap E'.val M).equivMap E'.val
  rw [hmap] at hequiv
  exact LinearEquiv.finrank_eq hequiv.toLinearEquiv

namespace IsGalois

variable {F E : Type*} [Field F] [Field E] [Algebra F E] [FiniteDimensional F E] [IsGalois F E]

/-- **Unique subfield of each degree dividing `[E:F]`**, for `E/F` finite Galois with cyclic Galois
group: for every `e ∣ Module.finrank F E`, there is a unique intermediate field `M` with
`Module.finrank F M = e`. -/
theorem existsUnique_intermediateField_finrank_eq [IsCyclic Gal(E/F)] {e : ℕ}
    (he : e ∣ Module.finrank F E) :
    ∃! M : IntermediateField F E, Module.finrank F M = e := by
  set n := Module.finrank F E with hn
  have hn0 : n ≠ 0 := Module.finrank_pos.ne'
  have he0 : e ≠ 0 := by
    rintro rfl
    exact hn0 (Nat.zero_dvd.mp he)
  have he_pos : 0 < e := Nat.pos_of_ne_zero he0
  have hnd : e * (n / e) = n := Nat.mul_div_cancel' he
  have hd : n / e ∣ n := Nat.div_dvd_of_dvd he
  have hcardG : Nat.card Gal(E/F) = n := IsGalois.card_aut_eq_finrank F E
  have hdG : n / e ∣ Nat.card Gal(E/F) := hcardG ▸ hd
  -- `IsCyclic.existsUnique_subgroup_card_eq` needs `[CommGroup Gal(E/F)]`, derived here from
  -- `IsCyclic.commGroup`; passing the ambient `[IsCyclic Gal(E/F)]` hypothesis explicitly via
  -- `‹_›` (rather than introducing a competing `CommGroup`-derived `Group` instance with `haveI`
  -- and letting instance search rediscover `IsCyclic`/`Finite` against it) avoids a diamond
  -- between the ambient `Group Gal(E/F)` instance and `IsCyclic.commGroup.toGroup` that otherwise
  -- makes plain instance search fail to find the (defeq, but not instance-search-defeq) ambient
  -- `[IsCyclic Gal(E/F)]` hypothesis.
  obtain ⟨H, hHcard, hHuniq⟩ :=
    @IsCyclic.existsUnique_subgroup_card_eq Gal(E/F) IsCyclic.commGroup ‹IsCyclic Gal(E/F)›
      inferInstance (n / e) hdG
  have hde_pos : 0 < n / e := by
    rcases Nat.eq_zero_or_pos (n / e) with h0 | hpos
    · rw [h0, mul_zero] at hnd; exact absurd hnd.symm hn0
    · exact hpos
  refine ⟨IntermediateField.fixedField H, ?_, fun M' hM' => ?_⟩
  · have hfix : (IntermediateField.fixedField H).fixingSubgroup = H :=
      IntermediateField.fixingSubgroup_fixedField H
    have hcardM : Module.finrank (IntermediateField.fixedField H) E = n / e := by
      have h := IsGalois.card_fixingSubgroup_eq_finrank (IntermediateField.fixedField H)
      rw [hfix, hHcard] at h
      exact h.symm
    have htower : Module.finrank F (IntermediateField.fixedField H) * (n / e) = n := by
      have h := Module.finrank_mul_finrank F (IntermediateField.fixedField H) E
      rwa [hcardM] at h
    have heq : Module.finrank F (IntermediateField.fixedField H) * (n / e) = e * (n / e) := by
      rw [htower, hnd]
    exact Nat.eq_of_mul_eq_mul_right hde_pos heq
  · have hcardM' : Module.finrank M' E = n / e := by
      have htower' := Module.finrank_mul_finrank F M' E
      rw [hM'] at htower'
      exact Nat.eq_of_mul_eq_mul_left he_pos (htower'.trans hnd.symm)
    have hHM' : Nat.card M'.fixingSubgroup = n / e := by
      rw [IsGalois.card_fixingSubgroup_eq_finrank M', hcardM']
    have hEq : M'.fixingSubgroup = H := hHuniq M'.fixingSubgroup hHM'
    exact (IsGalois.fixedField_eq_iff_fixingSubgroup_eq.mpr hEq).symm

end IsGalois
