import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.Coset.Card

/-!
# Subgroups of a finite cyclic group

For a finite cyclic group `G` and every divisor `d` of `Nat.card G` there is a unique subgroup of
`G` of order `d`, namely the kernel of the `d`-th power endomorphism `powMonoidHom d`. This is the
classical classification of the subgroup lattice of a finite cyclic group.

Mathlib's `IsCyclic.card_powMonoidHom_ker` and `IsCyclic.card_powMonoidHom_range`
(`Mathlib.GroupTheory.SpecificGroups.Cyclic`) compute the cardinalities of the kernel and range of
the `d`-th power map; this file packages them into the existence and uniqueness statement.

## Main results

* `IsCyclic.subgroup_eq_powMonoidHom_ker_of_card_eq` : a subgroup of order `d` is the kernel of
  `powMonoidHom d`.
* `IsCyclic.existsUnique_subgroup_card_eq` : for `d ∣ Nat.card G` there is a unique subgroup of
  order `d`.
* `mulEquivOfGenerators` : two groups equipped with a distinguished generator and of equal
  `Nat.card` are isomorphic by an isomorphism matching the generators.
* `zpowers_quotientGroupMk'_eq_top_of_zpowers_eq_top` : the image of a generator generates the
  quotient by a normal subgroup.

## Implementation notes

Cardinalities are handled throughout with `Nat.card`, so no `Fintype` instance is ever introduced;
`Fintype.ofFinite`-derived instances are not defeq-canonical, and mixing independently derived
copies for the same type makes `isDefEq`/`whnf` diverge.

Every occurrence of `powMonoidHom d` carries an explicit `(α := G)`. Leaving `α` to unification at
some occurrences (via `.ker`/`Nat.card`) but not others sends elaboration of the combining
`refine`/`exact` calls down a deferred-metavariable path whose cost grows with each heartbeat
increase rather than converging.

## References

* Dummit and Foote, *Abstract Algebra*, Theorem 14.19.
* Lidl and Niederreiter, *Finite Fields*, Theorem 2.6, for the subfield-lattice special case.
-/

@[expose] public section

namespace IsCyclic

variable {G : Type*} [CommGroup G] [IsCyclic G] [Finite G]

/-- A subgroup `K` of a finite cyclic group `G` with `Nat.card K = d` is the kernel of the `d`-th
power endomorphism. Every element of `K` has order dividing `d` by Lagrange's theorem inside `K`
(`Subgroup.orderOf_dvd_natCard`), so `K ≤ (powMonoidHom d).ker`, and the kernel again has
cardinality `d` since `d ∣ Nat.card G`, forcing equality. -/
theorem subgroup_eq_powMonoidHom_ker_of_card_eq (K : Subgroup G) {d : ℕ}
    (hd : d ∣ Nat.card G) (hK : Nat.card K = d) : K = (powMonoidHom d (α := G)).ker := by
  have hle : K ≤ (powMonoidHom d (α := G)).ker := by
    intro x hx
    have horder : orderOf x ∣ d := by
      have h := K.orderOf_dvd_natCard hx
      rwa [hK] at h
    rw [MonoidHom.mem_ker, powMonoidHom_apply]
    exact orderOf_dvd_iff_pow_eq_one.mp horder
  have hcard : Nat.card (powMonoidHom d (α := G)).ker = d := by
    rw [IsCyclic.card_powMonoidHom_ker]
    exact Nat.gcd_eq_right hd
  have hbij : Function.Bijective (Subgroup.inclusion hle) :=
    (Subgroup.inclusion_injective hle).bijective_of_nat_card_le (by rw [hK, hcard])
  refine le_antisymm hle fun x hx => ?_
  obtain ⟨⟨y, hy⟩, hyx⟩ := hbij.2 ⟨x, hx⟩
  have hxy : y = x := by
    have h := congrArg (fun z : (powMonoidHom d (α := G)).ker => (z : G)) hyx
    simpa [Subgroup.coe_inclusion] using h
  rwa [hxy] at hy

/-- **Classification of the subgroups of a finite cyclic group**: for every divisor `d` of
`Nat.card G` there is a unique subgroup `H` of `G` with `Nat.card H = d`, namely the kernel of
`powMonoidHom d`. -/
theorem existsUnique_subgroup_card_eq {d : ℕ} (hd : d ∣ Nat.card G) :
    ∃! H : Subgroup G, Nat.card H = d := by
  have hcard : Nat.card (powMonoidHom d (α := G)).ker = d := by
    rw [IsCyclic.card_powMonoidHom_ker]
    exact Nat.gcd_eq_right hd
  refine ExistsUnique.intro (powMonoidHom d (α := G)).ker hcard fun K hK => ?_
  exact subgroup_eq_powMonoidHom_ker_of_card_eq K hd hK

end IsCyclic

/-- Two groups `G`, `G'` generated by distinguished elements `g`, `g'` and with
`Nat.card G = Nat.card G'` are isomorphic. Both are identified with
`Multiplicative (ZMod (Nat.card G))` via `zmodMulEquivOfGenerator`
(`Mathlib.GroupTheory.SpecificGroups.Cyclic`); the resulting isomorphism sends `g` to `g'`
(`mulEquivOfGenerators_apply_self`). A cyclic group is therefore determined, together with a
choice of generator, by its `Nat.card` alone. -/
noncomputable def mulEquivOfGenerators {G G' : Type*} [Group G] [Group G'] {g : G} {g' : G'}
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) (hg' : ∀ x : G', x ∈ Subgroup.zpowers g')
    (hn : Nat.card G = Nat.card G') : G ≃* G' :=
  (zmodMulEquivOfGenerator hg rfl).symm.trans (zmodMulEquivOfGenerator hg' hn.symm)

/-- `mulEquivOfGenerators` carries the distinguished generator of `G` to that of `G'`. -/
@[simp]
theorem mulEquivOfGenerators_apply_self {G G' : Type*} [Group G] [Group G'] {g : G} {g' : G'}
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) (hg' : ∀ x : G', x ∈ Subgroup.zpowers g')
    (hn : Nat.card G = Nat.card G') : mulEquivOfGenerators hg hg' hn g = g' := by
  simp [mulEquivOfGenerators, zmodMulEquivOfGenerator_symm_apply_generator]

/-- The image of a generator of `G` under the quotient map `G → G ⧸ N` generates `G ⧸ N`; in
particular a quotient of a singly generated group is again singly generated. -/
theorem zpowers_quotientGroupMk'_eq_top_of_zpowers_eq_top {G : Type*} [Group G] {g : G}
    (hg : ∀ x : G, x ∈ Subgroup.zpowers g) (N : Subgroup G) [N.Normal] (y : G ⧸ N) :
    y ∈ Subgroup.zpowers (QuotientGroup.mk' N g) := by
  obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective N y
  obtain ⟨i, hi⟩ := hg x
  exact ⟨i, by rw [← hi, map_zpow]⟩
