/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral
import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Adjoin.PowerBasis
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Monogenicity from a bare Eisenstein minimal polynomial, with no `ValuativeRel`/`NormedField`

`Langlands/TotallyRamifiedEisenstein.lean`'s `LocalField.adjoin_eq_integralClosure_of_isUniformizer`
proves `Algebra.adjoin ↥𝒪[K] {π} = integralClosure ↥𝒪[K] L` for `𝒪[K] := (ValuativeRel.valuation
K).valuationSubring` — but its proof, from the point `minpoly ↥𝒪[K] π` is known Eisenstein onward,
uses no further `spectralNorm`/`ValuativeRel` structure: only that `R := ↥𝒪[K]` is an integrally
closed discrete valuation ring with fraction field `K`, and `π` has Eisenstein minimal polynomial
generating `L / K`. This file extracts exactly that tail of the proof as a standalone theorem
stated for an *arbitrary* such `R`, not tied to any `ValuativeRel`-canonical valuation subring.

This is the tool `ROADMAP.md`'s `§56` ("Gap 2") calls for: applying
`Algebra.discr_mul_isIntegral_mem_adjoin` and
`mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt` directly at a moving base `R`
(e.g. `R := O_{K_1}`) that carries no `ValuativeRel`/`NontriviallyNormedField` structure of its
own, sidestepping the instance diamond `Langlands/TowerBundleResidueField.lean`'s `_of_valuationSubring`
variants hit when reused one level up (see `Langlands/LubinTateTowerStepMonogenic.lean`).

## Main result

* `adjoin_eq_integralClosure_of_isEisensteinAt` : for `R` an integrally closed `IsDiscreteValuationRing`
  domain with fraction field `K`, `L / K` finite separable, `β : L` integral over `R` with
  `minpoly R β` Eisenstein at a uniformizer `ϖ` of `R` and generating `L` over `K`
  (`hgen : (minpoly K β).natDegree = Module.finrank K L`),
  `Algebra.adjoin R ({β} : Set L) = integralClosure R L`.

The proof is verbatim `LocalField.adjoin_eq_integralClosure_of_isUniformizer`'s, with `hEis`/`hβint`
taken as hypotheses instead of derived from a `hram : ‖ϖ‖ = spectralNorm K L π ^ n` total-ramification
condition.
-/

noncomputable section

open Polynomial

/-- **Monogenicity from a bare Eisenstein minimal polynomial.** `R` an integrally closed discrete
valuation ring with fraction field `K`, `L / K` finite separable, `β : L` integral over `R` whose
minimal polynomial over `R` is Eisenstein at (the ideal generated by) a uniformizer `ϖ` of `R`, and
`β` generates `L` over `K` (`hgen`). Then `Algebra.adjoin R {β} = integralClosure R L`: the integral
closure of `R` in `L` is generated as an `R`-algebra by `β`.

No `ValuativeRel`/`NormedField`/`spectralNorm` structure is used or needed — only that `R` is an
integrally closed `IsDiscreteValuationRing` with fraction field `K`. This generalizes
`LocalField.adjoin_eq_integralClosure_of_isUniformizer`
(`Langlands/TotallyRamifiedEisenstein.lean`), whose proof (from Eisenstein-ness of `minpoly ↥𝒪[K] π`
onward) is reproduced verbatim here with `hEis`/`hβint` as direct hypotheses instead of consequences
of a `hram` total-ramification condition. -/
theorem adjoin_eq_integralClosure_of_isEisensteinAt
    {R : Type*} [CommRing R] [IsDomain R] [IsIntegrallyClosed R] [IsDiscreteValuationRing R]
    {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]
    {L : Type*} [Field L] [Algebra K L] [Algebra R L] [IsScalarTower R K L]
    [FiniteDimensional K L] [Algebra.IsSeparable K L]
    {ϖ : R} (hϖ : Irreducible ϖ) {β : L} (hβint : IsIntegral R β)
    (hEis : (minpoly R β).IsEisensteinAt (Submodule.span R ({ϖ} : Set R)))
    (hgen : (minpoly K β).natDegree = Module.finrank K L) :
    Algebra.adjoin R ({β} : Set L) = integralClosure R L := by
  have hxK : IsIntegral K β := hβint.tower_top
  -- `β` generates `L` over `K`.
  have hfr : Module.finrank K (IntermediateField.adjoin K ({β} : Set L)) = Module.finrank K L := by
    rw [IntermediateField.adjoin.finrank hxK, hgen]
  have htop : IntermediateField.adjoin K ({β} : Set L) = ⊤ := by
    apply IntermediateField.toSubalgebra_injective
    rw [IntermediateField.top_toSubalgebra]
    apply Algebra.toSubmodule_eq_top.1
    apply Submodule.eq_top_of_finrank_eq
    rw [Subalgebra.finrank_toSubmodule]
    exact hfr
  have htopalg : Algebra.adjoin K ({β} : Set L) = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic hxK.isAlgebraic, htop,
      IntermediateField.top_toSubalgebra]
  -- A `PowerBasis K L` with generator `β`.
  let B0 : PowerBasis K ↥(Algebra.adjoin K ({β} : Set L)) := Algebra.adjoin.powerBasis hxK
  let e : ↥(Algebra.adjoin K ({β} : Set L)) ≃ₐ[K] L :=
    (Subalgebra.equivOfEq _ _ htopalg).trans Subalgebra.topEquiv
  let B : PowerBasis K L := B0.map e
  have hBgen : B.gen = β := by
    show e B0.gen = β
    rw [Algebra.adjoin.powerBasis_gen]
    show ((Subalgebra.equivOfEq _ _ htopalg).trans Subalgebra.topEquiv)
        (⟨β, Algebra.subset_adjoin rfl⟩ : ↥(Algebra.adjoin K ({β} : Set L))) = β
    rw [AlgEquiv.trans_apply, Subalgebra.equivOfEq_apply, Subalgebra.topEquiv_apply]
  have hBint : IsIntegral R B.gen := hBgen ▸ hβint
  have hEis' : (minpoly R B.gen).IsEisensteinAt (Submodule.span R ({ϖ} : Set R)) := hBgen ▸ hEis
  have hϖPrime : Prime ϖ := by
    haveI := PrincipalIdealRing.to_uniqueFactorizationMonoid (R := R)
    exact UniqueFactorizationMonoid.irreducible_iff_prime.mp hϖ
  refine le_antisymm (adjoin_le_integralClosure hβint) ?_
  intro z hz
  have hzint : IsIntegral R z := hz
  -- `discr K B.basis` is a nonzero element of `R`, hence an associate of `ϖ ^ m`.
  have hdint : IsIntegral R (Algebra.discr K B.basis) :=
    Algebra.discr_isIntegral K (R := R) (b := ⇑B.basis) fun i => by
      rw [B.basis_eq_pow i]; exact hBint.pow _
  obtain ⟨d, hd⟩ := IsIntegrallyClosed.isIntegral_iff.mp hdint
  have hdne : d ≠ 0 := by
    intro h0
    apply Algebra.discr_not_zero_of_basis (K := K) (L := L) B.basis
    rw [← hd, h0, map_zero]
  obtain ⟨m, hassoc⟩ := IsDiscreteValuationRing.associated_pow_irreducible hdne hϖ
  obtain ⟨v, hv⟩ := hassoc.symm
  have hmem : Algebra.discr K B.basis • z ∈ Algebra.adjoin R ({B.gen} : Set L) :=
    Algebra.discr_mul_isIntegral_mem_adjoin K (R := R) hBint hzint
  have hdz : d • z = Algebra.discr K B.basis • z := by
    rw [← hd, IsScalarTower.algebraMap_smul K d z]
  rw [← hdz, ← hv, mul_smul] at hmem
  have hmem2 : ((v⁻¹ : Rˣ) : R) • ((ϖ ^ m : R) • ((v : R) • z)) ∈
      Algebra.adjoin R ({B.gen} : Set L) :=
    Subalgebra.smul_mem _ hmem _
  have heq : ((v⁻¹ : Rˣ) : R) • ((ϖ ^ m : R) • ((v : R) • z)) = (ϖ ^ m : R) • z := by
    rw [smul_smul, smul_smul,
      show ((v⁻¹ : Rˣ) : R) * ϖ ^ m * (v : R) = ϖ ^ m * (((v⁻¹ : Rˣ) : R) * (v : R)) by ring,
      ← Units.val_mul, inv_mul_cancel, Units.val_one, mul_one]
  rw [heq] at hmem2
  have := mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt hϖPrime hBint hzint hmem2 hEis'
  rwa [hBgen] at this

end
