/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.Ideal.GoingUp
import Mathlib.RingTheory.Jacobson.Ideal
import Mathlib.RingTheory.LocalRing.RingHom.Basic
import Mathlib.RingTheory.Nilpotent.Basic
import Mathlib.RingTheory.Adjoin.Basic

/-!
# An integral extension of a local ring is local once its "residual" quotient is

`ROADMAP.md` `§57` records residue-field preservation for the second Lubin-Tate tower step
(`O_{K_2} / O_{K_1}`) as blocked on `[IsLocalRing (integralClosure O_{K_1} (nextSplittingField P₂))]`, an instance
`IsLocalRing.residueFieldEquivOfAdjoinSingleton` bakes directly into its hypotheses. Monogenicity of
`O_{K_2}` over `O_{K_1}` (`Langlands/LubinTateTowerStepMonogenic.lean`) does not by itself supply
`IsLocalRing`, and at this level `IsLocalRing` cannot be obtained the way it was at the `K → K_1`
level (`Langlands/MonogenicIntegralClosure.lean`'s `isDiscreteValuationRing_integralClosure`), because
that route needs a `ValuativeRel (K_1 P)` instance the whole `K_1 → K_2` arc was built to avoid
(`Langlands/LubinTateTowerStepMonogenic.lean`'s module docstring).

This file proves the classical "going-up" replacement instead, with **no valuation theory at all**:

> If `R` is local and `S` is integral over `R`, then `S` is local as soon as the quotient
> `S ⧸ (𝔪_R) S` is local.

## Main results

* `IsLocalRing.of_isIntegral_of_isLocalRing_quotient_map_maximalIdeal` : the general lemma above.
  `R` need not be a domain, `S` need not be a domain, and `𝔪_R S` need not be principal or generated
  by a single element — the only inputs are `[IsLocalRing R]`, `[Algebra.IsIntegral R S]`, and
  `[IsLocalRing (S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R))]`. This is more general than the
  route `ROADMAP.md §57` sketched (which assumed `S` a domain, going through
  `Ideal.isMaximal_comap_of_isIntegral_of_isMaximal` — that lemma, checked directly here, needs no
  domain hypothesis either) and than a nilpotence-specific argument (`S ⧸ 𝔪_R S` local is used as a
  black box; nothing about it being `κ[X]/(X^q)` or `π` being nilpotent enters this file at all).
* `IsLocalHom.algebraMap_of_isIntegral` : once `[IsLocalRing R] [IsLocalRing S] [Algebra.IsIntegral R
  S]` hold, `algebraMap R S` is automatically a local homomorphism — the maximal ideal of `S`
  contracts to the maximal ideal of `R` by the same going-up fact, so `IsLocalHom` costs nothing
  further once `IsLocalRing S` is in hand (whether obtained from the lemma above or otherwise).
* `IsLocalRing.of_isNilpotent_of_adjoin_eq_top` : a companion, non-integral-extension-specific lemma
  for discharging the `[IsLocalRing (S ⧸ 𝔪_R S)]` hypothesis the first bullet needs at a concrete
  instantiation — `R` local, `T` an `R`-algebra killed by `maximalIdeal R` and generated by a single
  nilpotent element, is itself local. Used by `Langlands/LubinTateTowerStepLocalRing.lean` to close
  `IsLocalRing (O_{K_2} ⧸ 𝔪_{O_{K_1}} O_{K_2})` directly from `P₂`'s Eisenstein/distinguished shape.

## Proof idea

Every maximal ideal `M` of `S` contracts, by `Ideal.isMaximal_comap_of_isIntegral_of_isMaximal`, to a
maximal ideal of `R` — hence, `R` being local, to `𝔪_R` itself — so `M ⊇ 𝔪_R S =: J` for *every*
maximal ideal `M`, i.e. `J` lies in the Jacobson radical `Ideal.jacobson (⊥ : Ideal S)`. Given
`[IsLocalRing (S ⧸ J)]`, `S`'s local-ring criterion `IsLocalRing.of_isUnit_or_isUnit_one_sub_self`
reduces to: for `a : S`, since `S ⧸ J` is local, `mk a` or `1 - mk a` is a unit in `S ⧸ J`; lifting an
inverse `e` of the unit one and using `J ⊆ Jacobson(⊥ : Ideal S)`,
`Ideal.isUnit_of_sub_one_mem_jacobson_bot` promotes the *product* `a * e` (or `(1 - a) * e`) to a unit
of `S` itself, and `isUnit_of_mul_isUnit_left` then extracts that `a` (or `1 - a`) itself is a unit.
No Weierstrass/nilpotence argument for `S ⧸ J` is needed here — it is entirely the caller's job to
supply `[IsLocalRing (S ⧸ J)]`, however that quotient happens to be identified at a given
instantiation (e.g. `κ[X]/(X^q)` for `S` monogenic by an Eisenstein polynomial).
-/

open IsLocalRing

/-- **An integral extension of a local ring is local once its `𝔪_R`-quotient is.** `R` local,
`S` integral over `R`; if `S ⧸ (𝔪_R) S` is local, then `S` is local.

No domain hypothesis on `R` or `S` is needed: `Ideal.isMaximal_comap_of_isIntegral_of_isMaximal`
(the going-up fact every maximal ideal of `S` contracts to a maximal ideal of `R`) holds for
arbitrary commutative rings, not just domains. -/
theorem IsLocalRing.of_isIntegral_of_isLocalRing_quotient_map_maximalIdeal
    {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S] [Algebra R S]
    [Algebra.IsIntegral R S]
    [IsLocalRing (S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R))] :
    IsLocalRing S := by
  set J : Ideal S := Ideal.map (algebraMap R S) (maximalIdeal R) with hJdef
  haveI : Nontrivial S := (Ideal.Quotient.mk_surjective (I := J)).nontrivial
  -- Every maximal ideal of `S` contains `J`, since it contracts to `R`'s unique maximal ideal.
  have hJmax : ∀ M : Ideal S, M.IsMaximal → J ≤ M := by
    intro M hM
    have hcomap : (M.comap (algebraMap R S)).IsMaximal :=
      Ideal.isMaximal_comap_of_isIntegral_of_isMaximal M
    rw [hJdef, Ideal.map_le_iff_le_comap, IsLocalRing.eq_maximalIdeal hcomap]
  have hJjac : J ≤ Ideal.jacobson (⊥ : Ideal S) :=
    le_sInf fun M hM => hJmax M hM.2
  refine IsLocalRing.of_isUnit_or_isUnit_one_sub_self fun a => ?_
  rcases IsLocalRing.isUnit_or_isUnit_one_sub_self (Ideal.Quotient.mk J a) with h | h
  · obtain ⟨s, hs⟩ := h.exists_right_inv
    obtain ⟨e, rfl⟩ := Ideal.Quotient.mk_surjective s
    have hme : Ideal.Quotient.mk J (a * e) = 1 := by rw [map_mul]; exact hs
    have hmem : a * e - 1 ∈ J := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, hme, map_one, sub_self]
    exact Or.inl (isUnit_of_mul_isUnit_left
      (Ideal.isUnit_of_sub_one_mem_jacobson_bot _ (hJjac hmem)))
  · have h' : IsUnit (Ideal.Quotient.mk J (1 - a)) := by rw [map_sub, map_one]; exact h
    obtain ⟨s, hs⟩ := h'.exists_right_inv
    obtain ⟨e, rfl⟩ := Ideal.Quotient.mk_surjective s
    have hme : Ideal.Quotient.mk J ((1 - a) * e) = 1 := by rw [map_mul]; exact hs
    have hmem : (1 - a) * e - 1 ∈ J := by
      rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, hme, map_one, sub_self]
    exact Or.inr (isUnit_of_mul_isUnit_left
      (Ideal.isUnit_of_sub_one_mem_jacobson_bot _ (hJjac hmem)))

/-- **`algebraMap R S` is automatically a local homomorphism, for `R`, `S` local and `S` integral
over `R`.** The maximal ideal of `S` contracts (`Ideal.isMaximal_comap_of_isIntegral_of_isMaximal`)
to a maximal ideal of `R`, hence — `R` being local — to `R`'s unique maximal ideal itself; that
equality is exactly one of the conditions `IsLocalRing.local_hom_TFAE` shows equivalent to
`IsLocalHom`. -/
theorem IsLocalHom.algebraMap_of_isIntegral
    {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S] [IsLocalRing S] [Algebra R S]
    [Algebra.IsIntegral R S] :
    IsLocalHom (algebraMap R S) := by
  have hcomap : (maximalIdeal S).comap (algebraMap R S) = maximalIdeal R :=
    IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_comap_of_isIntegral_of_isMaximal (maximalIdeal S))
  exact ((IsLocalRing.local_hom_TFAE (algebraMap R S)).out 3 0).mp hcomap.ge

/-- **A ring generated over a local ring's residue field by a single nilpotent element is local.**
`R` local, `T` an `R`-algebra on which `maximalIdeal R` acts as `0` (i.e. `T` is genuinely an
algebra over `R ⧸ maximalIdeal R`, e.g. `T := S ⧸ (maximalIdeal R) S` for some `R`-algebra `S`), `T`
generated as an `R`-algebra by a single nilpotent `β : T`. Then `T` is local.

This is the standard fact that a finite-dimensional local algebra over a field, generated by one
nilpotent element, is `κ[X]/(X^n)`-shaped and hence local — proved here directly via the local-ring
criterion `IsLocalRing.of_isUnit_or_isUnit_one_sub_self`, without constructing the `κ[X]/(X^n)`
isomorphism: every `a : T` is `algebraMap R T r + β * d` for some `r : R`, `d : T` (splitting off the
constant coefficient of a generating polynomial, `Polynomial.X_mul_divX_add`); if `r ∈ maximalIdeal
R` the first summand vanishes (`hR0`) and `a` itself is nilpotent (a nilpotent times anything is
nilpotent), so `1 - a` is a unit (`IsNilpotent.isUnit_one_sub`); if `r` is a unit in `R` (`R` local,
so this is the only remaining case), `algebraMap R T r` is a unit and `a` is unit-plus-nilpotent,
hence a unit (`IsNilpotent.isUnit_add_left_of_commute`). -/
theorem IsLocalRing.of_isNilpotent_of_adjoin_eq_top
    {R T : Type*} [CommRing R] [IsLocalRing R] [CommRing T] [Nontrivial T] [Algebra R T]
    (hR0 : ∀ m ∈ maximalIdeal R, algebraMap R T m = 0)
    {β : T} (hβnil : IsNilpotent β) (hadj : Algebra.adjoin R ({β} : Set T) = ⊤) :
    IsLocalRing T := by
  refine IsLocalRing.of_isUnit_or_isUnit_one_sub_self fun a => ?_
  have ha : a ∈ Algebra.adjoin R ({β} : Set T) := hadj ▸ Algebra.mem_top
  rw [Algebra.adjoin_singleton_eq_range_aeval] at ha
  obtain ⟨p, hp⟩ := ha
  have hp' : Polynomial.aeval β p = a := hp
  have hsplit : algebraMap R T (p.coeff 0) + β * Polynomial.aeval β p.divX = a := by
    have key : Polynomial.aeval β (Polynomial.X * p.divX + Polynomial.C (p.coeff 0)) =
        Polynomial.aeval β p := by rw [Polynomial.X_mul_divX_add]
    rw [← hp', ← key, map_add, map_mul, Polynomial.aeval_X, Polynomial.aeval_C, add_comm]
  have hbdnil : IsNilpotent (β * Polynomial.aeval β p.divX) :=
    Commute.isNilpotent_mul_right (Commute.all _ _) hβnil
  by_cases hr : p.coeff 0 ∈ maximalIdeal R
  · have hc0 : algebraMap R T (p.coeff 0) = 0 := hR0 _ hr
    have ha_eq : a = β * Polynomial.aeval β p.divX := by rw [← hsplit, hc0, zero_add]
    exact Or.inr (ha_eq ▸ IsNilpotent.isUnit_one_sub hbdnil)
  · have hru : IsUnit (p.coeff 0) := by
      by_contra hnu
      exact hr ((IsLocalRing.mem_maximalIdeal _).mpr (mem_nonunits_iff.mpr hnu))
    have hcunit : IsUnit (algebraMap R T (p.coeff 0)) := hru.map (algebraMap R T)
    have ha_eq : a = algebraMap R T (p.coeff 0) + β * Polynomial.aeval β p.divX := hsplit.symm
    exact Or.inl (ha_eq ▸
      IsNilpotent.isUnit_add_left_of_commute hbdnil hcunit (Commute.all _ _))

/-- **The maximal ideal of a local ring generated by one nilpotent element over a local base is
exactly the span of that element.** Same hypotheses as `IsLocalRing.of_isNilpotent_of_adjoin_eq_top`
(`R` local, `T` an `R ⧸ maximalIdeal R`-algebra generated by a single nilpotent `β`), now taking
`[IsLocalRing T]` as an explicit hypothesis (supplied by the theorem above, or otherwise) rather than
re-deriving it, so callers who already have that instance do not pay for it twice — mirroring
`LubinTateTowerStepLocalRing.lean`'s `mem_maximalIdeal_of_isDistinguishedAt_root`, which takes
`[IsLocalRing (integralClosure R L)]` the same way.

Proof: `β` itself is a nonunit (nilpotent elements are never units in a nontrivial ring,
`IsNilpotent.not_isUnit`), so `Ideal.span {β} ⊆ maximalIdeal T` by ideal absorption. Conversely, for
`a ∈ maximalIdeal T`, the same decomposition `a = algebraMap R T (p.coeff 0) + β * (aeval β
p.divX)` used above forces `p.coeff 0 ∈ maximalIdeal R` (otherwise `algebraMap R T (p.coeff 0)` would
be a unit and, since `β * (aeval β p.divX)` is nilpotent, `a` itself would be a unit, contradicting
`a ∈ maximalIdeal T`), hence `algebraMap R T (p.coeff 0) = 0` (`hR0`) and `a = β * (aeval β p.divX) ∈
Ideal.span {β}` directly. -/
theorem IsLocalRing.maximalIdeal_eq_span_of_isNilpotent_of_adjoin_eq_top
    {R T : Type*} [CommRing R] [IsLocalRing R] [CommRing T] [IsLocalRing T] [Algebra R T]
    (hR0 : ∀ m ∈ maximalIdeal R, algebraMap R T m = 0)
    {β : T} (hβnil : IsNilpotent β) (hadj : Algebra.adjoin R ({β} : Set T) = ⊤) :
    maximalIdeal T = Ideal.span {β} := by
  have hβnu : ¬ IsUnit β := hβnil.not_isUnit
  have hβmem : β ∈ maximalIdeal T :=
    (IsLocalRing.mem_maximalIdeal β).mpr (mem_nonunits_iff.mpr hβnu)
  refine le_antisymm (fun a ha => ?_) (by
    rw [Ideal.span_le, Set.singleton_subset_iff]; exact hβmem)
  have ha' : a ∈ Algebra.adjoin R ({β} : Set T) := hadj ▸ Algebra.mem_top
  rw [Algebra.adjoin_singleton_eq_range_aeval] at ha'
  obtain ⟨p, hp⟩ := ha'
  have hp' : Polynomial.aeval β p = a := hp
  have hsplit : algebraMap R T (p.coeff 0) + β * Polynomial.aeval β p.divX = a := by
    have key : Polynomial.aeval β (Polynomial.X * p.divX + Polynomial.C (p.coeff 0)) =
        Polynomial.aeval β p := by rw [Polynomial.X_mul_divX_add]
    rw [← hp', ← key, map_add, map_mul, Polynomial.aeval_X, Polynomial.aeval_C, add_comm]
  have hbdnil : IsNilpotent (β * Polynomial.aeval β p.divX) :=
    Commute.isNilpotent_mul_right (Commute.all _ _) hβnil
  by_cases hr : p.coeff 0 ∈ maximalIdeal R
  · have hc0 : algebraMap R T (p.coeff 0) = 0 := hR0 _ hr
    have ha_eq : a = β * Polynomial.aeval β p.divX := by rw [← hsplit, hc0, zero_add]
    exact Ideal.mem_span_singleton.mpr ⟨Polynomial.aeval β p.divX, ha_eq⟩
  · exfalso
    have hru : IsUnit (p.coeff 0) := by
      by_contra hnu
      exact hr ((IsLocalRing.mem_maximalIdeal _).mpr (mem_nonunits_iff.mpr hnu))
    have hcunit : IsUnit (algebraMap R T (p.coeff 0)) := hru.map (algebraMap R T)
    have haunit : IsUnit a := hsplit ▸
      IsNilpotent.isUnit_add_left_of_commute hbdnil hcunit (Commute.all _ _)
    exact (mem_nonunits_iff.mp ((IsLocalRing.mem_maximalIdeal a).mp ha)) haunit
