/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Langlands.LubinTateTowerStepRootConnect
import Langlands.LubinTateSplittingFieldDegree

/-!
# `K_1⟮β⟯ = nextSplittingField` and `[nextSplittingField : K_1] = q`

`ROADMAP.md`'s item 6 of the tower-step chain: reassembling item 5's transitivity
(`exists_piTorsion_translate_of_aeval_P₂_eq_zero`) and the `K_1 P → K_2` `piTorsion`-invariance fact
(`piTorsion_one_K_2_eq_algebraMap_image`) into the headline structural statement, mirroring
`Langlands.LubinTateSplittingFieldDegree`'s `K⟮α⟯ = ⊤`/`[K_1 : K] = q - 1` argument one level up.

## Main results

* `FPiEval_algebraMap_mem_adjoin` : **`F_π(β, algebraMap t) ∈ (K_1 P)⟮β⟯`**, for `β : nextSplittingField` in the
  open unit ball and `t : K_1 P` in the open unit ball. The `FPiEval` analogue of
  `LubinTate.eval_phiU_mem_adjoin`'s finite-dimensional-closed-subspace technique: each evaluation
  summand of the bivariate `F_π` series is a `K_1 P`-scalar (via `K_2.algebraMap_O_eq_comp_K_1`)
  times a power of `β`, hence lies in the finite-dimensional `K_1 P`-subspace `(K_1 P)⟮β⟯`, and the
  `HasSum` limit stays there too (`Submodule.mem_of_hasSum_of_finiteDimensional`).
* `adjoin_root_eq_top_K_2` : **`(K_1 P)⟮β⟯ = ⊤`**, for `β` any root of `P₂`'s image in `nextSplittingField`. Every
  other root `β'` differs from `β` by a `piTorsion hπ hf 1`-translate (item 5), and that translate is
  (Task 1) the `algebraMap`-image of a `K_1 P`-torsion point, so `β' = F_π(β, algebraMap t) ∈
  (K_1 P)⟮β⟯` by the lemma above; since `nextSplittingField` is *by construction* the splitting field of `P₂`'s
  image, generated by its roots (`Polynomial.IsSplittingField.adjoin_rootSet`), this forces
  `(K_1 P)⟮β⟯ = ⊤`.
* `finrank_K_2_eq_residueCard` : **`Module.finrank (K_1 P) (nextSplittingField P₂) = residueCard O`** —
  `[nextSplittingField : K_1] = q`. Combines `adjoin_root_eq_top_K_2` with the already-computed
  `Module.finrank (K_1 P) (K_1 P)⟮β⟯ = residueCard O` (`exists_finrank_adjoin_eq_residueCard_K_2`) via
  `IntermediateField.finrank_top'`.
-/

@[expose] public section

noncomputable section

open scoped Polynomial IntermediateField

namespace LubinTate

open IsLocalRing PowerSeries Polynomial NonarchimedeanPowerSeriesEval
open NonarchimedeanMvPowerSeriesEvalFin2

variable {O : Type*} [CommRing O] [IsDomain O] [IsDiscreteValuationRing O]
  [Finite (ResidueField O)]
variable {K : Type*} [NontriviallyNormedField K] [IsUltrametricDist K] [ValuativeRel K]
  [(NormedField.valuation (K := K)).Compatible] [CompleteSpace K]
  [IsDiscreteValuationRing ↥(ValuativeRel.valuation K).valuationSubring]
  [Algebra O K] [IsFractionRing O K]
variable {π : O} {f : O⟦X⟧} {P : O[X]}
  {P₂ : (↥(integralClosure ↥(ValuativeRel.valuation K).valuationSubring (K_1 (K := K) P)))[X]}

/-! ## `F_π(β, algebraMap t)` stays inside `(K_1 P)⟮β⟯` -/

/-- **`F_π(β, algebraMap (K_1 P) nextSplittingField t) ∈ (K_1 P)⟮β⟯`**, for `β : nextSplittingField` and `t : K_1 P` both in the
open unit ball. The `FPiEval` analogue of `eval_phiU_mem_adjoin`: `F_π(β, t')` (`t' := algebraMap
(K_1 P) nextSplittingField t`) is a bivariate `tsum`, each of whose summands `algebraMap O nextSplittingField (coeff n Φ) * β ^ n 0
* t' ^ n 1` factors (via `K_2.algebraMap_O_eq_comp_K_1` and `map_pow`) as a `K_1 P`-scalar
(`algebraMap (K_1 P) nextSplittingField` applied to `algebraMap O (K_1 P) (coeff n Φ) * t ^ n 1`) times a power of
`β`, hence lies in the finite-dimensional `K_1 P`-subspace `(K_1 P)⟮β⟯` (finite-dimensional inside
`nextSplittingField`, since `nextSplittingField.instFiniteDimensional`); `Submodule.mem_of_hasSum_of_finiteDimensional` (`Langlands.
LubinTateSplittingFieldDegree`) places the limit back inside it. -/
theorem FPiEval_algebraMap_mem_adjoin (hOK : ∀ c : O, ‖algebraMap O K c‖ ≤ 1) {π : O}
    (hπ : Irreducible π) {f : O⟦X⟧} (hf : IsLubinTatePoly π (residueCard O) f)
    {β : nextSplittingField (K' := K_1 (K := K) P) P₂} (hβ : ‖β‖ < 1) {t : K_1 (K := K) P} (ht : ‖t‖ < 1) :
    letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
    FPiEval hπ hf β (algebraMap (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂) t) ∈
      (K_1 (K := K) P)⟮β⟯ := by
  letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
  set t' := algebraMap (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂) t with ht'def
  have ht' : ‖t'‖ < 1 := by
    rw [ht'def, nextSplittingField.norm_eq_spectralNorm, spectralNorm_extends]; exact ht
  have hsum := hasSum_FPiEval (K_2.hOK_transport (K := K) (P := P) P₂ hOK) hπ hf hβ ht'
  have hmem : ∀ n : Fin 2 →₀ ℕ,
      evalSummandMv (Phi hπ hf) (![β, t'] : Fin 2 → nextSplittingField (K' := K_1 (K := K) P) P₂) n ∈
      Subalgebra.toSubmodule
        ((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P)
          (nextSplittingField (K' := K_1 (K := K) P) P₂)).toSubalgebra := by
    intro n
    rw [Subalgebra.mem_toSubmodule, IntermediateField.mem_toSubalgebra]
    unfold evalSummandMv
    rw [Fin.prod_univ_two]
    show algebraMap O (nextSplittingField (K' := K_1 (K := K) P) P₂) (MvPowerSeries.coeff n (Phi hπ hf)) *
        ((![β, t'] : Fin 2 → nextSplittingField (K' := K_1 (K := K) P) P₂) 0 ^ n 0 *
          (![β, t'] : Fin 2 → nextSplittingField (K' := K_1 (K := K) P) P₂) 1 ^ n 1) ∈
      ((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂))
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one]
    rw [show algebraMap O (nextSplittingField (K' := K_1 (K := K) P) P₂) (MvPowerSeries.coeff n (Phi hπ hf)) =
        algebraMap (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂)
          (algebraMap O (K_1 (K := K) P) (MvPowerSeries.coeff n (Phi hπ hf))) from
      congrFun (K_2.algebraMap_O_eq_comp_K_1 (K := K) (P := P) hOK) _,
      ht'def, ← map_pow]
    refine mul_mem (IntermediateField.algebraMap_mem _ _)
      (mul_mem (pow_mem (IntermediateField.mem_adjoin_simple_self _ β) _)
        (IntermediateField.algebraMap_mem _ _))
  have hres := Submodule.mem_of_hasSum_of_finiteDimensional
    (Subalgebra.toSubmodule
      ((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P)
        (nextSplittingField (K' := K_1 (K := K) P) P₂)).toSubalgebra) hsum hmem
  rwa [Subalgebra.mem_toSubmodule, IntermediateField.mem_toSubalgebra] at hres

/-! ## `(K_1 P)⟮β⟯ = nextSplittingField` -/

/-- **`(K_1 P)⟮β⟯ = ⊤`, for `β` any root of `P₂`'s image in `nextSplittingField`.** `nextSplittingField` is *by construction* the
splitting field of `P₂`'s image over `K_1 P`, generated by its roots
(`Polynomial.IsSplittingField.adjoin_rootSet`). Every root `β'` differs from `β` by a `piTorsion hπ
hf 1`-translate (`exists_piTorsion_translate_of_aeval_P₂_eq_zero`, item 5), and — by `piTorsion_one_
K_2_eq_algebraMap_image` (Task 1's invariance fact) — that translate is the `algebraMap`-image of a
`K_1 P`-torsion point `t`, so `β' = F_π(β, algebraMap t) ∈ (K_1 P)⟮β⟯` by `FPiEval_algebraMap_mem_
adjoin`; `β` itself trivially lies in its own adjoin. -/
theorem adjoin_root_eq_top_K_2 (hOK : ∀ c : O, ‖algebraMap O K c‖ ≤ 1) {π : O}
    (hπ : Irreducible π) (hπnorm : ‖algebraMap O K π‖ < 1) {f : O⟦X⟧}
    (hf : IsLubinTatePoly π (residueCard O) f) {u : O⟦X⟧} (hu : IsUnit u)
    (heq : f = (P : O⟦X⟧) * u) (hPdist : P.IsDistinguishedAt (maximalIdeal O))
    (hPdeg : P.natDegree = residueCard O)
    {α' : ↥(integralClosure ↥(ValuativeRel.valuation K).valuationSubring (K_1 (K := K) P))}
    {u₂ : (↥(integralClosure ↥(ValuativeRel.valuation K).valuationSubring
      (K_1 (K := K) P)))⟦X⟧} (hu₂ : IsUnit u₂)
    (heq₂ : shifted f (towerHom (K := K) hOK P) α' = (P₂ : _⟦X⟧) * u₂)
    (hα'irr : Irreducible α') (hP₂dist : P₂.IsDistinguishedAt (maximalIdeal _))
    (hassoc : Associated (P₂.coeff 0) α') (hdeg : 0 < P₂.natDegree)
    (hα'norm : ‖algebraMap _ (nextSplittingField (K' := K_1 (K := K) P) P₂) (α' : _)‖ < 1)
    {α : K_1 (K := K) P} (hα'coe : (α' : K_1 (K := K) P) = α)
    {β : nextSplittingField (K' := K_1 (K := K) P) P₂}
    (hβroot : Polynomial.aeval β (P₂.map (algebraMap _ (K_1 (K := K) P))) = 0) :
    letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
    ((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂)) =
      ⊤ := by
  letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
  have hβnorm : ‖β‖ < 1 := norm_lt_one_of_aeval_P₂_eq_zero hα'irr hP₂dist hassoc hdeg hα'norm hβroot
  have hroots : ((P₂.map (algebraMap _ (K_1 (K := K) P))).rootSet
      (nextSplittingField (K' := K_1 (K := K) P) P₂)) ⊆
      (((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P)
        (nextSplittingField (K' := K_1 (K := K) P) P₂)).toSubalgebra : Set (nextSplittingField (K' := K_1 (K := K) P) P₂)) := by
    intro β' hβ'
    obtain ⟨-, hβ'root⟩ := Polynomial.mem_rootSet'.mp hβ'
    obtain ⟨t', ht'mem, ht'eq⟩ :=
      exists_piTorsion_translate_of_aeval_P₂_eq_zero hOK hπ hf hu₂ heq₂ hα'irr hP₂dist hassoc hdeg
        hα'norm hα'coe hβroot hβ'root
    rw [piTorsion_one_K_2_eq_algebraMap_image (K := K) (P := P) (P₂ := P₂) hOK hπ hπnorm hf hu heq
      hPdist hPdeg] at ht'mem
    obtain ⟨t, htmem, htmem'⟩ := ht'mem
    rw [SetLike.mem_coe, IntermediateField.mem_toSubalgebra, ht'eq, ← htmem']
    exact FPiEval_algebraMap_mem_adjoin hOK hπ hf hβnorm htmem.1
  have hle : (⊤ : Subalgebra (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂)) ≤
      ((K_1 (K := K) P)⟮β⟯ : IntermediateField (K_1 (K := K) P)
        (nextSplittingField (K' := K_1 (K := K) P) P₂)).toSubalgebra := by
    rw [← Polynomial.IsSplittingField.adjoin_rootSet (nextSplittingField (K' := K_1 (K := K) P) P₂)
      (P₂.map (algebraMap _ (K_1 (K := K) P)))]
    exact Algebra.adjoin_le hroots
  refine eq_top_iff.mpr fun x _ ↦ ?_
  exact (IntermediateField.mem_toSubalgebra _ x).mp (hle Algebra.mem_top)

/-! ## `[nextSplittingField : K_1] = q` -/

/-- **`Module.finrank (K_1 P) (nextSplittingField P₂) = residueCard O`** — `[nextSplittingField : K_1] = q`, the second genuine
tower-step degree computation of the Lubin-Tate arc. `exists_finrank_adjoin_eq_residueCard_K_2`
already supplies a root `β` of `P₂`'s image with `Module.finrank (K_1 P) (K_1 P)⟮β⟯ = residueCard O`;
`adjoin_root_eq_top_K_2` upgrades that same `β` to `(K_1 P)⟮β⟯ = ⊤`, so `IntermediateField.finrank_
top'` identifies `Module.finrank (K_1 P) (nextSplittingField P₂)` with `Module.finrank (K_1 P) (K_1 P)⟮β⟯`. -/
theorem finrank_K_2_eq_residueCard (hOK : ∀ c : O, ‖algebraMap O K c‖ ≤ 1) {π : O}
    (hπ : Irreducible π) (hπnorm : ‖algebraMap O K π‖ < 1) {f : O⟦X⟧}
    (hf : IsLubinTatePoly π (residueCard O) f) {u : O⟦X⟧} (hu : IsUnit u)
    (heq : f = (P : O⟦X⟧) * u) (hPdist : P.IsDistinguishedAt (maximalIdeal O))
    (hPdeg : P.natDegree = residueCard O)
    {α' : ↥(integralClosure ↥(ValuativeRel.valuation K).valuationSubring (K_1 (K := K) P))}
    {u₂ : (↥(integralClosure ↥(ValuativeRel.valuation K).valuationSubring
      (K_1 (K := K) P)))⟦X⟧} (hu₂ : IsUnit u₂)
    (heq₂ : shifted f (towerHom (K := K) hOK P) α' = (P₂ : _⟦X⟧) * u₂)
    (hα'irr : Irreducible α') (hP₂dist : P₂.IsDistinguishedAt (maximalIdeal _))
    (hassoc : Associated (P₂.coeff 0) α') (hdeg : 0 < P₂.natDegree)
    (hα'norm : ‖algebraMap _ (nextSplittingField (K' := K_1 (K := K) P) P₂) (α' : _)‖ < 1)
    {α : K_1 (K := K) P} (hα'coe : (α' : K_1 (K := K) P) = α)
    {β : nextSplittingField (K' := K_1 (K := K) P) P₂}
    (hβroot : Polynomial.aeval β (P₂.map (algebraMap _ (K_1 (K := K) P))) = 0)
    (hβfin : Module.finrank (K_1 (K := K) P) (K_1 (K := K) P)⟮β⟯ = residueCard O) :
    letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
    Module.finrank (K_1 (K := K) P) (nextSplittingField (K' := K_1 (K := K) P) P₂) = residueCard O := by
  letI := K_2.instAlgebraO (K := K) (P := P) P₂ hOK
  have htop := adjoin_root_eq_top_K_2 hOK hπ hπnorm hf hu heq hPdist hPdeg hu₂ heq₂ hα'irr hP₂dist
    hassoc hdeg hα'norm hα'coe hβroot
  rw [← IntermediateField.finrank_top' (F := K_1 (K := K) P)
    (E := nextSplittingField (K' := K_1 (K := K) P) P₂), ← htop]
  exact hβfin

end LubinTate

end
