import Mathlib.RingTheory.DedekindDomain.Different
import Mathlib.RingTheory.Conductor

/-!
# Discriminant a unit implies the monogenic order is the maximal order

The classical companion fact to `Mathlib.RingTheory.LocalRing.Etale`'s monogenicity +
unit-derivative-of-minpoly result: if `x` generates `L` over `K` (`Frac A`) and the derivative of
`x`'s minimal polynomial over `A` is a unit (the "discriminant is a unit" condition, since the
discriminant of a monic polynomial is, up to units, the norm of the derivative at a root), then the
monogenic order `A[x]` generated by `x` is *all* of `B` -- i.e. `B` is the maximal order (assuming
`B` is already known to be the integral closure of `A` in `L`, via `IsIntegralClosure B A L`).

Assembled entirely from existing Mathlib machinery for Dedekind domains, found by loogling
`discriminant`/`conductor`/`differentIdeal` combinations rather than assumed missing:
`conductor_mul_differentIdeal` (`𝔣ₓ * 𝔇 = (f'(x))` as ideals of `B`, `𝔣ₓ` the conductor of `A[x]`)
turns the unit-derivative hypothesis into `𝔣ₓ * 𝔇 = ⊤` (`Ideal.span_singleton_eq_top`), hence
`𝔣ₓ = ⊤` (`Ideal.mul_le_right`, `top_le_iff`), hence (`conductor_eq_top_iff_adjoin_eq_top`, already
in `Mathlib.RingTheory.Conductor`) `A[x] = ⊤`, i.e. `A[x] = B`.

## Note on placement

Kept in its own file, importing `Mathlib.RingTheory.DedekindDomain.Different` /
`Mathlib.RingTheory.Conductor` directly, rather than added to `Langlands.UnramifiedExtension`
(the file it is meant to eventually support `exists_restrictNormalHom_decompositionSubgroup_surjective`
in): adding those two imports to `Langlands.UnramifiedExtension` broke `Langlands.WeilGroup`'s build
(which imports `Langlands.UnramifiedExtension`) with instance-diamond failures around
`IsScalarTower 𝓀[K] _ (IsLocalRing.ResidueField _)` and `ResidueField.algebraOfIsIntegral` vs.
`IntermediateField.algebra'` -- some instance pulled in transitively by the Dedekind-domain
different/conductor machinery competes with `WeilGroup.lean`'s own careful residue-field algebra
tower setup. Not investigated further here (out of scope for landing this lemma standalone); when
this lemma is actually wired into `exists_restrictNormalHom_decompositionSubgroup_surjective`, that
diamond will need to be tracked down and resolved (or worked around, e.g. by using this lemma only
in a context that doesn't pull the heavy import into `WeilGroup.lean`'s transitive closure). -/

@[expose] public section

/-- **Discriminant a unit implies the monogenic order equals the maximal order.** -/
theorem Algebra.adjoin_eq_top_of_isUnit_aeval_derivative_minpoly
    (A K L : Type*) {B : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsFractionRing A K] [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A] [IsDedekindDomain B]
    [Module.IsTorsionFree A B]
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤)
    (hunit : IsUnit (Polynomial.aeval x (minpoly A x).derivative)) :
    Algebra.adjoin A {x} = ⊤ := by
  have hspan : conductor A x * differentIdeal A B = ⊤ := by
    rw [conductor_mul_differentIdeal A K L x hx]
    exact Ideal.span_singleton_eq_top.mpr hunit
  have hcond : conductor A x = ⊤ :=
    top_le_iff.mp (hspan ▸ Ideal.mul_le_right)
  exact adjoin_eq_top_of_conductor_eq_top hcond
