import Mathlib.RingTheory.DedekindDomain.Different
import Mathlib.RingTheory.Conductor

/-!
# Discriminant a unit implies the monogenic order is the maximal order

Companion to the monogenicity and unit-derivative-of-minpoly results of
`Mathlib.RingTheory.LocalRing.Etale`: if `x` generates `L` over `K = Frac A` and the derivative of
the minimal polynomial of `x` over `A`, evaluated at `x`, is a unit, then the monogenic order
`A[x]` is all of `B`. The hypothesis is the "discriminant is a unit" condition, since the
discriminant of a monic polynomial is, up to units, the norm of its derivative at a root; `B` is
the maximal order by the ambient `IsIntegralClosure B A L`.

The argument is assembled from Mathlib's Dedekind domain machinery.
`conductor_mul_differentIdeal` states `𝔣ₓ * 𝔇 = (f'(x))` as ideals of `B`, with `𝔣ₓ` the conductor
of `A[x]`; the unit hypothesis turns this into `𝔣ₓ * 𝔇 = ⊤` (`Ideal.span_singleton_eq_top`), hence
`𝔣ₓ = ⊤` (`Ideal.mul_le_right`, `top_le_iff`), hence `A[x] = ⊤` by
`conductor_eq_top_iff_adjoin_eq_top`.

## Implementation notes

This lemma is kept in its own file, importing `Mathlib.RingTheory.DedekindDomain.Different` and
`Mathlib.RingTheory.Conductor` directly, rather than in `Langlands.UnramifiedExtension`, whose
`exists_restrictNormalHom_decompositionSubgroup_surjective` it is intended to support. Adding those
imports to `Langlands.UnramifiedExtension` breaks the build of `Langlands.WeilGroup`, which imports
it, with instance diamonds around `IsScalarTower 𝓀[K] _ (IsLocalRing.ResidueField _)` and
`ResidueField.algebraOfIsIntegral` versus `IntermediateField.algebra'`: an instance pulled in
transitively by the different/conductor machinery competes with the residue field algebra tower
of `Langlands.WeilGroup`. Wiring this lemma into
`exists_restrictNormalHom_decompositionSubgroup_surjective` requires resolving that diamond, or
using the lemma only where the import stays out of the transitive closure of
`Langlands.WeilGroup`. -/

@[expose] public section

/-- If `x : B` generates `L` over `K` and `(minpoly A x).derivative` evaluated at `x` is a unit,
then `A[x] = B`: the monogenic order generated by `x` is the maximal order. -/
theorem Algebra.adjoin_eq_top_of_isUnit_aeval_derivative_minpoly
    (A K L : Type*) {B : Type*} [CommRing A] [Field K] [CommRing B] [Field L]
    [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
    [IsScalarTower A K L] [IsScalarTower A B L]
    [IsDomain A] [IsFractionRing A K] [FiniteDimensional K L] [Algebra.IsSeparable K L]
    [IsIntegralClosure B A L] [IsIntegrallyClosed A] [IsDedekindDomain B]
    [Module.IsTorsionFree A B]
    (x : B) (hx : Algebra.adjoin K {algebraMap B L x} = ⊤)
    (hunit : IsUnit (Polynomial.aeval x (minpoly A x).derivative)) :
    Algebra.adjoin A {x} = ⊤ := by
  have hspan : conductor A x * differentIdeal A B = ⊤ := by
    rw [conductor_mul_differentIdeal A K L x hx]
    exact Ideal.span_singleton_eq_top.mpr hunit
  have hcond : conductor A x = ⊤ :=
    top_le_iff.mp (hspan ▸ Ideal.mul_le_right)
  exact adjoin_eq_top_of_conductor_eq_top hcond
