/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.Ideal.Over
import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# A Nakayama-style criterion for monogenicity over a local ring

Serre's tower-composition argument for `𝒪_L = 𝒪_K[a]` (*Local Fields* III §6) does not, on
reflection, need a discriminant/index computation at all: it is a direct corollary of Nakayama's
lemma, already available in Mathlib as `IsLocalRing.map_mkQ_eq_top`
(`Mathlib.RingTheory.LocalRing.Module`). For `R` local with maximal ideal `𝔪` and `S` a finite
`R`-algebra, a submodule `N ≤ S` equals `⊤` iff its image in `S ⧸ 𝔪 • ⊤` (the reduction mod `𝔪`) is
`⊤`. Applied to `N := Subalgebra.toSubmodule (Algebra.adjoin R {a})`, this reduces
`Algebra.adjoin R {a} = ⊤` to a statement purely about the residue algebra `S ⧸ 𝔪S`: do the images
of the powers of `a` span it?

This supersedes the `differentIdeal`/discriminant-tower route flagged as the "best candidate" by
`ROADMAP.md`'s twenty-third/twenty-fourth passes: that route needed translating this repo's
`Algebra.discr`/`spectralNorm` formalism into the ideal-valued `differentIdeal`/`FractionalIdeal`
formalism (untranslated, and separately needed a classical resultant-of-a-sum identity for
`disc_K(β + c•π)` that is not in Mathlib and would need to be built from scratch,
`Mathlib.RingTheory.Polynomial.Resultant.Basic` having no connection to `Algebra.discr` at all,
confirmed by grep this pass). The Nakayama route needs no discriminant, no resultant, and no
Eisenstein-ness of `minpoly K a` (which genuinely fails for the composite generator in the mixed
ramification case, confirmed this pass: `mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt`
requires `(minpoly R B.gen).IsEisensteinAt`, and Eisenstein-ness needs the *whole* extension totally
ramified). It also gives the field-level primitive-element fact
(`Langlands.PrimitiveElementFusion.exists_scalar_add_smul_primitive`) as a free corollary rather
than a separate input: if the powers of `a` already span the free rank-`ef` `R`-module `S`, `a`
cannot satisfy a shorter algebraic relation over `K`, so `(minpoly K a).natDegree = ef` follows
automatically once `Algebra.adjoin R {a} = ⊤` is known, with no separate pigeonhole argument needed.

## Main result

* `LocalField.adjoin_eq_top_of_map_mkQ_eq_top` : for `R` local, `S` a finite `R`-algebra, `a : S`,
  if the image of `Algebra.adjoin R {a}` in `S ⧸ (maximalIdeal R • ⊤)` is all of that quotient,
  then `Algebra.adjoin R {a} = ⊤`.
* `LocalField.adjoin_singleton_eq_top_of_forall_sub_mem_span` : the totally-ramified specialization,
  in the form the residue data actually arrives in — if every `s : S` is congruent to a scalar mod
  `ϖ` and some power `ϖ ^ e` already lies in `𝔪_R S`, then `ϖ` generates `S` over `R`.

## Status update (twenty-sixth pass)

Items (1) and (2) below were the two gaps left open when this file was written. **Item (2) is now
closed** — `Langlands.ArtinianPrimitiveElement`'s `LocalField.adjoin_add_nilpotent_eq_top` proves
it, and with `c = 1`, so no scalar search is needed at the residue level. **Item (1) is no longer
required in the form stated**: `adjoin_eq_top_of_adjoin_quotient_eq_top` (below) plus the Artinian
primitive element theorem compose into
`LocalField.exists_adjoin_eq_top_of_residue_nilpotent`, which needs only that the residue algebra
`S ⧸ 𝔪_R S` contains a separable residue field `κ` and a nilpotent `π` with `S ⧸ 𝔪_R S = κ + π ·
(S ⧸ 𝔪_R S)` — *not* an explicit isomorphism with `κ_M[T] ⧸ (T ^ e)`.

What is still missing is the *ramification input* discharging those three hypotheses for the actual
tower, and — logically prior to that — a tower object at all: see `ROADMAP.md`'s twenty-sixth pass.

## What remains (as assessed when this file was written)

The hypothesis this lemma needs — that the images of the powers of `a := β + c • π` span
`S ⧸ 𝔪_K S` for `S := 𝒪_N` — is itself a nontrivial fact requiring:

1. Identifying `𝒪_N ⧸ 𝔪_K 𝒪_N` concretely. Using `𝒪_M = 𝒪_K[β]` (unramified: `𝔪_K 𝒪_M = 𝔪_M`) and
   `𝒪_N = 𝒪_M[π]` (Eisenstein of degree `e`), the classical computation is
   `𝒪_N ⧸ 𝔪_K 𝒪_N ≅ κ_M[T] ⧸ (T ^ e)` where `κ_M := 𝒪_M ⧸ 𝔪_M` is generated over `κ_K` by the image
   of `β`. This ring isomorphism is not yet built in this repo.
2. An "Artinian primitive element" fact: in `κ_M[T] ⧸ (T ^ e)` (`κ_M / κ_K` a degree-`f` field
   extension generated by `β̄`), do the powers of `β̄ + c̄ • T` span the whole `κ_K`-algebra (of
   `κ_K`-dimension `ef`) for a suitable `c̄`? This is a linear-algebra fact about a nilpotent
   extension of a field extension, genuinely different in character from Mathlib's
   field-only primitive element theorem (`Mathlib.FieldTheory.PrimitiveElement`, which does not
   apply to the non-reduced ring `κ_M[T] ⧸ (T ^ e)`) and not found in Mathlib by this pass's search
   (`grep -rn "primitive" Mathlib/RingTheory/` turns up only field-theoretic and
   `PrimitiveRoots`/`IsPrimitiveRoot` hits, nothing about generation of Artinian local algebras).
   Notably, `Mathlib.RingTheory.LocalRing.Etale`'s own `exists_adjoin_eq_top` (the theorem this
   repo's unramified half already uses, per `ROADMAP.md`'s thirteenth pass) proves monogenicity of
   an *étale* (residue extension separable, ramification index `1`) local extension by exactly
   this Nakayama pattern — "lifts a primitive element of the residue field extension via Nakayama's
   lemma" (its own docstring, `LocalRing/Etale.lean:92`) — confirming the pattern is the right one
   in the unramified case, where the residue quotient genuinely is a field and
   `Field.exists_primitive_element` applies directly. The totally-ramified/mixed case here differs
   exactly because `S ⧸ 𝔪_K S` is a non-reduced Artinian ring (`T` nilpotent), not a field, so that
   theorem's proof does not transfer verbatim; a new argument for the Artinian case is needed.

Neither (1) nor (2) was attempted in code this pass; both are precisely scoped, genuinely new
mathematical content, not lemma lookups.
-/

namespace LocalField

/-- **Nakayama-style monogenicity criterion.** For `R` local (maximal ideal `𝔪`) and `S` a finite
`R`-algebra, if the image of `Algebra.adjoin R {a}` (viewed as a submodule of `S`) under reduction
mod `𝔪 • ⊤` is everything, then `Algebra.adjoin R {a} = ⊤` outright — i.e. `a` generates `S` as an
`R`-algebra.

This is `IsLocalRing.map_mkQ_eq_top` (`Mathlib.RingTheory.LocalRing.Module`), specialized to the
submodule underlying a singly-generated subalgebra. -/
theorem adjoin_eq_top_of_map_mkQ_eq_top {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] [Module.Finite R S] {a : S}
    (h : (Subalgebra.toSubmodule (Algebra.adjoin R ({a} : Set S))).map
        (Submodule.mkQ (IsLocalRing.maximalIdeal R • (⊤ : Submodule R S))) = ⊤) :
    Algebra.adjoin R ({a} : Set S) = ⊤ := by
  rw [← Algebra.toSubmodule_eq_top]
  exact IsLocalRing.map_mkQ_eq_top.mp h

open Polynomial IsLocalRing in
/-- **Monogenicity descends from the residue algebra.** If the image of `β` generates
`S ⧸ 𝔪_R S` as an algebra over the residue field `R ⧸ 𝔪_R`, then `β` generates `S` over `R`.

This is the usable form of `adjoin_eq_top_of_map_mkQ_eq_top`: it replaces the submodule-image
hypothesis by an honest *algebra*-generation statement about the residue ring `S ⧸ 𝔪_R S`, which is
what `Langlands.ArtinianPrimitiveElement` supplies.

Mathlib's `IsLocalRing.adjoin_residue_eq_top_iff_adjoin_eq_top`
(`Mathlib/RingTheory/LocalRing/Etale.lean:63`) is the same statement for the quotient by `𝔪_S`
rather than `𝔪_R S`, and needs `[Algebra.FormallyUnramified R S]` precisely to identify the two
(via `Algebra.FormallyUnramified.map_maximalIdeal`). In the ramified case `𝔪_R S ⊊ 𝔪_S`, so that
lemma does not apply; the proof below is its forward direction with the unramifiedness step
removed, quotienting by `𝔪_R S` throughout. -/
theorem adjoin_eq_top_of_adjoin_quotient_eq_top {R S : Type*} [CommRing R] [IsLocalRing R]
    [CommRing S] [Algebra R S] [Module.Finite R S] (β : S)
    (h : Algebra.adjoin (R ⧸ maximalIdeal R)
        ({Ideal.Quotient.mk (Ideal.map (algebraMap R S) (maximalIdeal R)) β} :
          Set (S ⧸ Ideal.map (algebraMap R S) (maximalIdeal R))) = ⊤) :
    Algebra.adjoin R ({β} : Set S) = ⊤ := by
  refine eq_top_iff.mpr <| Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥)
    (?_ : ⊤ ≤ (Algebra.adjoin R ({β} : Set S)).toSubmodule ⊔ maximalIdeal R • ⊤)
  intro s _
  rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at h
  obtain ⟨p, hp⟩ := h (Ideal.Quotient.mk _ s)
  obtain ⟨q, rfl⟩ := Polynomial.map_surjective _ Ideal.Quotient.mk_surjective p
  rw [Ideal.smul_top_eq_map]
  refine Submodule.mem_sup.mpr ⟨aeval β q, ?_, s - aeval β q, ?_, by ring⟩
  · rw [Algebra.adjoin_singleton_eq_range_aeval]; exact ⟨q, rfl⟩
  · rw [Submodule.restrictScalars_mem, ← Ideal.Quotient.eq]
    rw [← map_aeval_eq_aeval_map (ψ := Ideal.Quotient.mk _)
      (φ := Ideal.Quotient.mk (maximalIdeal R)) rfl] at hp
    exact hp.symm

open Polynomial IsLocalRing in
/-- **Monogenicity from a residue-surjectivity hypothesis and a single power.** For `R` local and
`S` a finite `R`-algebra, if every `s : S` is congruent to (the image of) a scalar modulo `ϖ`, and
some power `ϖ ^ e` already lies in `𝔪_R S`, then `ϖ` generates `S` as an `R`-algebra.

This is the shape the totally ramified case supplies: `hres` is surjectivity of the residue map
`R → S ⧸ (ϖ)` (for `S` local with `𝔪_S = (ϖ)`, exactly trivial residue extension) and `he` is the
ramification identity `𝔪_R S = 𝔪_S ^ e = (ϖ ^ e)`. Neither hypothesis mentions a valuation, a
discrete valuation ring, or an Eisenstein polynomial, so the lemma applies verbatim at completions,
at localizations, and at abstract local rings alike.

The proof is the classical `ϖ`-adic expansion: `hres` peels one coefficient at a time, giving
`s ≡ aeval ϖ q mod (ϖ ^ n)` for every `n` and a suitable `q : R[X]`; taking `n = e` puts the
remainder in `𝔪_R • ⊤`, and Nakayama (`Submodule.le_of_le_smul_of_le_jacobson_bot`, the same engine
as `adjoin_eq_top_of_map_mkQ_eq_top` above) upgrades that to equality. -/
theorem adjoin_singleton_eq_top_of_forall_sub_mem_span {R S : Type*} [CommRing R] [IsLocalRing R]
    [CommRing S] [Algebra R S] [Module.Finite R S] {ϖ : S}
    (hres : ∀ s : S, ∃ r : R, s - algebraMap R S r ∈ Ideal.span {ϖ})
    {e : ℕ} (he : ϖ ^ e ∈ Ideal.map (algebraMap R S) (maximalIdeal R)) :
    Algebra.adjoin R ({ϖ} : Set S) = ⊤ := by
  have key : ∀ (n : ℕ) (s : S), ∃ q : R[X], s - aeval ϖ q ∈ Ideal.span {ϖ ^ n} := by
    intro n
    induction n with
    | zero => intro s; exact ⟨0, by simp⟩
    | succ n ih =>
      intro s
      obtain ⟨q, hq⟩ := ih s
      obtain ⟨t, ht⟩ := Ideal.mem_span_singleton'.mp hq
      obtain ⟨r, hr⟩ := hres t
      obtain ⟨t', ht'⟩ := Ideal.mem_span_singleton'.mp hr
      refine ⟨q + C r * X ^ n, Ideal.mem_span_singleton'.mpr ⟨t', ?_⟩⟩
      simp only [map_add, map_mul, map_pow, aeval_C, aeval_X]
      have hts : t = t' * ϖ + algebraMap R S r := by rw [ht']; ring
      have hs : s = t * ϖ ^ n + aeval ϖ q := by rw [ht]; ring
      rw [hs, hts]
      ring
  rw [← Algebra.toSubmodule_eq_top]
  refine le_antisymm le_top (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) ?_)
  intro s _
  obtain ⟨q, hq⟩ := key e s
  rw [Ideal.smul_top_eq_map]
  refine Submodule.mem_sup.mpr ⟨aeval ϖ q, ?_, s - aeval ϖ q, ?_, by ring⟩
  · rw [Subalgebra.mem_toSubmodule, Algebra.adjoin_singleton_eq_range_aeval]
    exact ⟨q, rfl⟩
  · rw [Submodule.restrictScalars_mem]
    exact Ideal.span_le.mpr (Set.singleton_subset_iff.mpr he) hq

end LocalField
