/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.RingTheory.LocalRing.Module

/-!
# A Nakayama-style criterion for monogenicity over a local ring

Serre's tower-composition argument for `𝒪_L = 𝒪_K[a]` (*Local Fields* III §6) does not, on
reflection, need a discriminant/index computation at all: it is a direct corollary of Nakayama's
lemma, already available in Mathlib as `IsLocalRing.map_mkQ_eq_top`
(`Mathlib.RingTheory.LocalRing.Module`). For `R` local with maximal ideal `𝔪` and `S` a finite
`R`-algebra, a submodule `N ≤ S` equals `⊤` iff its image in `S ⧸ 𝔪 • ⊤` (the reduction mod `𝔪`) is
`⊤`. Applied to `N := Subalgebra.toSubmodule (Algebra.adjoin R {a})`, this reduces
`Algebra.adjoin R {a} = ⊤` to a statement purely about the residue algebra `S ⧸ 𝔪S`: do the images
of the powers of `a` span it?

This supersedes the `differentIdeal`/discriminant-tower route flagged as the "best candidate" by
`ROADMAP.md`'s twenty-third/twenty-fourth passes: that route needed translating this repo's
`Algebra.discr`/`spectralNorm` formalism into the ideal-valued `differentIdeal`/`FractionalIdeal`
formalism (untranslated, and separately needed a classical resultant-of-a-sum identity for
`disc_K(β + c•π)` that is not in Mathlib and would need to be built from scratch,
`Mathlib.RingTheory.Polynomial.Resultant.Basic` having no connection to `Algebra.discr` at all,
confirmed by grep this pass). The Nakayama route needs no discriminant, no resultant, and no
Eisenstein-ness of `minpoly K a` (which genuinely fails for the composite generator in the mixed
ramification case, confirmed this pass: `mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt`
requires `(minpoly R B.gen).IsEisensteinAt`, and Eisenstein-ness needs the *whole* extension totally
ramified). It also gives the field-level primitive-element fact
(`Langlands.PrimitiveElementFusion.exists_scalar_add_smul_primitive`) as a free corollary rather
than a separate input: if the powers of `a` already span the free rank-`ef` `R`-module `S`, `a`
cannot satisfy a shorter algebraic relation over `K`, so `(minpoly K a).natDegree = ef` follows
automatically once `Algebra.adjoin R {a} = ⊤` is known, with no separate pigeonhole argument needed.

## Main result

* `LocalField.adjoin_eq_top_of_map_mkQ_eq_top` : for `R` local, `S` a finite `R`-algebra, `a : S`,
  if the image of `Algebra.adjoin R {a}` in `S ⧸ (maximalIdeal R • ⊤)` is all of that quotient,
  then `Algebra.adjoin R {a} = ⊤`.

## What remains (not attempted in this file)

The hypothesis this lemma needs — that the images of the powers of `a := β + c • π` span
`S ⧸ 𝔪_K S` for `S := 𝒪_N` — is itself a nontrivial fact requiring:

1. Identifying `𝒪_N ⧸ 𝔪_K 𝒪_N` concretely. Using `𝒪_M = 𝒪_K[β]` (unramified: `𝔪_K 𝒪_M = 𝔪_M`) and
   `𝒪_N = 𝒪_M[π]` (Eisenstein of degree `e`), the classical computation is
   `𝒪_N ⧸ 𝔪_K 𝒪_N ≅ κ_M[T] ⧸ (T ^ e)` where `κ_M := 𝒪_M ⧸ 𝔪_M` is generated over `κ_K` by the image
   of `β`. This ring isomorphism is not yet built in this repo.
2. An "Artinian primitive element" fact: in `κ_M[T] ⧸ (T ^ e)` (`κ_M / κ_K` a degree-`f` field
   extension generated by `β̄`), do the powers of `β̄ + c̄ • T` span the whole `κ_K`-algebra (of
   `κ_K`-dimension `ef`) for a suitable `c̄`? This is a linear-algebra fact about a nilpotent
   extension of a field extension, genuinely different in character from Mathlib's
   field-only primitive element theorem (`Mathlib.FieldTheory.PrimitiveElement`, which does not
   apply to the non-reduced ring `κ_M[T] ⧸ (T ^ e)`) and not found in Mathlib by this pass's search
   (`grep -rn "primitive" Mathlib/RingTheory/` turns up only field-theoretic and
   `PrimitiveRoots`/`IsPrimitiveRoot` hits, nothing about generation of Artinian local algebras).
   Notably, `Mathlib.RingTheory.LocalRing.Etale`'s own `exists_adjoin_eq_top` (the theorem this
   repo's unramified half already uses, per `ROADMAP.md`'s thirteenth pass) proves monogenicity of
   an *étale* (residue extension separable, ramification index `1`) local extension by exactly
   this Nakayama pattern — "lifts a primitive element of the residue field extension via Nakayama's
   lemma" (its own docstring, `LocalRing/Etale.lean:92`) — confirming the pattern is the right one
   in the unramified case, where the residue quotient genuinely is a field and
   `Field.exists_primitive_element` applies directly. The totally-ramified/mixed case here differs
   exactly because `S ⧸ 𝔪_K S` is a non-reduced Artinian ring (`T` nilpotent), not a field, so that
   theorem's proof does not transfer verbatim; a new argument for the Artinian case is needed.

Neither (1) nor (2) was attempted in code this pass; both are precisely scoped, genuinely new
mathematical content, not lemma lookups.
-/

namespace LocalField

/-- **Nakayama-style monogenicity criterion.** For `R` local (maximal ideal `𝔪`) and `S` a finite
`R`-algebra, if the image of `Algebra.adjoin R {a}` (viewed as a submodule of `S`) under reduction
mod `𝔪 • ⊤` is everything, then `Algebra.adjoin R {a} = ⊤` outright — i.e. `a` generates `S` as an
`R`-algebra.

This is `IsLocalRing.map_mkQ_eq_top` (`Mathlib.RingTheory.LocalRing.Module`), specialized to the
submodule underlying a singly-generated subalgebra. -/
theorem adjoin_eq_top_of_map_mkQ_eq_top {R S : Type*} [CommRing R] [IsLocalRing R] [CommRing S]
    [Algebra R S] [Module.Finite R S] {a : S}
    (h : (Subalgebra.toSubmodule (Algebra.adjoin R ({a} : Set S))).map
        (Submodule.mkQ (IsLocalRing.maximalIdeal R • (⊤ : Submodule R S))) = ⊤) :
    Algebra.adjoin R ({a} : Set S) = ⊤ := by
  rw [← Algebra.toSubmodule_eq_top]
  exact IsLocalRing.map_mkQ_eq_top.mp h

end LocalField
