import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois
import Langlands.TotallyRamifiedValuationExtension
import Langlands.AdicCompletionIntegersResidue
import Langlands.AdicCompletionIntegralClosure
import Langlands.HeightOneSpectrumRationalPrimeTower

/-!
# A concrete MIXED-CHARACTERISTIC, WILD, GALOIS ramified extension: `ℚ(ζ_{p²}) / ℚ(ζ_p)`

Targets the task's headline gap: every existing `IsTotallyRamified` instance in this repo
(`TotallyRamifiedConcreteExample`, `TotallyRamifiedWildConcreteExample`,
`TotallyRamifiedArtinSchreierConcreteExample`) is equal-characteristic (built over `k[X]` for a
finite field `k`), so none of them can exercise the `CharZero`-only machinery of
`AdicCompletionNormExpTrace`/`NonarchimedeanExponentialUnitsIso`. This file builds a genuinely
mixed-characteristic (`CharZero K`, residue characteristic `p`), wild (`p ∣ e`), Galois instance
using cyclotomic number fields: `K := ℚ(ζ_p)`, `L := ℚ(ζ_{p²}) = K(ζ_p^{1/p})`.

## Step 0 (premise check): which `p`, and the exact ramification numbers

Recent Mathlib (`Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal`) has *exactly* the ideal-level
facts needed, for every prime `p` uniformly (no small-`p` special-casing needed on the Mathlib side):

* `IsCyclotomicExtension.Rat.ncard_primesOver_of_prime`/`_of_prime_pow`: the rational prime `p` has
  a **unique** prime ideal above it in `ℚ(ζ_p)` (resp. `ℚ(ζ_{p^(k+1)})`) — so `v` and `w` below are
  not just *a* choice of place, they are *the* unique places above `p`, and the extension `L / K` is
  automatically totally ramified at the unique prime of `L` over `v` (no splitting to rule out).
* `IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime`/`eq_span_zeta_sub_one_of_liesOver'`: the
  ramification index of `p` in `ℚ(ζ_p)` is exactly `p - 1`, realized by the *explicit* prime ideal
  `span {ζ_p - 1}` (no going-up theorem needed to exhibit `v`).
* `IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime_pow`/`eq_span_zeta_sub_one_of_liesOver`
  (with `k = 1`, i.e. `n = p ^ (1 + 1) = p²`): the ramification index of `p` in `ℚ(ζ_{p²})` is
  exactly `p ^ 1 * (p - 1) = p * (p - 1)`, realized by the explicit prime ideal `span {ζ_{p²} - 1}`.

Since `K = ℚ(ζ_p) ⊆ L = ℚ(ζ_{p²})` is a tower over `ℚ` with `w` (the unique prime of `L` over `p`)
lying over `v` (the unique prime of `K` over `p`, forced by uniqueness — see
`w_asIdeal_comap_eq_v_asIdeal` below), the ramification indices multiply in the tower:
`e(w / p) = e(v / p) * e(w / v)`, i.e. `p * (p - 1) = (p - 1) * e(w / v)`, giving
**`e(w / v) = p` exactly** — genuinely wild, since `p ∣ e`. Likewise
`f(w / p) = f(v / p) * f(w / v)` with `f(v/p) = f(w/p) = 1` (both `ramificationIdxIn`-style
theorems above pin the inertia degree at `1` for every prime power `p^k`), giving `f(w / v) = 1`.
This holds **for every prime `p`** — the formula is uniform, so there is no "hard" or "easy" choice
of `p` on the number-theoretic side. `p = 2` is degenerate as a *choice for this file*, though: it
makes `K = ℚ(ζ_2) = ℚ`, i.e. `v` would be the ordinary rational prime `(2)` in `ℤ` and the "base
field" of the whole construction collapses to `ℚ` itself, which is a valid but uninteresting corner
case of the general construction. `p = 3` is the smallest prime giving a genuinely nontrivial `K`
(a quadratic field, `ℚ(ζ_3) = ℚ(√-3)`), so it is used here; nothing in the proof is specific to `3`
beyond that choice, and `Mathlib.NumberTheory.NumberField.Cyclotomic.PID`'s `three_pid` (though
unused below, since `IsDedekindDomain (𝓞 K)` is already automatic for any number field) confirms
`p = 3` is also one of the best-supported small cases elsewhere in Mathlib.

## Design: `K` and `L` as concrete cyclotomic fields, following the tower argument in
`IsCyclotomicExtension.Rat.inertiaDegIn_ramificationIdxIn_aux`

`L := CyclotomicField (p ^ (1 + 1)) ℚ` (syntactically `p ^ (1 + 1)`, not `p ^ 2`, so that Mathlib's
`k = 1` prime-power lemmas apply without any rewriting). `K := ℚ⟮ζ_p⟯`, the `IntermediateField ℚ L`
generated by `ζ_p := ζ_{p²} ^ p`, exactly the construction Mathlib's own `Galois.lean` uses
internally (`Fₚ := ℚ⟮ζₚ⟯` in `inertiaDegIn_ramificationIdxIn_aux`) to realize `ℚ(ζ_p)` inside
`ℚ(ζ_{p²})` with `Algebra K L` for free (an `IntermediateField` is automatically an algebra over the
ambient field).

## Status

See the closing section of this file and `ROADMAP.md` for the precise account of what closed.
-/

noncomputable section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum IsLocalRing Polynomial NumberField Ideal
  IntermediateField
open scoped Cyclotomic

namespace Langlands.TotallyRamifiedCyclotomicConcreteExample

/-! ### `p`, `L := ℚ(ζ_{p²})`, `K := ℚ(ζ_p) ⊆ L` -/

/-- The residue characteristic, and (as shown below) the ramification index of `L / K` at the
place constructed here: `p = 3`, the smallest prime for which `K := ℚ(ζ_p)` is not just `ℚ`
itself (see the module docstring's Step 0 discussion). -/
abbrev p : ℕ := 3

instance : Fact (Nat.Prime p) := ⟨by decide⟩

/-- `L := ℚ(ζ_{p²})`, realized concretely as the `p ^ (1 + 1)`-th cyclotomic field (kept in the
form `p ^ (1 + 1)`, matching Mathlib's `k = 1` prime-power lemmas syntactically). -/
abbrev L : Type := CyclotomicField (p ^ (1 + 1)) ℚ

/-- Registered explicitly (rather than left to automatic instance search) because Lean's
typeclass search does not resolve the generic `[CharZero K] : IsCyclotomicExtension {n} K
(CyclotomicField n K)` instance via `inferInstance` for a concrete `n` here (confirmed by direct
experiment: the term typechecks when applied explicitly, but plain `inferInstance` fails) — the
`[NeZero (n : K)]`-indexed variant `CyclotomicField.isCyclotomicExtension`, applied explicitly,
works reliably instead. -/
instance : IsCyclotomicExtension {p ^ (1 + 1)} ℚ L :=
  CyclotomicField.isCyclotomicExtension (p ^ (1 + 1)) ℚ

instance : NumberField L := IsCyclotomicExtension.numberField {p ^ (1 + 1)} ℚ L

/-- `ζ`, a primitive `p²`-th root of unity generating `L` over `ℚ`. -/
noncomputable def ζ : L := IsCyclotomicExtension.zeta (p ^ (1 + 1)) ℚ L

theorem hζ : IsPrimitiveRoot ζ (p ^ (1 + 1)) := IsCyclotomicExtension.zeta_spec (p ^ (1 + 1)) ℚ L

/-- `ζₚ := ζ ^ p`, a primitive `p`-th root of unity inside `L`. -/
noncomputable def ζₚ : L := ζ ^ p

theorem hζₚ : IsPrimitiveRoot ζₚ p := hζ.pow (by positivity) (pow_succ p 1 ▸ (by ring))

/-- `K := ℚ(ζ_p)`, the `IntermediateField ℚ L` generated by `ζₚ`. -/
abbrev K : Type := ℚ⟮ζₚ⟯

instance : IsCyclotomicExtension {p} ℚ K :=
  hζₚ.intermediateField_adjoin_isCyclotomicExtension ℚ

instance : NumberField K := IsCyclotomicExtension.numberField {p} ℚ K

/-! ### `IsGalois K L`

Free from `IsGalois ℚ L` (`IsCyclotomicExtension.isGalois`, unconditional for any cyclotomic
extension of `ℚ`) plus the generic fact that any intermediate field of a Galois extension is
itself Galois over that intermediate field (`IsGalois.tower_top_intermediateField`, already an
instance in Mathlib — no extra work needed here, unlike the Artin–Schreier file's from-scratch
`IsGalois` construction at the *completed* level in `AdicCompletionIntegersResidue`-adjacent
files). -/

instance : IsGalois ℚ L := IsCyclotomicExtension.isGalois {p ^ (1 + 1)} ℚ L

instance : IsGalois K L := inferInstance

/-! ### `v : HeightOneSpectrum (𝓞 K)` and `w : HeightOneSpectrum (𝓞 L)`, both explicit

Unlike the Artin–Schreier file (which had to invoke a going-up theorem since its `S` was not a
hand-built ring), the places `v` and `w` here are **explicit** ideals, courtesy of
`IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver'`/`_of_liesOver`: the *unique* prime
of `𝓞 K` (resp. `𝓞 L`) above the rational prime `p` is `span {ζₚ - 1}` (resp. `span {ζ - 1}`). -/

/-- `ζ_K`, a primitive `p`-th root of unity **native to `K` itself** (as opposed to `ζₚ : L`,
which merely generates `K`) — used for `v` below so that all the "Prime"-section lemmas of
`IsCyclotomicExtension.Rat` apply directly with ambient field `K`, matching their stated
signatures without any `algebraMap`/injectivity bookkeeping. Which primitive root is chosen does
not matter for `v` itself: `eq_span_zeta_sub_one_of_liesOver'` shows every primitive `p`-th root of
unity in `K` gives the same ideal `span {ζ_K - 1}`, the unique prime of `𝓞 K` above `p`. -/
noncomputable def ζ_K : K := IsCyclotomicExtension.zeta p ℚ K

theorem hζ_K : IsPrimitiveRoot ζ_K p := IsCyclotomicExtension.zeta_spec p ℚ K

/-- `v`, the unique place of `𝓞 K` above the rational prime `p`. -/
def v : HeightOneSpectrum (𝓞 K) where
  asIdeal := Ideal.span {hζ_K.toInteger - 1}
  isPrime := IsCyclotomicExtension.Rat.isPrime_span_zeta_sub_one' p hζ_K
  ne_bot := by
    simpa [Ideal.span_singleton_eq_bot] using (hζ_K.zeta_sub_one_prime' (p := p)).ne_zero

/-- `w`, the unique place of `𝓞 L` above the rational prime `p`. -/
def w : HeightOneSpectrum (𝓞 L) where
  asIdeal := Ideal.span {hζ.toInteger - 1}
  isPrime := IsCyclotomicExtension.Rat.isPrime_span_zeta_sub_one p 1 hζ
  ne_bot := by
    simpa [Ideal.span_singleton_eq_bot] using (hζ.zeta_sub_one_prime (p := p) (k := 1)).ne_zero

/-- `hζ_K`, recast as a primitive `p ^ (0 + 1)`-th root, to match Mathlib's prime-power (`k = 0`)
lemmas syntactically (mirroring how `IsCyclotomicExtension.Rat`'s own "Prime"-section lemmas are
proved by reducing to the `k = 0` case of the "PrimePow" section, e.g. `isPrime_span_zeta_sub_one'`
itself). -/
theorem hζ_K' : IsPrimitiveRoot ζ_K (p ^ (0 + 1)) := by simpa using hζ_K

instance isCyclotomicExtension_K_pow_zero_add_one :
    IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by simpa using
  (inferInstance : IsCyclotomicExtension {p} ℚ K)

instance : v.asIdeal.LiesOver (Ideal.span {(p : ℤ)}) :=
  IsCyclotomicExtension.Rat.liesOver_span_zeta_sub_one p 0 hζ_K'

instance : w.asIdeal.LiesOver (Ideal.span {(p : ℤ)}) :=
  IsCyclotomicExtension.Rat.liesOver_span_zeta_sub_one p 1 hζ

/-! ### `w.asIdeal.LiesOver v.asIdeal`

Since `𝓞 K` has a *unique* prime over the rational prime `p` (`v`, by
`IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver'`), and `w.asIdeal`'s comap to `𝓞 K`
is itself a prime lying over `p` (by transitivity of `Ideal.under`, since `w.asIdeal` already lies
over `p`), that comap must equal `v.asIdeal` exactly — no going-up theorem needed, unlike the
Artin–Schreier file (where `S` was not a hand-built ring and `w` could not be pinned down this
concretely to begin with). -/

instance isPrime_comap_w : (w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L))).IsPrime :=
  Ideal.IsPrime.comap _

instance liesOver_comap_w : (w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L))).LiesOver
    (Ideal.span {(p : ℤ)}) where
  over := by
    rw [Ideal.over_def w.asIdeal (Ideal.span {(p : ℤ)}), ← Ideal.under_under (A := ℤ) (B := 𝓞 K)]

theorem comap_w_eq_v :
    w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L)) = v.asIdeal :=
  IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver' p K hζ_K _

instance : w.asIdeal.LiesOver v.asIdeal where
  over := comap_w_eq_v.symm

/-! ### `e := v.asIdeal.ramificationIdx' w.asIdeal = p` and `f := v.asIdeal.inertiaDeg' w.asIdeal
= 1`, via the general bridge lemma (`Langlands.HeightOneSpectrumRationalPrimeTower`) and
Mathlib's concrete cyclotomic formulas

`Ideal.ramificationIdx v.asIdeal ℤ = p - 1` (`ramificationIdx_eq_of_prime`, since `K = ℚ(ζ_p)`) and
`Ideal.ramificationIdx w.asIdeal ℤ = p ^ 1 * (p - 1)` (`ramificationIdx_eq_of_prime_pow` with
`k = 1`, since `L = ℚ(ζ_{p²})`); the bridge lemma's tower identity
`Ideal.ramificationIdx w.asIdeal ℤ = Ideal.ramificationIdx v.asIdeal ℤ * v.asIdeal.ramificationIdx'
w.asIdeal` then forces `e = p` exactly (cancelling the common nonzero factor `p - 1`) — the
genuinely wild ramification the task is after. The inertia-degree computation is identical in
shape, with both absolute inertia degrees equal to `1`, forcing `f = 1`. -/

theorem ramificationIdx_v : Ideal.ramificationIdx v.asIdeal ℤ = p - 1 :=
  IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime p K v.asIdeal

theorem ramificationIdx_w : Ideal.ramificationIdx w.asIdeal ℤ = p ^ 1 * (p - 1) :=
  IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime_pow p 1 L w.asIdeal

/-- **`e := v.asIdeal.ramificationIdx' w.asIdeal = p` exactly.** -/
theorem ramificationIdx'_eq : v.asIdeal.ramificationIdx' w.asIdeal = p := by
  have hb := ramificationIdx_int_eq_mul_ramificationIdx' v w (p := p)
  rw [ramificationIdx_w, ramificationIdx_v, pow_one, mul_comm p (p - 1)] at hb
  have hp1 : 0 < p - 1 := by have := (Fact.out : p.Prime).two_le; omega
  exact (Nat.eq_of_mul_eq_mul_left hp1 hb).symm

theorem inertiaDeg_v : Ideal.inertiaDeg v.asIdeal ℤ = 1 :=
  IsCyclotomicExtension.Rat.inertiaDeg_eq_of_prime p K v.asIdeal

theorem inertiaDeg_w : Ideal.inertiaDeg w.asIdeal ℤ = 1 :=
  IsCyclotomicExtension.Rat.inertiaDeg_eq_of_prime_pow p 1 L w.asIdeal

/-- **`f := v.asIdeal.inertiaDeg' w.asIdeal = 1` exactly.** -/
theorem inertiaDeg'_eq : v.asIdeal.inertiaDeg' w.asIdeal = 1 := by
  have hb := inertiaDeg_int_eq_mul_inertiaDeg' v w (p := p)
  rw [inertiaDeg_w, inertiaDeg_v] at hb
  omega

end Langlands.TotallyRamifiedCyclotomicConcreteExample

end
