import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois
import Langlands.TotallyRamifiedValuationExtension
import Langlands.AdicCompletionIntegersResidue
import Langlands.AdicCompletionIntegralClosure
import Langlands.HeightOneSpectrumRationalPrimeTower
import Langlands.AdicCompletionPrimitiveElementDegree
import Langlands.NormMapResidueCompatibility

/-!
# A concrete MIXED-CHARACTERISTIC, WILD, GALOIS ramified extension: `ℚ(ζ_{p²}) / ℚ(ζ_p)`

Targets the task's headline gap: every existing `IsTotallyRamified` instance in this repo
(`TotallyRamifiedConcreteExample`, `TotallyRamifiedWildConcreteExample`,
`TotallyRamifiedArtinSchreierConcreteExample`) is equal-characteristic (built over `k[X]` for a
finite field `k`), so none of them can exercise the `CharZero`-only machinery of
`AdicCompletionNormExpTrace`/`NonarchimedeanExponentialUnitsIso`. This file builds a genuinely
mixed-characteristic (`CharZero K`, residue characteristic `p`), wild (`p ∣ e`), Galois instance
using cyclotomic number fields: `K := ℚ(ζ_p)`, `L := ℚ(ζ_{p²}) = K(ζ_p^{1/p})`.

## Step 0 (premise check): which `p`, and the exact ramification numbers

Recent Mathlib (`Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal`) has *exactly* the ideal-level
facts needed, for every prime `p` uniformly (no small-`p` special-casing needed on the Mathlib side):

* `IsCyclotomicExtension.Rat.ncard_primesOver_of_prime`/`_of_prime_pow`: the rational prime `p` has
  a **unique** prime ideal above it in `ℚ(ζ_p)` (resp. `ℚ(ζ_{p^(k+1)})`) — so `v` and `w` below are
  not just *a* choice of place, they are *the* unique places above `p`, and the extension `L / K` is
  automatically totally ramified at the unique prime of `L` over `v` (no splitting to rule out).
* `IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime`/`eq_span_zeta_sub_one_of_liesOver'`: the
  ramification index of `p` in `ℚ(ζ_p)` is exactly `p - 1`, realized by the *explicit* prime ideal
  `span {ζ_p - 1}` (no going-up theorem needed to exhibit `v`).
* `IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime_pow`/`eq_span_zeta_sub_one_of_liesOver`
  (with `k = 1`, i.e. `n = p ^ (1 + 1) = p²`): the ramification index of `p` in `ℚ(ζ_{p²})` is
  exactly `p ^ 1 * (p - 1) = p * (p - 1)`, realized by the explicit prime ideal `span {ζ_{p²} - 1}`.

Since `K = ℚ(ζ_p) ⊆ L = ℚ(ζ_{p²})` is a tower over `ℚ` with `w` (the unique prime of `L` over `p`)
lying over `v` (the unique prime of `K` over `p`, forced by uniqueness — see
`w_asIdeal_comap_eq_v_asIdeal` below), the ramification indices multiply in the tower:
`e(w / p) = e(v / p) * e(w / v)`, i.e. `p * (p - 1) = (p - 1) * e(w / v)`, giving
**`e(w / v) = p` exactly** — genuinely wild, since `p ∣ e`. Likewise
`f(w / p) = f(v / p) * f(w / v)` with `f(v/p) = f(w/p) = 1` (both `ramificationIdxIn`-style
theorems above pin the inertia degree at `1` for every prime power `p^k`), giving `f(w / v) = 1`.
This holds **for every prime `p`** — the formula is uniform, so there is no "hard" or "easy" choice
of `p` on the number-theoretic side. `p = 2` is degenerate as a *choice for this file*, though: it
makes `K = ℚ(ζ_2) = ℚ`, i.e. `v` would be the ordinary rational prime `(2)` in `ℤ` and the "base
field" of the whole construction collapses to `ℚ` itself, which is a valid but uninteresting corner
case of the general construction. `p = 3` is the smallest prime giving a genuinely nontrivial `K`
(a quadratic field, `ℚ(ζ_3) = ℚ(√-3)`), so it is used here; nothing in the proof is specific to `3`
beyond that choice, and `Mathlib.NumberTheory.NumberField.Cyclotomic.PID`'s `three_pid` (though
unused below, since `IsDedekindDomain (𝓞 K)` is already automatic for any number field) confirms
`p = 3` is also one of the best-supported small cases elsewhere in Mathlib.

## Design: `K` and `L` as concrete cyclotomic fields, following the tower argument in
`IsCyclotomicExtension.Rat.inertiaDegIn_ramificationIdxIn_aux`

`L := CyclotomicField (p ^ (1 + 1)) ℚ` (syntactically `p ^ (1 + 1)`, not `p ^ 2`, so that Mathlib's
`k = 1` prime-power lemmas apply without any rewriting). `K := ℚ⟮ζ_p⟯`, the `IntermediateField ℚ L`
generated by `ζ_p := ζ_{p²} ^ p`, exactly the construction Mathlib's own `Galois.lean` uses
internally (`Fₚ := ℚ⟮ζₚ⟯` in `inertiaDegIn_ramificationIdxIn_aux`) to realize `ℚ(ζ_p)` inside
`ℚ(ζ_{p²})` with `Algebra K L` for free (an `IntermediateField` is automatically an algebra over the
ambient field).

## Status

See the closing section of this file and `ROADMAP.md` for the precise account of what closed.
-/

noncomputable section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum IsLocalRing Polynomial NumberField Ideal
  IntermediateField
open scoped Cyclotomic

namespace Langlands.TotallyRamifiedCyclotomicConcreteExample

/-! ### `p`, `L := ℚ(ζ_{p²})`, `K := ℚ(ζ_p) ⊆ L` -/

/-- The residue characteristic, and (as shown below) the ramification index of `L / K` at the
place constructed here: `p = 3`, the smallest prime for which `K := ℚ(ζ_p)` is not just `ℚ`
itself (see the module docstring's Step 0 discussion). -/
abbrev p : ℕ := 3

instance : Fact (Nat.Prime p) := ⟨by decide⟩

/-- `L := ℚ(ζ_{p²})`, realized concretely as the `p ^ (1 + 1)`-th cyclotomic field (kept in the
form `p ^ (1 + 1)`, matching Mathlib's `k = 1` prime-power lemmas syntactically). -/
abbrev L : Type := CyclotomicField (p ^ (1 + 1)) ℚ

/-- Registered explicitly (rather than left to automatic instance search) because Lean's
typeclass search does not resolve the generic `[CharZero K] : IsCyclotomicExtension {n} K
(CyclotomicField n K)` instance via `inferInstance` for a concrete `n` here (confirmed by direct
experiment: the term typechecks when applied explicitly, but plain `inferInstance` fails) — the
`[NeZero (n : K)]`-indexed variant `CyclotomicField.isCyclotomicExtension`, applied explicitly,
works reliably instead. -/
instance : IsCyclotomicExtension {p ^ (1 + 1)} ℚ L :=
  CyclotomicField.isCyclotomicExtension (p ^ (1 + 1)) ℚ

instance : NumberField L := IsCyclotomicExtension.numberField {p ^ (1 + 1)} ℚ L

/-- `ζ`, a primitive `p²`-th root of unity generating `L` over `ℚ`. -/
noncomputable def ζ : L := IsCyclotomicExtension.zeta (p ^ (1 + 1)) ℚ L

theorem hζ : IsPrimitiveRoot ζ (p ^ (1 + 1)) := IsCyclotomicExtension.zeta_spec (p ^ (1 + 1)) ℚ L

/-- `ζₚ := ζ ^ p`, a primitive `p`-th root of unity inside `L`. -/
noncomputable def ζₚ : L := ζ ^ p

theorem hζₚ : IsPrimitiveRoot ζₚ p := hζ.pow (by positivity) (pow_succ p 1 ▸ (by ring))

/-- `K := ℚ(ζ_p)`, the `IntermediateField ℚ L` generated by `ζₚ`. -/
abbrev K : Type := ℚ⟮ζₚ⟯

instance : IsCyclotomicExtension {p} ℚ K :=
  hζₚ.intermediateField_adjoin_isCyclotomicExtension ℚ

instance : NumberField K := IsCyclotomicExtension.numberField {p} ℚ K

/-! ### `IsGalois K L`

Free from `IsGalois ℚ L` (`IsCyclotomicExtension.isGalois`, unconditional for any cyclotomic
extension of `ℚ`) plus the generic fact that any intermediate field of a Galois extension is
itself Galois over that intermediate field (`IsGalois.tower_top_intermediateField`, already an
instance in Mathlib — no extra work needed here, unlike the Artin–Schreier file's from-scratch
`IsGalois` construction at the *completed* level in `AdicCompletionIntegersResidue`-adjacent
files). -/

instance : IsGalois ℚ L := IsCyclotomicExtension.isGalois {p ^ (1 + 1)} ℚ L

instance : IsGalois K L := inferInstance

/-! ### `v : HeightOneSpectrum (𝓞 K)` and `w : HeightOneSpectrum (𝓞 L)`, both explicit

Unlike the Artin–Schreier file (which had to invoke a going-up theorem since its `S` was not a
hand-built ring), the places `v` and `w` here are **explicit** ideals, courtesy of
`IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver'`/`_of_liesOver`: the *unique* prime
of `𝓞 K` (resp. `𝓞 L`) above the rational prime `p` is `span {ζₚ - 1}` (resp. `span {ζ - 1}`). -/

/-- `ζ_K`, a primitive `p`-th root of unity **native to `K` itself** (as opposed to `ζₚ : L`,
which merely generates `K`) — used for `v` below so that all the "Prime"-section lemmas of
`IsCyclotomicExtension.Rat` apply directly with ambient field `K`, matching their stated
signatures without any `algebraMap`/injectivity bookkeeping. Which primitive root is chosen does
not matter for `v` itself: `eq_span_zeta_sub_one_of_liesOver'` shows every primitive `p`-th root of
unity in `K` gives the same ideal `span {ζ_K - 1}`, the unique prime of `𝓞 K` above `p`. -/
noncomputable def ζ_K : K := IsCyclotomicExtension.zeta p ℚ K

theorem hζ_K : IsPrimitiveRoot ζ_K p := IsCyclotomicExtension.zeta_spec p ℚ K

/-- `v`, the unique place of `𝓞 K` above the rational prime `p`. -/
def v : HeightOneSpectrum (𝓞 K) where
  asIdeal := Ideal.span {hζ_K.toInteger - 1}
  isPrime := IsCyclotomicExtension.Rat.isPrime_span_zeta_sub_one' p hζ_K
  ne_bot := by
    simpa [Ideal.span_singleton_eq_bot] using (hζ_K.zeta_sub_one_prime' (p := p)).ne_zero

/-- `w`, the unique place of `𝓞 L` above the rational prime `p`. -/
def w : HeightOneSpectrum (𝓞 L) where
  asIdeal := Ideal.span {hζ.toInteger - 1}
  isPrime := IsCyclotomicExtension.Rat.isPrime_span_zeta_sub_one p 1 hζ
  ne_bot := by
    simpa [Ideal.span_singleton_eq_bot] using (hζ.zeta_sub_one_prime (p := p) (k := 1)).ne_zero

/-- `hζ_K`, recast as a primitive `p ^ (0 + 1)`-th root, to match Mathlib's prime-power (`k = 0`)
lemmas syntactically (mirroring how `IsCyclotomicExtension.Rat`'s own "Prime"-section lemmas are
proved by reducing to the `k = 0` case of the "PrimePow" section, e.g. `isPrime_span_zeta_sub_one'`
itself). -/
theorem hζ_K' : IsPrimitiveRoot ζ_K (p ^ (0 + 1)) := by simpa using hζ_K

instance isCyclotomicExtension_K_pow_zero_add_one :
    IsCyclotomicExtension {p ^ (0 + 1)} ℚ K := by simpa using
  (inferInstance : IsCyclotomicExtension {p} ℚ K)

instance : v.asIdeal.LiesOver (Ideal.span {(p : ℤ)}) :=
  IsCyclotomicExtension.Rat.liesOver_span_zeta_sub_one p 0 hζ_K'

instance : w.asIdeal.LiesOver (Ideal.span {(p : ℤ)}) :=
  IsCyclotomicExtension.Rat.liesOver_span_zeta_sub_one p 1 hζ

/-! ### `w.asIdeal.LiesOver v.asIdeal`

Since `𝓞 K` has a *unique* prime over the rational prime `p` (`v`, by
`IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver'`), and `w.asIdeal`'s comap to `𝓞 K`
is itself a prime lying over `p` (by transitivity of `Ideal.under`, since `w.asIdeal` already lies
over `p`), that comap must equal `v.asIdeal` exactly — no going-up theorem needed, unlike the
Artin–Schreier file (where `S` was not a hand-built ring and `w` could not be pinned down this
concretely to begin with). -/

instance isPrime_comap_w : (w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L))).IsPrime :=
  Ideal.IsPrime.comap _

instance liesOver_comap_w : (w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L))).LiesOver
    (Ideal.span {(p : ℤ)}) where
  over := by
    rw [Ideal.over_def w.asIdeal (Ideal.span {(p : ℤ)}), ← Ideal.under_under (A := ℤ) (B := 𝓞 K)]

theorem comap_w_eq_v :
    w.asIdeal.comap (algebraMap (𝓞 K) (𝓞 L)) = v.asIdeal :=
  IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver' p K hζ_K _

instance : w.asIdeal.LiesOver v.asIdeal where
  over := comap_w_eq_v.symm

/-! ### `e := v.asIdeal.ramificationIdx' w.asIdeal = p` and `f := v.asIdeal.inertiaDeg' w.asIdeal
= 1`, via the general bridge lemma (`Langlands.HeightOneSpectrumRationalPrimeTower`) and
Mathlib's concrete cyclotomic formulas

`Ideal.ramificationIdx v.asIdeal ℤ = p - 1` (`ramificationIdx_eq_of_prime`, since `K = ℚ(ζ_p)`) and
`Ideal.ramificationIdx w.asIdeal ℤ = p ^ 1 * (p - 1)` (`ramificationIdx_eq_of_prime_pow` with
`k = 1`, since `L = ℚ(ζ_{p²})`); the bridge lemma's tower identity
`Ideal.ramificationIdx w.asIdeal ℤ = Ideal.ramificationIdx v.asIdeal ℤ * v.asIdeal.ramificationIdx'
w.asIdeal` then forces `e = p` exactly (cancelling the common nonzero factor `p - 1`) — the
genuinely wild ramification the task is after. The inertia-degree computation is identical in
shape, with both absolute inertia degrees equal to `1`, forcing `f = 1`. -/

theorem ramificationIdx_v : Ideal.ramificationIdx v.asIdeal ℤ = p - 1 :=
  IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime p K v.asIdeal

theorem ramificationIdx_w : Ideal.ramificationIdx w.asIdeal ℤ = p ^ 1 * (p - 1) :=
  IsCyclotomicExtension.Rat.ramificationIdx_eq_of_prime_pow p 1 L w.asIdeal

/-- **`e := v.asIdeal.ramificationIdx' w.asIdeal = p` exactly.** -/
theorem ramificationIdx'_eq : v.asIdeal.ramificationIdx' w.asIdeal = p := by
  have hb := ramificationIdx_int_eq_mul_ramificationIdx' v w (p := p)
  rw [ramificationIdx_w, ramificationIdx_v, pow_one, mul_comm p (p - 1)] at hb
  have hp1 : 0 < p - 1 := by have := (Fact.out : p.Prime).two_le; omega
  exact (Nat.eq_of_mul_eq_mul_left hp1 hb).symm

theorem inertiaDeg_v : Ideal.inertiaDeg v.asIdeal ℤ = 1 :=
  IsCyclotomicExtension.Rat.inertiaDeg_eq_of_prime p K v.asIdeal

theorem inertiaDeg_w : Ideal.inertiaDeg w.asIdeal ℤ = 1 :=
  IsCyclotomicExtension.Rat.inertiaDeg_eq_of_prime_pow p 1 L w.asIdeal

/-- **`f := v.asIdeal.inertiaDeg' w.asIdeal = 1` exactly.** -/
theorem inertiaDeg'_eq : v.asIdeal.inertiaDeg' w.asIdeal = 1 := by
  have hb := inertiaDeg_int_eq_mul_inertiaDeg' v w (p := p)
  rw [inertiaDeg_w, inertiaDeg_v] at hb
  omega

/-! ### `theta := ζ - 1`, a primitive element of `L / K` which is also a uniformizer

The completed-level separability/degree argument (`Langlands.AdicCompletionPrimitiveElementDegree`)
needs a primitive element of `L / K` whose minimal polynomial *stays irreducible* after base change
to `Kv := v.adicCompletion K`. `ζ` itself is a primitive element (`minpoly K ζ = X ^ p - C c`, with
`c : K` the copy of `ζₚ = ζ ^ p` inside `K`), but its minimal polynomial is **not** Eisenstein at
`v`: its constant term `-c` is a root of unity, hence a unit at `v`. The shift `theta := ζ - 1`
fixes exactly this: `minpoly K theta = (X + 1) ^ p - C c` has constant term `1 - c`, and `c - 1`
generates `v.asIdeal` *exactly* (`IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver'`,
applied to `c`, itself a primitive `p`-th root of unity in `K`), so the constant term has valuation
exactly the uniformizer value — the Eisenstein condition. -/

/-- `theta := ζ - 1`, the primitive element used throughout the completed-level argument. -/
noncomputable def theta : L := ζ - 1

/-- `c : K`, the copy of `ζₚ = ζ ^ p` living inside `K = ℚ⟮ζₚ⟯` itself. -/
noncomputable def c : K := IntermediateField.AdjoinSimple.gen ℚ ζₚ

theorem algebraMap_c : algebraMap K L c = ζₚ := IntermediateField.AdjoinSimple.algebraMap_gen ℚ ζₚ

theorem hc : IsPrimitiveRoot c p :=
  IsPrimitiveRoot.of_map_of_injective (f := algebraMap K L) (by rw [algebraMap_c]; exact hζₚ)
    (algebraMap K L).injective

/-! ### The degrees: `[L : ℚ] = 6`, `[K : ℚ] = 2`, hence `[L : K] = p = 3` -/

instance : NeZero (p ^ (1 + 1)) := ⟨by decide⟩

instance : NeZero p := ⟨by decide⟩

theorem finrank_ℚ_L : Module.finrank ℚ L = 6 := by
  rw [IsCyclotomicExtension.Rat.finrank (p ^ (1 + 1)) L]; decide

theorem finrank_ℚ_K : Module.finrank ℚ K = 2 := by
  rw [IsCyclotomicExtension.Rat.finrank p K]; decide

theorem finrank_K_L : Module.finrank K L = p := by
  have h := Module.finrank_mul_finrank ℚ K L
  rw [finrank_ℚ_K, finrank_ℚ_L] at h
  show Module.finrank K L = 3
  omega

/-! ### `theta` is a primitive element: `K⟮theta⟯ = ⊤` -/

theorem adjoin_theta_eq_top : IntermediateField.adjoin K ({theta} : Set L) = ⊤ := by
  have hθ : theta ∈ IntermediateField.adjoin K ({theta} : Set L) :=
    IntermediateField.subset_adjoin _ _ rfl
  have hζmem : ζ ∈ IntermediateField.adjoin K ({theta} : Set L) := by
    have h := (IntermediateField.adjoin K ({theta} : Set L)).add_mem hθ
      (IntermediateField.one_mem _)
    simpa [theta] using h
  rw [eq_top_iff]
  rintro x -
  have hx : x ∈ Algebra.adjoin ℚ ({ζ} : Set L) :=
    (IsCyclotomicExtension.adjoin_primitive_root_eq_top (A := ℚ) (B := L) hζ) ▸ Algebra.mem_top
  induction hx using Algebra.adjoin_induction with
  | mem y hy => rw [Set.mem_singleton_iff.mp hy]; exact hζmem
  | algebraMap r =>
    rw [IsScalarTower.algebraMap_apply ℚ K L]
    exact IntermediateField.algebraMap_mem _ _
  | add y z _ _ ihy ihz => exact (IntermediateField.adjoin K ({theta} : Set L)).add_mem ihy ihz
  | mul y z _ _ ihy ihz => exact (IntermediateField.adjoin K ({theta} : Set L)).mul_mem ihy ihz

/-! ### The shifted polynomial `(X + 1) ^ p - C a`, in expanded form

Kept in the *expanded* form `X ^ 3 + C 3 * X ^ 2 + C 3 * X + C (1 - a)` (`p = 3`) rather than as
`(X + 1) ^ p - C a`, so that its coefficients — the data the Eisenstein criterion consumes — are
directly readable, while `eisPoly_eq_shift` recovers the conceptual form for the `aeval` computation.
Stated over an arbitrary commutative ring so that the *same* polynomial can be used over `K`
(where it is `minpoly K theta`), over `v.adicCompletionIntegers K` (where it is Eisenstein), and
over `v.adicCompletion K` (where Gauss's lemma delivers irreducibility). -/

/-- `eisPoly a = (X + 1) ^ p - C a`, expanded. -/
noncomputable def eisPoly {A : Type*} [CommRing A] (a : A) : Polynomial A :=
  Polynomial.X ^ 3 + Polynomial.C 3 * Polynomial.X ^ 2 + Polynomial.C 3 * Polynomial.X
    + Polynomial.C (1 - a)

variable {A B : Type*} [CommRing A] [CommRing B]

theorem eisPoly_eq_shift (a : A) :
    eisPoly a = (Polynomial.X + 1) ^ p - Polynomial.C a := by
  simp only [eisPoly, map_sub, map_one, map_ofNat, p]
  ring

theorem eisPoly_monic (a : A) : (eisPoly a).Monic := by
  unfold eisPoly
  monicity!

theorem eisPoly_natDegree [Nontrivial A] (a : A) : (eisPoly a).natDegree = 3 := by
  unfold eisPoly
  compute_degree!

theorem eisPoly_degree [Nontrivial A] (a : A) : (eisPoly a).degree = 3 := by
  rw [Polynomial.degree_eq_natDegree (eisPoly_monic a).ne_zero, eisPoly_natDegree]
  rfl

theorem eisPoly_map (f : A →+* B) (a : A) : (eisPoly a).map f = eisPoly (f a) := by
  simp only [eisPoly, Polynomial.map_add, Polynomial.map_mul, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.map_C, Polynomial.map_ofNat, Polynomial.map_sub, Polynomial.map_one, map_sub,
    map_one, map_ofNat]

theorem eisPoly_coeff_zero (a : A) : (eisPoly a).coeff 0 = 1 - a := by
  simp [eisPoly]

theorem eisPoly_coeff_one (a : A) : (eisPoly a).coeff 1 = 3 := by
  simp [eisPoly, Polynomial.coeff_one]

theorem eisPoly_coeff_two (a : A) : (eisPoly a).coeff 2 = 3 := by
  simp [eisPoly, Polynomial.coeff_one]

/-! ### `minpoly K theta = eisPoly c` -/

theorem aeval_theta_eisPoly : Polynomial.aeval theta (eisPoly c) = 0 := by
  rw [eisPoly_eq_shift]
  simp only [map_sub, map_pow, map_add, Polynomial.aeval_X, Polynomial.aeval_one,
    Polynomial.aeval_C, algebraMap_c]
  show (theta + 1) ^ p - ζₚ = 0
  rw [show theta + 1 = ζ by rw [theta]; ring]
  rw [ζₚ, sub_self]

theorem isIntegral_theta : IsIntegral K theta :=
  ⟨eisPoly c, eisPoly_monic c, aeval_theta_eisPoly⟩

theorem natDegree_minpoly_theta : (minpoly K theta).natDegree = 3 := by
  have h := IntermediateField.adjoin.finrank isIntegral_theta
  rw [adjoin_theta_eq_top,
    LinearEquiv.finrank_eq (IntermediateField.topEquiv (F := K) (E := L)).toLinearEquiv,
    finrank_K_L] at h
  exact h.symm

theorem minpoly_theta_eq : minpoly K theta = eisPoly c := by
  refine (minpoly.unique K theta (eisPoly_monic c) aeval_theta_eisPoly fun q hq haq => ?_).symm
  rw [eisPoly_degree]
  have hmin := minpoly.min K theta hq haq
  rwa [Polynomial.degree_eq_natDegree (minpoly.ne_zero isIntegral_theta),
    natDegree_minpoly_theta] at hmin

/-! ### `c - 1` is an exact uniformizer at `v`

`c` is a primitive `p`-th root of unity **in `K`**, so `IsCyclotomicExtension.Rat.
eq_span_zeta_sub_one_of_liesOver'` (applied to the prime `v.asIdeal`, which lies over the rational
prime `p`) says `v.asIdeal = span {γ - 1}` for `γ := hc.toInteger` — *exactly*, not merely up to a
power. Note this does not touch the already-closed definition of `v` (built from a possibly
different primitive root `ζ_K`): the lemma applies to every primitive `p`-th root of `K` alike. -/

/-- `γ := hc.toInteger : 𝓞 K`, the algebraic integer underlying `c`. -/
noncomputable def γ : 𝓞 K := hc.toInteger

theorem γ_sub_one_ne_zero : (γ - 1 : 𝓞 K) ≠ 0 := (hc.zeta_sub_one_prime' (p := p)).ne_zero

theorem v_asIdeal_eq_span : v.asIdeal = Ideal.span {(γ - 1 : 𝓞 K)} :=
  IsCyclotomicExtension.Rat.eq_span_zeta_sub_one_of_liesOver' p K hc v.asIdeal

theorem intValuation_γ_sub_one : v.intValuation (γ - 1 : 𝓞 K) = WithZero.exp (-1 : ℤ) :=
  v.intValuation_singleton γ_sub_one_ne_zero v_asIdeal_eq_span

/-! ### The Eisenstein setup over `𝒪 := v.adicCompletionIntegers K` -/

/-- `π₀`, the image of the uniformizer `γ - 1` in `𝒪 := v.adicCompletionIntegers K`. -/
noncomputable def π₀ : v.adicCompletionIntegers K :=
  algebraMap (𝓞 K) (v.adicCompletionIntegers K) (γ - 1)

/-- `c₀`, the image of `γ` in `𝒪`. -/
noncomputable def c₀ : v.adicCompletionIntegers K :=
  algebraMap (𝓞 K) (v.adicCompletionIntegers K) γ

theorem c₀_sub_one : c₀ - 1 = π₀ := by rw [π₀, map_sub, map_one, c₀]

theorem valuation_π₀ :
    Valued.v (π₀ : v.adicCompletion K) = WithZero.exp (-1 : ℤ) := by
  rw [π₀, IsDedekindDomain.HeightOneSpectrum.algebraMap_adicCompletionIntegers_apply,
    IsDedekindDomain.HeightOneSpectrum.valuedAdicCompletion_eq_valuation',
    v.valuation_of_algebraMap]
  exact intValuation_γ_sub_one

theorem π₀_ne_zero : (π₀ : v.adicCompletionIntegers K) ≠ 0 := by
  intro h0
  have := valuation_π₀
  rw [show ((π₀ : v.adicCompletionIntegers K) : v.adicCompletion K) = 0 by rw [h0]; rfl,
    Valuation.map_zero] at this
  exact absurd this.symm (by simp)

theorem isUniformizer_π₀ :
    Valuation.IsUniformizer Valued.v (π₀ : v.adicCompletion K) := by
  rw [Valuation.IsUniformizer.iff, valuation_π₀,
    Valuation.IsRankOneDiscrete.generator_eq_exp_neg_one_of_surjective
      (IsDedekindDomain.HeightOneSpectrum.valuedAdicCompletion_surjective K v)]
  rfl

theorem maximalIdeal_eq_span_π₀ :
    IsLocalRing.maximalIdeal (v.adicCompletionIntegers K) =
      Ideal.span {(π₀ : v.adicCompletionIntegers K)} :=
  isUniformizer_π₀.is_generator

theorem π₀_mem_maximalIdeal :
    (π₀ : v.adicCompletionIntegers K) ∈
      IsLocalRing.maximalIdeal (v.adicCompletionIntegers K) := by
  rw [maximalIdeal_eq_span_π₀]
  exact Ideal.mem_span_singleton_self _

/-- `p = 3` lies in `v.asIdeal`: `(γ - 1) ^ (p - 1)` is associated to `p`
(`IsCyclotomicExtension.Rat.associated_zeta_sub_one_pow_prime`), so `γ - 1` divides `p`. -/
theorem p_mem_v_asIdeal : ((p : ℕ) : 𝓞 K) ∈ v.asIdeal := by
  have hassoc := IsCyclotomicExtension.Rat.associated_zeta_sub_one_pow_prime p hc
  rw [v_asIdeal_eq_span, Ideal.mem_span_singleton]
  refine dvd_trans (dvd_pow_self _ (by decide : p - 1 ≠ 0)) hassoc.dvd

theorem three_mem_maximalIdeal :
    (3 : v.adicCompletionIntegers K) ∈
      IsLocalRing.maximalIdeal (v.adicCompletionIntegers K) := by
  have hcast : (3 : v.adicCompletionIntegers K) =
      algebraMap (𝓞 K) (v.adicCompletionIntegers K) ((p : ℕ) : 𝓞 K) := by
    rw [show ((p : ℕ) : 𝓞 K) = (3 : 𝓞 K) from rfl, map_ofNat]
  refine IsDedekindDomain.HeightOneSpectrum.mem_maximalIdeal_of_valued_lt_one v ?_
  rw [hcast, IsDedekindDomain.HeightOneSpectrum.algebraMap_adicCompletionIntegers_apply,
    IsDedekindDomain.HeightOneSpectrum.valuedAdicCompletion_eq_valuation',
    v.valuation_lt_one_iff_mem]
  exact p_mem_v_asIdeal

theorem eisPoly_c₀_isEisensteinAt :
    (eisPoly c₀).IsEisensteinAt (IsLocalRing.maximalIdeal (v.adicCompletionIntegers K)) := by
  refine (eisPoly_monic c₀).isEisensteinAt_of_mem_of_notMem
    (IsLocalRing.maximalIdeal.isMaximal _).ne_top ?_ ?_
  · intro n hn
    rw [eisPoly_natDegree] at hn
    interval_cases n
    · rw [eisPoly_coeff_zero, show (1 : v.adicCompletionIntegers K) - c₀ = -π₀ by
        rw [← c₀_sub_one]; ring]
      exact neg_mem π₀_mem_maximalIdeal
    · rw [eisPoly_coeff_one]; exact three_mem_maximalIdeal
    · rw [eisPoly_coeff_two]; exact three_mem_maximalIdeal
  · rw [eisPoly_coeff_zero, maximalIdeal_eq_span_π₀, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton]
    rintro ⟨t, ht⟩
    have hfac : (π₀ : v.adicCompletionIntegers K) * (-1 - π₀ * t) = 0 := by
      have h1 : (1 : v.adicCompletionIntegers K) - c₀ = -π₀ := by rw [← c₀_sub_one]; ring
      rw [h1] at ht
      linear_combination ht
    rcases mul_eq_zero.mp hfac with h | h
    · exact π₀_ne_zero h
    · refine absurd π₀_mem_maximalIdeal ?_
      rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not]
      exact IsUnit.of_mul_eq_one (-t) (by linear_combination h)

/-- **The base-changed polynomial is irreducible over `𝒪`** — Eisenstein at the maximal ideal. -/
theorem eisPoly_c₀_irreducible : Irreducible (eisPoly c₀) :=
  eisPoly_c₀_isEisensteinAt.irreducible (IsLocalRing.maximalIdeal.isMaximal _).isPrime
    (eisPoly_monic c₀).isPrimitive (by rw [eisPoly_natDegree]; norm_num)

/-- **Irreducibility over the completion `Kv := v.adicCompletion K`**, by Gauss's lemma
(`Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map`, applicable since `𝒪` is
integrally closed with fraction field `Kv`). -/
theorem map_minpoly_theta_irreducible :
    Irreducible ((minpoly K theta).map (algebraMap K (v.adicCompletion K))) := by
  have hgauss : Irreducible ((eisPoly c₀).map
      (algebraMap (v.adicCompletionIntegers K) (v.adicCompletion K))) :=
    ((eisPoly_monic c₀).irreducible_iff_irreducible_map_fraction_map).mp eisPoly_c₀_irreducible
  rw [eisPoly_map, show algebraMap (v.adicCompletionIntegers K) (v.adicCompletion K) c₀ =
    algebraMap K (v.adicCompletion K) c from rfl] at hgauss
  rwa [minpoly_theta_eq, eisPoly_map]

end Langlands.TotallyRamifiedCyclotomicConcreteExample

end
