/-
Copyright (c) 2026 rhizone. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Langlands.TotallyRamifiedEisenstein
import Langlands.MonogenicIntegralClosure

/-!
# Residue-field preservation for a totally ramified extension, via monogenicity

`ROADMAP.md` `§48` recorded residue-field preservation (`ResidueField 𝒪_L ≃+* ResidueField 𝒪[K]`
for `L / K` totally ramified) as the sole remaining blocker to the Lubin-Tate tower step, and
recorded the expectation that closing it would need a fresh `e · f = n` development, because
`Langlands/TotallyRamifiedValuationExtension.lean`'s `IsTotallyRamified` structure states it as an
*unavoidable hypothesis field* whose classical derivation goes through that identity.

**That expectation is corrected here: no `e · f = n` argument is needed.** Once the ring of
integers is known to be *monogenic* over `𝒪[K]`, generated by a single element of the maximal ideal
— which is exactly what `Langlands/TotallyRamifiedEisenstein.lean`'s
`LocalField.adjoin_eq_integralClosure_of_isUniformizer` already proves for a totally ramified
extension, in the `spectralNorm`/`NormedField` formalism — residue-field preservation is a
*two-line elementary quotient argument*: every `x : 𝒪_L` is a polynomial in `π` with `𝒪[K]`
coefficients, and modulo `𝔪_L ∋ π` only the constant coefficient survives, so the residue map
`𝓀[K] → 𝓀[L]` is surjective; it is injective for free, being a ring homomorphism of fields.

Nothing about ramification indices, inertia degrees, or `Ideal.sum_ramification_inertia` enters.

## Main results

* `IsLocalRing.residueField_map_surjective_of_adjoin_singleton` : the elementary engine, with no
  valuation theory in sight. For `A → B` a local homomorphism of local rings with
  `Algebra.adjoin A {π} = ⊤` for some `π ∈ 𝔪_B`, `IsLocalRing.ResidueField.map (algebraMap A B)` is
  surjective.
* `IsLocalRing.residueFieldEquivOfAdjoinSingleton` : the same hypotheses package it as a
  `RingEquiv`, injectivity coming from `RingHom.injective` (a ring hom out of a field).
* `LocalField.spectralNorm_le_one_of_isIntegral` : the converse of
  `LocalField.isIntegral_of_spectralNorm_le_one` (`Langlands/MonogenicIntegralClosure.lean`) —
  an element integral over `𝒪[K]` has `spectralNorm K L x ≤ 1`. Proved by transporting
  `minpoly ↥𝒪[K] x`'s coefficients up along `minpoly.isIntegrallyClosed_eq_field_fractions'` and
  applying Mathlib's `spectralValue_le_one_iff`. Not previously available in either direction here.
* `LocalField.notMem_isUnit_of_spectralNorm_lt_one`, phrased as
  `LocalField.mem_maximalIdeal_integralClosure_of_spectralNorm_lt_one` : an element of `𝒪_L` of
  spectral norm `< 1` lies in `𝔪_{𝒪_L}`.
* `LocalField.adjoin_singleton_eq_top_of_isUniformizer` : the `Subalgebra ↥𝒪[K] ↥𝒪_L` form of
  `adjoin_eq_integralClosure_of_isUniformizer` — `Algebra.adjoin ↥𝒪[K] {π'} = ⊤` for `π'` the
  uniformizer viewed inside `𝒪_L`, rather than the `Subalgebra ↥𝒪[K] L` form the Eisenstein file
  proves.
* `LocalField.residueField_map_bijective_of_isUniformizer` and
  `LocalField.residueFieldEquivOfIsUniformizer` : **the headline results.** Under exactly the
  hypotheses of `adjoin_eq_integralClosure_of_isUniformizer` (`hram` total ramification, `hgen`
  generation), `IsLocalRing.ResidueField ↥𝒪[K] ≃+* IsLocalRing.ResidueField ↥(integralClosure
  ↥𝒪[K] L)`.

## Which ring `𝒪_L` is

Everything here is stated for `integralClosure ↥(ValuativeRel.valuation K).valuationSubring L`,
the spelling that carries Mathlib's `Algebra`/`IsLocalHom` instances
(`LocalField.isLocalHom_algebraMap_integralClosure`, `Langlands/MonogenicIntegralClosure.lean`) and
that `adjoin_eq_integralClosure_of_isUniformizer` states its conclusion in. It is the same ring as
`↥(NormedField.valuation (K := L)).valuationSubring` used by
`Langlands/LubinTateSplittingFieldDVR.lean` — the identification is
`LocalField.valuationSubring_eq_of_comap_eq` (`Langlands/HenselianValuation.lean`), already carried
out three times in that file — but no such transport is needed for the statements here.
-/

noncomputable section

open IsLocalRing ValuativeRel Polynomial

/-! ## The elementary engine -/

/-- **A local ring generated over a local subring by one element of the maximal ideal has the same
residue field.** No valuation theory, no ramification theory: if `B` is generated as an `A`-algebra
by a single `π ∈ 𝔪_B`, then every `x : B` is `Polynomial.aeval π p` for some `p : A[X]`, and
`aeval π p - algebraMap A B (p.coeff 0) = π * aeval π p.divX ∈ 𝔪_B`
(`Polynomial.X_mul_divX_add`), so `x` and `algebraMap A B (p.coeff 0)` have the same residue. -/
theorem IsLocalRing.residueField_map_surjective_of_adjoin_singleton
    {A B : Type*} [CommRing A] [IsLocalRing A] [CommRing B] [IsLocalRing B]
    [Algebra A B] [IsLocalHom (algebraMap A B)]
    {π : B} (hπ : π ∈ maximalIdeal B)
    (hadj : Algebra.adjoin A ({π} : Set B) = ⊤) :
    Function.Surjective (ResidueField.map (algebraMap A B)) := by
  intro y
  obtain ⟨x, rfl⟩ := IsLocalRing.residue_surjective y
  have hx : x ∈ Algebra.adjoin A ({π} : Set B) := hadj ▸ Algebra.mem_top
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hx
  obtain ⟨p, hp⟩ := hx
  have hp' : Polynomial.aeval π p = x := hp
  refine ⟨residue A (p.coeff 0), ?_⟩
  rw [ResidueField.map_residue]
  have key : Polynomial.aeval π (Polynomial.X * p.divX + Polynomial.C (p.coeff 0)) =
      Polynomial.aeval π p := by
    rw [Polynomial.X_mul_divX_add]
  have hsplit : π * Polynomial.aeval π p.divX + algebraMap A B (p.coeff 0) = x := by
    rw [← hp', ← key, map_add, map_mul, Polynomial.aeval_X, Polynomial.aeval_C]
  have hmem : x - algebraMap A B (p.coeff 0) ∈ maximalIdeal B := by
    have : x - algebraMap A B (p.coeff 0) = π * Polynomial.aeval π p.divX := by
      rw [← hsplit]; ring
    rw [this]
    exact Ideal.mul_mem_right _ _ hπ
  exact (Ideal.Quotient.eq.mpr hmem).symm

/-- The `RingEquiv` packaging of `IsLocalRing.residueField_map_surjective_of_adjoin_singleton`:
injectivity is free, `ResidueField.map (algebraMap A B)` being a ring homomorphism out of a
field. -/
def IsLocalRing.residueFieldEquivOfAdjoinSingleton
    {A B : Type*} [CommRing A] [IsLocalRing A] [CommRing B] [IsLocalRing B]
    [Algebra A B] [IsLocalHom (algebraMap A B)]
    {π : B} (hπ : π ∈ maximalIdeal B)
    (hadj : Algebra.adjoin A ({π} : Set B) = ⊤) :
    ResidueField A ≃+* ResidueField B :=
  RingEquiv.ofBijective (ResidueField.map (algebraMap A B))
    ⟨(ResidueField.map (algebraMap A B)).injective,
      residueField_map_surjective_of_adjoin_singleton hπ hadj⟩

namespace LocalField

variable (K : Type*) [NontriviallyNormedField K] [IsUltrametricDist K] [ValuativeRel K]
  [(NormedField.valuation (K := K)).Compatible] [CompleteSpace K]
  {L : Type*} [Field L] [Algebra K L] [FiniteDimensional K L]

/-! ## Spectral norm and integrality -/

omit [CompleteSpace K] in
/-- **The converse of `LocalField.isIntegral_of_spectralNorm_le_one`**: an element of `L` integral
over `𝒪[K]` has spectral norm at most `1`.

`minpoly.isIntegrallyClosed_eq_field_fractions'` identifies `minpoly K x` with the image of
`minpoly ↥𝒪[K] x`, whose coefficients lie in `𝒪[K]` by construction, hence have norm `≤ 1`
(`mem_valuationSubring_iff_norm_le_one`); Mathlib's `spectralValue_le_one_iff` for the monic
`minpoly K x` then gives `spectralValue (minpoly K x) = spectralNorm K L x ≤ 1`. -/
theorem spectralNorm_le_one_of_isIntegral {x : L}
    (hx : IsIntegral ↥(valuation K).valuationSubring x) :
    spectralNorm K L x ≤ 1 := by
  haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
  have hmonic : (minpoly K x).Monic := minpoly.monic (Algebra.IsIntegral.isIntegral x)
  have hminpolyeq : minpoly K x =
      Polynomial.map (algebraMap ↥(valuation K).valuationSubring K)
        (minpoly ↥(valuation K).valuationSubring x) :=
    minpoly.isIntegrallyClosed_eq_field_fractions' K hx
  rw [spectralNorm, spectralValue_le_one_iff hmonic]
  intro n
  rw [hminpolyeq, Polynomial.coeff_map, ValuationSubring.algebraMap_apply,
    ← mem_valuationSubring_iff_norm_le_one K]
  exact ((minpoly ↥(valuation K).valuationSubring x).coeff n).2

/-- An element of `𝒪_L := integralClosure 𝒪[K] L` whose spectral norm is strictly less than `1`
lies in the maximal ideal.

If it were a unit of `𝒪_L` its inverse would be integral over `𝒪[K]`, hence of spectral norm `≤ 1`
(`spectralNorm_le_one_of_isIntegral`); but multiplicativity of the spectral norm
(`spectralAlgNorm_mul`) forces `spectralNorm K L x * spectralNorm K L x⁻¹ = 1`, contradicting
`spectralNorm K L x < 1`. -/
theorem mem_maximalIdeal_integralClosure_of_spectralNorm_lt_one
    (x : ↥(integralClosure ↥(valuation K).valuationSubring L))
    (hx : spectralNorm K L (x : L) < 1) :
    x ∈ maximalIdeal ↥(integralClosure ↥(valuation K).valuationSubring L) := by
  haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
  rw [IsLocalRing.mem_maximalIdeal]
  intro hu
  have hx0 : (x : L) ≠ 0 := by
    intro h0
    rw [h0, spectralNorm_zero] at hx
    obtain ⟨s, hs⟩ := hu.exists_right_inv
    have hcontr : (0 : L) * (s : L) = 1 := by
      simpa [h0] using congrArg (Subtype.val) hs
    simp at hcontr
  obtain ⟨s, hs⟩ := hu.exists_right_inv
  have hsL : (x : L) * (s : L) = 1 := by
    simpa using congrArg (Subtype.val) hs
  have hsinv : (s : L) = (x : L)⁻¹ := eq_inv_of_mul_eq_one_right hsL
  have hsint : IsIntegral ↥(valuation K).valuationSubring ((x : L)⁻¹) := hsinv ▸ s.2
  have hsle : spectralNorm K L ((x : L)⁻¹) ≤ 1 := spectralNorm_le_one_of_isIntegral K hsint
  have hmul : spectralNorm K L (x : L) * spectralNorm K L ((x : L)⁻¹) = 1 := by
    have := spectralAlgNorm_mul (K := K) (L := L) (x : L) ((x : L)⁻¹)
    rw [mul_inv_cancel₀ hx0] at this
    simpa [spectralAlgNorm_def, spectralNorm_one] using this.symm
  nlinarith [spectralNorm_nonneg (K := K) (L := L) (x : L),
    spectralNorm_nonneg (K := K) (L := L) ((x : L)⁻¹)]

/-! ## Residue-field preservation -/

variable [IsDiscreteValuationRing ↥(valuation K).valuationSubring] [Algebra.IsSeparable K L]

/-- **The `Subalgebra ↥𝒪[K] ↥𝒪_L` form of monogenicity.**
`adjoin_eq_integralClosure_of_isUniformizer` (`Langlands/TotallyRamifiedEisenstein.lean`) states
`Algebra.adjoin ↥𝒪[K] {π} = integralClosure ↥𝒪[K] L` as an equality of subalgebras *of `L`*; this
restates it as `Algebra.adjoin ↥𝒪[K] {π'} = ⊤` inside `𝒪_L` itself, where `π'` is `π` viewed as an
element of the integral closure. Transport is by `Polynomial.aeval_algHom_apply` along
`Subalgebra.val`. -/
theorem adjoin_singleton_eq_top_of_isUniformizer
    {ϖ : ↥(valuation K).valuationSubring} (hϖ : Irreducible ϖ) {π : L}
    (hram : ‖(ϖ : K)‖ = spectralNorm K L π ^ (minpoly K π).natDegree)
    (hgen : (minpoly K π).natDegree = Module.finrank K L)
    (hπint : IsIntegral ↥(valuation K).valuationSubring π) :
    Algebra.adjoin ↥(valuation K).valuationSubring
        ({(⟨π, hπint⟩ : ↥(integralClosure ↥(valuation K).valuationSubring L))} :
          Set ↥(integralClosure ↥(valuation K).valuationSubring L)) = ⊤ := by
  haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
  have hadjL : Algebra.adjoin ↥(valuation K).valuationSubring ({π} : Set L) =
      integralClosure ↥(valuation K).valuationSubring L :=
    adjoin_eq_integralClosure_of_isUniformizer K hϖ hram hgen
  refine Algebra.eq_top_iff.mpr fun b => ?_
  have hb : (b : L) ∈ Algebra.adjoin ↥(valuation K).valuationSubring ({π} : Set L) := by
    rw [hadjL]; exact b.2
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hb
  obtain ⟨p, hp⟩ := hb
  have hp' : Polynomial.aeval π p = (b : L) := hp
  have hval : (Polynomial.aeval (⟨π, hπint⟩ :
      ↥(integralClosure ↥(valuation K).valuationSubring L)) p) = b := by
    have haeval := Polynomial.aeval_algHom_apply
      (Subalgebra.val (integralClosure ↥(valuation K).valuationSubring L))
      (⟨π, hπint⟩ : ↥(integralClosure ↥(valuation K).valuationSubring L)) p
    refine Subtype.ext ?_
    simpa [hp'] using haeval.symm
  rw [← hval, Algebra.adjoin_singleton_eq_range_aeval]
  exact ⟨p, rfl⟩

/-- **Residue-field preservation for a totally ramified extension.** Under exactly the hypotheses of
`adjoin_eq_integralClosure_of_isUniformizer` — `ϖ` a uniformizer of `𝒪[K]`, `π : L` satisfying the
total-ramification condition `hram : ‖ϖ‖ = spectralNorm K L π ^ (minpoly K π).natDegree`, and `π`
generating `L` over `K` (`hgen`) — the induced map on residue fields
`𝓀[K] → 𝓀[𝒪_L]` is bijective.

Surjectivity is `IsLocalRing.residueField_map_surjective_of_adjoin_singleton` applied to
`adjoin_singleton_eq_top_of_isUniformizer`, with `π ∈ 𝔪_{𝒪_L}` from
`mem_maximalIdeal_integralClosure_of_spectralNorm_lt_one` (`spectralNorm K L π < 1` follows from
`hram` and `‖ϖ‖ < 1`); injectivity is free. **No `e · f = n` identity is used.** -/
theorem residueField_map_bijective_of_isUniformizer
    {ϖ : ↥(valuation K).valuationSubring} (hϖ : Irreducible ϖ) {π : L}
    (hram : ‖(ϖ : K)‖ = spectralNorm K L π ^ (minpoly K π).natDegree)
    (hgen : (minpoly K π).natDegree = Module.finrank K L) :
    Function.Bijective (ResidueField.map (algebraMap ↥(valuation K).valuationSubring
      ↥(integralClosure ↥(valuation K).valuationSubring L))) := by
  haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
  have hπint : IsIntegral ↥(valuation K).valuationSubring π :=
    isIntegral_of_isUniformizer K hϖ hram
  have hϖlt : ‖(ϖ : K)‖ < 1 :=
    (mem_maximalIdeal_iff_norm_lt_one K ϖ).mp
      ((IsLocalRing.mem_maximalIdeal _).mpr fun hu => hϖ.not_isUnit hu)
  have hspec : spectralNorm K L π < 1 := by
    by_contra hge
    push Not at hge
    have h1 : (1 : ℝ) ≤ spectralNorm K L π ^ (minpoly K π).natDegree := one_le_pow₀ hge
    rw [← hram] at h1
    linarith
  have hmem : (⟨π, hπint⟩ : ↥(integralClosure ↥(valuation K).valuationSubring L)) ∈
      maximalIdeal ↥(integralClosure ↥(valuation K).valuationSubring L) :=
    mem_maximalIdeal_integralClosure_of_spectralNorm_lt_one K _ hspec
  exact ⟨(ResidueField.map _).injective,
    IsLocalRing.residueField_map_surjective_of_adjoin_singleton hmem
      (adjoin_singleton_eq_top_of_isUniformizer K hϖ hram hgen hπint)⟩

/-- **The residue field of a totally ramified extension is the base residue field**, packaged as a
`RingEquiv`. See `residueField_map_bijective_of_isUniformizer`. -/
def residueFieldEquivOfIsUniformizer
    {ϖ : ↥(valuation K).valuationSubring} (hϖ : Irreducible ϖ) {π : L}
    (hram : ‖(ϖ : K)‖ = spectralNorm K L π ^ (minpoly K π).natDegree)
    (hgen : (minpoly K π).natDegree = Module.finrank K L) :
    ResidueField ↥(valuation K).valuationSubring ≃+*
      ResidueField ↥(integralClosure ↥(valuation K).valuationSubring L) :=
  RingEquiv.ofBijective _ (residueField_map_bijective_of_isUniformizer K hϖ hram hgen)

end LocalField
