import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.NumberTheory.LocalField.Basic
import Mathlib.RingTheory.Valuation.RamificationGroup
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.RingTheory.Valuation.LocalSubring
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion

/-!
# The Weil group of a nonarchimedean local field

Let `K` be a nonarchimedean local field, with ring of integers `𝒪[K]`, maximal ideal `𝓂[K]`
and (finite) residue field `𝓀[K]`. Let `K̄` be an algebraic closure of `K` and
`G_K = Gal(K̄/K) = Field.absoluteGaloisGroup K` its absolute Galois group.

Choosing a valuation subring `𝒪[K̄]` of `K̄` extending `𝒪[K]` (Chevalley's extension theorem;
unique up to `G_K`-conjugacy, and since `K` is complete, in fact the *decomposition subgroup* of
`𝒪[K̄]` -- the stabilizer of `𝒪[K̄]` inside `G_K` -- is all of `G_K`), we get:

* a residue field `𝓀[K̄] := IsLocalRing.ResidueField 𝒪[K̄]`, an algebraic closure of `𝓀[K]`;
* the *inertia subgroup* `I_K ≤ G_K`, the kernel of the induced action of `G_K` on `𝓀[K̄]`;
* the induced action `ρ : G_K →* RingAut 𝓀[K̄]`, whose image is (all of) the profinite Galois
  group `Gal(𝓀[K̄]/𝓀[K])`, generated topologically by the (arithmetic) Frobenius
  `x ↦ x ^ #𝓀[K]` and abstractly isomorphic to `ℤ̂`, the profinite completion of `ℤ`.

This gives the exact sequence `1 → I_K → G_K → Gal(𝓀[K̄]/𝓀[K]) → 1`, and, transporting along
the (highly nontrivial, and currently `sorry`-ed) isomorphism `Gal(𝓀[K̄]/𝓀[K]) ≃ ℤ̂`, a
homomorphism `G_K →* ℤ̂` whose kernel is `I_K`.

The **Weil group** `W_K` is defined as the preimage of the copy of `ℤ` inside `ℤ̂` (the image of
`ℤ̂`'s canonical dense map `ℤ → ℤ̂`) under this homomorphism. Equivalently, `W_K` is the subgroup
of `σ ∈ G_K` whose image in `Gal(𝓀[K̄]/𝓀[K])` is an *integer* power of Frobenius (as opposed to
an arbitrary element of the profinite closure `ℤ̂` of the subgroup generated by Frobenius).

`W_K` is given the topology making `I_K` an *open* subgroup of `W_K` (with its subspace/profinite
topology from `G_K`), rather than the subspace topology from `G_K` -- under the latter, `I_K`
would still be closed but not open, since `⟨Frob⟩ ≅ ℤ` sits densely inside `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂`.
Concretely: `W_K ≅ I_K ⋊ ℤ` as topological groups, where `ℤ` is discrete and `I_K` carries its
profinite topology. Rather than building this topology by transporting the product topology along
a set-theoretic splitting `W_K ≃ I_K × ℤ`, we build it directly as a `GroupFilterBasis` (see
`WeilGroup.groupFilterBasis`) whose basic neighborhoods of `1` are the intersections of `I_K` with
(the restriction to `W_K` of) open subgroups of `G_K` -- this makes `I_K` open by construction,
without needing the splitting itself, and continuity of multiplication/inversion/conjugation
follows directly from the fact that they already hold in `G_K`. The projection `W_K →* ℤ`
(`WeilGroup.toArt`, the local Artin/"art" map) is defined directly from `toZhatHom`, with kernel
`I_K` (`WeilGroup.toArt_ker`); it is *not* yet shown to be continuous for this topology (nor is
the fully set-theoretic splitting `W_K ≃ I_K × ℤ` constructed), which is left for later.

## Main definitions

* `LocalField.valuationSubringExtension K` : a choice of valuation subring `𝒪[K̄]` of (a fixed
  algebraic closure of) `K` extending `𝒪[K]`.
* `LocalField.decompositionSubgroup_eq_top` : the decomposition subgroup of
  `valuationSubringExtension K` is all of `G_K` (uses completeness of `K`).
* `LocalField.inertiaSubgroup K` : the inertia subgroup `I_K ≤ G_K`, transported along
  `decompositionSubgroup_eq_top` from `ValuationSubring.inertiaSubgroup`.
* `LocalField.residueAction K` : the homomorphism `G_K →* RingAut 𝓀[K̄]` induced by the action
  on the residue field, with kernel `I_K`.
* `LocalField.Zhat` : the profinite completion `ℤ̂` of `ℤ` (as a profinite group, multiplicatively
  written), built from Mathlib's general categorical profinite completion of groups.
* `LocalField.frobenius K` : the arithmetic Frobenius `x ↦ x ^ #𝓀[K]` on `𝓀[K̄]`, as an element
  of `RingAut 𝓀[K̄]`.
* `LocalField.residueGaloisGroup_equiv_Zhat` : the (`sorry`-ed) isomorphism identifying the image
  of `residueAction K` with `ℤ̂`, sending Frobenius to (the image of) `1`.
* `LocalField.WeilGroup K` : the Weil group `W_K ≤ G_K`, the preimage of `ℤ ≤ ℤ̂` under (the
  composite of `residueAction K` with) `residueGaloisGroup_equiv_Zhat`.
* `LocalField.toZhat_injective` : `toZhat : ℤ → ℤ̂` is injective (`ℤ` is residually finite), so
  `ℤ ≤ ℤ̂` (`integerSubgroup`) really is (a copy of) `ℤ` (`integerSubgroupEquiv`).
* `LocalField.WeilGroup.toArt` : the Artin ("art") map `W_K →* ℤ`, with kernel `I_K`
  (`WeilGroup.toArt_ker`).
* `LocalField.WeilGroup.groupFilterBasis` : the `GroupFilterBasis` on `W_K` making `I_K` open,
  whose basic neighborhoods of `1` are intersections of `I_K` with open subgroups of `G_K`.
* `LocalField.WeilGroup.instTopologicalSpace` / `instIsTopologicalGroup` : the resulting topology
  on `W_K` and the fact that it makes `W_K` a topological group.
* `LocalField.WeilGroup.isOpen_inertiaSubgroupOf` : `I_K` is open in `W_K` for this topology.

## Implementation notes

Several ingredients used here are genuinely deep theorems that are not (yet) in Mathlib, and are
recorded as `sorry`s rather than proved:

* `exists_valuationSubring_extends` : Chevalley's theorem that every valuation on a field extends
  to any algebraic (or indeed arbitrary) field extension.
* `decompositionSubgroup_eq_top` : uniqueness of the extension of the valuation of a complete
  (Henselian) field to an algebraic extension.
* `residueField_isAlgClosed` / `residueField_isAlgebraic` : the residue field of `𝒪[K̄]` is an
  algebraic closure of `𝓀[K]`.
* `frobenius_mem_residueAction_range` : `residueAction` surjects onto `Gal(𝓀[K̄]/𝓀[K])`, i.e.
  `frobenius K` lies in `(residueAction K).range`. Genuinely local-field-theoretic (not about
  finite fields at all): for a Henselian complete field, the residue extension of an algebraic
  extension is again Galois, with Galois group a quotient of `G_K` -- concretely, every
  automorphism of `𝓀[K̄]/𝓀[K]` lifts to an automorphism of `K̄/K` fixing `valuationSubringExtension
  K`, via the theory of unramified extensions (not a consequence of Mathlib's
  `InfiniteGalois.restrictNormalHom_surjective`, which is surjectivity of a different map).
* `exists_residueGaloisGroup_equiv_Zhat` : the identification `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂` via Frobenius,
  i.e. the classical computation of the absolute Galois group of a finite field. This is stated as
  an abstract group isomorphism sending Frobenius to `1`; upgrading it to a homeomorphism (matching
  the Krull topology on the left against the profinite topology on the right) is left for later.
  Given `frobenius_mem_residueAction_range`, the remaining content is purely about finite fields:
  Mathlib has the pieces (`kbar/𝓀[K]` is Galois via `residueField_isGalois`; each finite
  subextension's Galois group is cyclic, generated by Frobenius, via
  `Mathlib.FieldTheory.Finite.Extension`; `Zhat` satisfies the profinite completion's universal
  property) but not yet a proof that assembles them, which would need identifying `Gal(𝓀[K̄]/𝓀[K])`
  as a `ProfiniteGrp` matching its open-subgroup lattice against the one defining `Zhat` (see the
  docstring of `exists_residueGaloisGroup_equiv_Zhat` for the precise gap).
The full set-theoretic splitting `W_K ≃ I_K × ℤ` (as opposed to just the topology, which is built
directly via `WeilGroup.groupFilterBasis` without needing it) and continuity of `WeilGroup.toArt`
for that topology are not yet constructed either; both are left for later.

Everything else that depends on these five facts *only* formally -- `residueAction_ker`, the
`IsLocalHom` instance for `algebraMap 𝒪[K] 𝒪[K̄]`, `inertiaSubgroup_le_weilGroup`, and the
definitions of `frobenius` / `frobenius_fixes` (via `residueField_isAlgClosed` giving `kbar`
`PerfectField`, hence `PerfectRing kbar p` for `p` the residue characteristic, hence a genuine
`iterateFrobeniusEquiv`) -- is proved outright, not `sorry`-ed. `residueAction_ker` in particular
needs no input beyond `MonoidHom.ker` algebra: `residueAction` is `ValuationSubring.inertiaSubgroup`
composed with the (bijective, value-preserving) `decompositionEquiv`, so its kernel is literally
`inertiaSubgroup K` regardless of which valuation subring extension was chosen. Likewise the
`IsLocalHom` instance is proved directly from `Submonoid.isUnit_iff_and` and
`valuationSubringExtension_comap`, without needing Chevalley's theorem's *content* (only its
statement, `valuationSubringExtension_comap`, which is definitional once a choice is fixed).

None of these are needed for the *definitions* of `inertiaSubgroup`, `residueAction`, `Zhat`,
`frobenius`, or `WeilGroup` themselves to typecheck; they are only needed for the expected
*properties* of these objects (e.g. that `I_K` really is the kernel of `G_K → Gal(k̄/k)`, that
`Zhat` really is (topologically) generated by the image of `1`, etc.), which is why the
definitions are considered the primary deliverable of this file.

## References
* J-P. Serre, *Local Fields*, chapter XII (definition of the Weil group).
* J. Tate, *Number theoretic background*, §1, in *Automorphic forms, representations, and
  L-functions* (Corvallis proceedings).
-/

noncomputable section

open ValuativeRel Valuation IsLocalRing CategoryTheory

namespace LocalField

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- A fixed algebraic closure of `K`. -/
local notation "L" => AlgebraicClosure K

/-! ### The valuation subring of `K̄` extending `𝒪[K]` -/

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- **Chevalley's extension theorem** (not yet in Mathlib): every valuation on a field extends to
an algebraic closure. We record the existence of a valuation subring of `L = AlgebraicClosure K`
lying over `𝒪[K] = (valuation K).valuationSubring` as a `sorry`-ed fact, and fix a choice of such
an extension via `valuationSubringExtension`. -/
theorem exists_valuationSubring_extends :
    ∃ A : ValuationSubring L, A.comap (algebraMap K L) = (valuation K).valuationSubring := by
  set O := (valuation K).valuationSubring with hO
  set f : ↥O →+* L := (algebraMap K L).comp O.subtype with hf
  obtain ⟨A, hA, hloc⟩ := IsLocalRing.exists_factor_valuationRing f
  haveI : IsLocalHom (f.codRestrict A.toSubring hA) := hloc
  refine ⟨A, ValuationSubring.ext _ _ fun x => ?_⟩
  rw [ValuationSubring.mem_comap]
  constructor
  · intro hx
    by_contra hxO
    -- `x ∉ O`, so `x⁻¹ ∈ O` (and `x⁻¹` is a non-unit in `O`, since otherwise `x ∈ O`).
    have hx0 : x ≠ 0 := fun h => hxO (h ▸ O.zero_mem)
    have hxinv : x⁻¹ ∈ O := (O.mem_or_inv_mem x).resolve_left hxO
    set b : ↥O := ⟨x⁻¹, hxinv⟩ with hb
    have hfb : f b ∈ A.toSubring := hA b
    have hfb' : f b = (algebraMap K L x)⁻¹ := by
      show (algebraMap K L) x⁻¹ = (algebraMap K L x)⁻¹
      exact map_inv₀ _ _
    -- both `algebraMap K L x` and its inverse lie in `A`, so it (equivalently, `f b`) is a unit.
    have hne : algebraMap K L x ≠ 0 := (map_ne_zero_iff (algebraMap K L) (algebraMap K L).injective).mpr hx0
    have hub : IsUnit (f.codRestrict A.toSubring hA b) := by
      refine isUnit_iff_exists_inv.mpr ⟨⟨algebraMap K L x, hx⟩, Subtype.ext ?_⟩
      show f b * algebraMap K L x = 1
      rw [hfb', inv_mul_cancel₀ hne]
    have hbunit : IsUnit b := IsLocalHom.map_nonunit b hub
    -- but then `x = (x⁻¹)⁻¹ ∈ O`, contradicting `hxO`.
    obtain ⟨c, hc⟩ := isUnit_iff_exists_inv.mp hbunit
    have hcx : (c : K) = x := by
      have hbc : (b : K) * (c : K) = 1 := congrArg Subtype.val hc
      rw [hb] at hbc
      show (c : K) = x
      field_simp at hbc
      rw [hbc]
    exact hxO (hcx ▸ c.2)
  · intro hxO
    exact hA ⟨x, hxO⟩

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- A choice of valuation subring of `L = AlgebraicClosure K` extending `𝒪[K]`, i.e. "the" ring
of integers `𝒪[K̄]` of the algebraic closure (for our fixed choice of extended valuation). -/
def valuationSubringExtension : ValuationSubring L :=
  (exists_valuationSubring_extends K).choose

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
@[simp]
theorem valuationSubringExtension_comap :
    (valuationSubringExtension K).comap (algebraMap K L) = (valuation K).valuationSubring :=
  (exists_valuationSubring_extends K).choose_spec

/-! ### The decomposition subgroup is everything -/

/-- Since `K` is complete (hence Henselian), the valuation on `K` extends *uniquely* (up to
equivalence) to any algebraic extension of `K`, so every automorphism of `K̄` over `K` stabilizes
`valuationSubringExtension K`. Equivalently: the decomposition subgroup of
`valuationSubringExtension K` is all of `G_K`. This is a standard fact about Henselian valued
fields, not yet in Mathlib as such (searched thoroughly: `Mathlib.RingTheory.Henselian` only has
the local lifting property, not a statement about uniqueness of extension of a valuation/norm to
an algebraic extension; `Mathlib.RingTheory.Valuation.LocalSubring` /
`Mathlib.RingTheory.Valuation.Extension` only give *existence* of extensions, which is what
powers `exists_valuationSubring_extends` above, not uniqueness).

The closest genuine uniqueness statement in Mathlib is on the *normed-field* side, not the
`ValuativeRel`/`ValuationSubring` side used here:
`Mathlib.Analysis.Normed.Unbundled.SpectralNorm.spectralNorm_unique_field_norm_ext` (via
`NormedAlgebra.norm_eq_spectralNorm`) shows that for `K` a complete nonarchimedean normed field and
`L / K` algebraic, *any* multiplicative norm on `L` extending the norm on `K` equals the spectral
norm, i.e. the norm extension is unique. Bridging this to the present statement would require: (1)
transporting `K`'s `ValuativeRel`/rank-≤-1 valuation to a `NormedField` structure (the machinery
exists in `Mathlib.Topology.Algebra.Valued.NormedValued`, e.g. `Valuation.RankOne.toNormedField`)
together with a compatible `CompleteSpace K` instance (available once a `UniformSpace K` compatible
with the topology is fixed, per the module docstring of `IsNonarchimedeanLocalField`); (2) showing
that a `ValuationSubring` of `L` extending `𝒪[K]` in the sense used here (`comap = 𝒪[K]`)
corresponds to a rank-≤-1 (hence normable) valuation on `L`, which itself requires the standard
fact that an algebraic extension of a rank-1-valued field is again rank 1; and (3) using
`spectralNorm_unique_field_norm_ext` to conclude the norms -- and hence the valuation subrings, as
their closed unit balls -- agree, giving stabilization by every automorphism. None of this bridging
work exists in Mathlib yet, so this remains a `sorry`. -/
theorem decompositionSubgroup_eq_top :
    ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) = ⊤ := by
  sorry

/-- The canonical isomorphism `G_K ≃* (decomposition subgroup of `𝒪[K̄]`)`, using
`decompositionSubgroup_eq_top`. -/
def decompositionEquiv :
    Field.absoluteGaloisGroup K ≃*
      ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) :=
  (Subgroup.topEquiv (G := Field.absoluteGaloisGroup K)).symm.trans
    (MulEquiv.subgroupCongr (decompositionSubgroup_eq_top K).symm)

/-! ### The inertia subgroup -/

/-- The inertia subgroup `I_K ≤ G_K`: the kernel of the action of `G_K` on the residue field of
`valuationSubringExtension K`, transported from `ValuationSubring.inertiaSubgroup` along the fact
that the decomposition subgroup of `valuationSubringExtension K` is everything
(`decompositionSubgroup_eq_top`). -/
def inertiaSubgroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (ValuationSubring.inertiaSubgroup K (valuationSubringExtension K)).map
    (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)).subtype

/-! ### The residue field extension and the induced Galois action -/

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄] = valuationSubringExtension K`, i.e. the restriction of
`algebraMap K L` to rings of integers; well-defined by `valuationSubringExtension_comap`. -/
def integersAlgebraMap : ↥(𝒪[K]) →+* valuationSubringExtension K :=
  ((algebraMap K L).comp (𝒪[K]).subtype).codRestrict _ fun x => by
    have hx : (x : K) ∈ (valuation K).valuationSubring :=
      (Valuation.mem_valuationSubring_iff _ _).mpr ((Valuation.mem_integer_iff _ _).mp x.2)
    rw [← valuationSubringExtension_comap K] at hx
    exact (ValuationSubring.mem_comap).mp hx

instance : Algebra ↥(𝒪[K]) (valuationSubringExtension K) := (integersAlgebraMap K).toAlgebra

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄]` is a local homomorphism: since both are valuation subrings and
the inclusion is the restriction of the (injective, field-valued) map `algebraMap K L` compatible
with the valuations, it reflects units. Not yet proved here. -/
instance : IsLocalHom (algebraMap ↥(𝒪[K]) (valuationSubringExtension K)) := by
  refine ⟨fun a ha => ?_⟩
  set A := valuationSubringExtension K
  have hcoe : ((algebraMap ↥(𝒪[K]) A a : A) : L) = algebraMap K L (a : K) := rfl
  rw [Submonoid.isUnit_iff_and, hcoe] at ha
  obtain ⟨hne0, hinv⟩ := ha
  rw [Submonoid.isUnit_iff_and]
  refine ⟨fun h => hne0 (by rw [h]; simp), ?_⟩
  rw [← map_inv₀] at hinv
  have hmem : (a : K)⁻¹ ∈ (valuation K).valuationSubring := by
    rw [← valuationSubringExtension_comap K]
    exact ValuationSubring.mem_comap.mpr hinv
  exact (Valuation.mem_integer_iff _ _).mpr ((Valuation.mem_valuationSubring_iff _ _).mp hmem)

/-- The residue field of the algebraic-closure integers `valuationSubringExtension K`: this is
(a `sorry`-ed fact away from being, via `residueField_isAlgClosed` / `residueField_isAlgebraic`)
an algebraic closure `𝓀[K]bar` of the (finite) residue field `𝓀[K]`. -/
local notation "kbar" => IsLocalRing.ResidueField (valuationSubringExtension K)

/-- The residue field `kbar` of `valuationSubringExtension K` is algebraically closed. This
reflects the general fact that the residue field of a valuation ring inside an algebraically
closed field is algebraically closed; not yet in Mathlib. -/
theorem residueField_isAlgClosed : IsAlgClosed kbar := by
  sorry

/-- The residue field `kbar` of `valuationSubringExtension K` is algebraic over `𝓀[K]`. -/
theorem residueField_isAlgebraic : Algebra.IsAlgebraic 𝓀[K] kbar := by
  sorry

instance : Fact (IsAlgClosed kbar) := ⟨residueField_isAlgClosed K⟩

instance : Algebra.IsAlgebraic 𝓀[K] kbar := residueField_isAlgebraic K

/-- `kbar` is an algebraic closure of `𝓀[K]`, packaging `residueField_isAlgClosed` and
`residueField_isAlgebraic` into the `IsAlgClosure` typeclass. This is what lets us invoke the
general theory of algebraic closures (`IsAlgClosure.normal`, giving `Normal 𝓀[K] kbar`) below,
rather than reproving normality of `kbar/𝓀[K]` by hand. -/
instance : IsAlgClosure 𝓀[K] kbar where
  isAlgClosed := residueField_isAlgClosed K
  isAlgebraic := residueField_isAlgebraic K

/-- `kbar/𝓀[K]` is Galois: it is normal (`IsAlgClosure.normal`, since `kbar` is an algebraic
closure of `𝓀[K]`) and separable (`Algebra.IsAlgebraic.isSeparable_of_perfectField`, since `𝓀[K]`
is finite, hence perfect, and `kbar/𝓀[K]` is algebraic). Unlike the general
`IsAlgClosure.separable` instance in Mathlib, this does not need `CharZero 𝓀[K]` (which would be
false: `𝓀[K]` has positive characteristic), only that `𝓀[K]` is perfect. -/
instance residueField_isGalois : IsGalois 𝓀[K] kbar := ⟨⟩

/-- The action of the decomposition subgroup (i.e., via `decompositionEquiv`, of all of `G_K`) on
`valuationSubringExtension K` induces an action on its residue field `kbar`, giving a
homomorphism `G_K →* RingAut kbar`. Its kernel is `inertiaSubgroup K` and its image is (all of,
though this is not recorded here) the Galois group `Gal(kbar/𝓀[K])`. -/
def residueAction : Field.absoluteGaloisGroup K →* RingAut kbar :=
  (MulSemiringAction.toRingAut
      (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)) kbar).comp
    (decompositionEquiv K).toMonoidHom

theorem residueAction_ker : (residueAction K).ker = inertiaSubgroup K := by
  ext x
  simp only [residueAction, inertiaSubgroup, MonoidHom.mem_ker, MonoidHom.coe_comp,
    Function.comp_apply, MulEquiv.coe_toMonoidHom, Subgroup.mem_map]
  constructor
  · intro hx
    exact ⟨decompositionEquiv K x, hx, rfl⟩
  · rintro ⟨y, hy, hxy⟩
    have hyx : decompositionEquiv K x = y := by
      apply Subtype.ext
      rw [← hxy]; rfl
    rwa [hyx]

/-! ### The profinite completion `ℤ̂` and Frobenius -/

/-- The profinite completion `ℤ̂` of `ℤ`, written multiplicatively (as the profinite completion,
in the sense of `ProfiniteGrp.ProfiniteCompletion`, of the multiplicative group `Multiplicative
ℤ`). This carries its `Group`, `TopologicalSpace`, and `IsTopologicalGroup` (in fact
`CompactSpace` and `TotallyDisconnectedSpace`) instances via the `CoeSort` on `ProfiniteGrp`. -/
abbrev Zhat : Type := ProfiniteGrp.ProfiniteCompletion.completion (GrpCat.of (Multiplicative ℤ))

/-- The canonical dense homomorphism `ℤ → ℤ̂` (written multiplicatively). -/
def toZhat : Multiplicative ℤ →* Zhat :=
  (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (Multiplicative ℤ))).hom

theorem denseRange_toZhat : DenseRange (toZhat) :=
  ProfiniteGrp.ProfiniteCompletion.denseRange (GrpCat.of (Multiplicative ℤ))

/-- `Multiplicative ℤ` is residually finite: given `g ≠ 1`, i.e. `n := g.toAdd ≠ 0`, reduction mod
any modulus exceeding `|n|` is a homomorphism to a finite group not killing `g`. This is what makes
`toZhat` injective (`toZhat_injective`), i.e. makes `ℤ̂` genuinely contain (a copy of) `ℤ`. -/
instance : Group.ResiduallyFinite (Multiplicative ℤ) := by
  apply Group.residuallyFinite_of_forall_exists_finite_monoidHom
  intro g hg
  set n : ℤ := g.toAdd with hn
  have hn0 : n ≠ 0 := fun h => hg (toAdd_eq_zero.mp h)
  refine ⟨Multiplicative (ZMod (n.natAbs + 1)), inferInstance, inferInstance,
    (Int.castAddHom (ZMod (n.natAbs + 1))).toMultiplicative, fun h => hn0 ?_⟩
  have h' : (n : ZMod (n.natAbs + 1)) = 0 := by
    simpa [AddMonoidHom.toMultiplicative, ← hn, toAdd_eq_zero] using h
  rw [ZMod.intCast_zmod_eq_zero_iff_dvd] at h'
  have h'' : ((n.natAbs + 1 : ℕ) : ℤ) ∣ (n.natAbs : ℤ) := Int.dvd_natAbs.mpr h'
  have hpos : (0 : ℤ) < (n.natAbs : ℤ) := by exact_mod_cast Int.natAbs_pos.mpr hn0
  have hle := Int.le_of_dvd hpos h''
  omega

/-- `toZhat` is injective: `ℤ` really does embed into its profinite completion `ℤ̂`. -/
theorem toZhat_injective : Function.Injective (toZhat) :=
  (ProfiniteGrp.ProfiniteCompletion.etaFn_injective_iff_residuallyFinite
    (GrpCat.of (Multiplicative ℤ))).mpr inferInstance

/-- The subgroup `ℤ ≤ ℤ̂` given by the (injective, by `toZhat_injective`) image of `toZhat`. -/
def integerSubgroup : Subgroup Zhat := (toZhat).range

/-- The isomorphism `ℤ ≃* integerSubgroup`, i.e. `ℤ ≤ ℤ̂` really is (a copy of) `ℤ` and not some
quotient of it, using injectivity of `toZhat`. -/
def integerSubgroupEquiv : Multiplicative ℤ ≃* integerSubgroup :=
  MonoidHom.ofInjective toZhat_injective

instance : Fintype 𝓀[K] := Fintype.ofFinite _

/-- The residue characteristic `p` of `𝓀[K]` (and, transported along `algebraMap 𝓀[K] kbar`, of
`kbar`). -/
def residueCharP : ℕ := ringChar 𝓀[K]

instance : CharP 𝓀[K] (residueCharP K) := ringChar.charP _

instance residueCharP_fact : Fact (residueCharP K).Prime :=
  ⟨CharP.char_is_prime 𝓀[K] _⟩

/-- The degree `n` of `𝓀[K]` over its prime field, i.e. `#𝓀[K] = p ^ n` (`card_residueField_eq`). -/
def residueDegree : ℕ+ := (FiniteField.card 𝓀[K] (residueCharP K)).choose

theorem card_residueField_eq :
    Fintype.card 𝓀[K] = (residueCharP K) ^ (residueDegree K : ℕ) :=
  (FiniteField.card 𝓀[K] (residueCharP K)).choose_spec.2

instance : CharP kbar (residueCharP K) :=
  charP_of_injective_algebraMap (algebraMap 𝓀[K] kbar).injective _

instance : ExpChar 𝓀[K] (residueCharP K) := .prime (residueCharP_fact K).out

instance : ExpChar kbar (residueCharP K) := .prime (residueCharP_fact K).out

/-- The (arithmetic) Frobenius automorphism `x ↦ x ^ #𝓀[K]` of `kbar`, generating (topologically)
the Galois group `Gal(kbar/𝓀[K])`. Well-definedness as a ring automorphism (as opposed to merely
an endomorphism) uses that `kbar` is algebraically closed, hence perfect
(`residueField_isAlgClosed`), so that the (injective, since `kbar` is a field) Frobenius
endomorphism is also surjective. -/
def frobenius : RingAut kbar :=
  haveI : PerfectField kbar := @IsAlgClosed.perfectField kbar _ (residueField_isAlgClosed K)
  haveI : PerfectRing kbar (residueCharP K) := PerfectField.toPerfectRing (residueCharP K)
  iterateFrobeniusEquiv kbar (residueCharP K) (residueDegree K : ℕ)

/-- Frobenius fixes `𝓀[K]` pointwise: elements of the residue field of `𝒪[K]` satisfy
`x ^ #𝓀[K] = x`, by Lagrange / Fermat's little theorem for the finite field `𝓀[K]`. -/
theorem frobenius_fixes (x : 𝓀[K]) :
    frobenius K (algebraMap 𝓀[K] kbar x) = algebraMap 𝓀[K] kbar x := by
  haveI : PerfectField kbar := @IsAlgClosed.perfectField kbar _ (residueField_isAlgClosed K)
  haveI : PerfectRing kbar (residueCharP K) := PerfectField.toPerfectRing (residueCharP K)
  show iterateFrobeniusEquiv kbar (residueCharP K) (residueDegree K : ℕ)
      (algebraMap 𝓀[K] kbar x) = algebraMap 𝓀[K] kbar x
  rw [iterateFrobeniusEquiv_def, ← map_pow, ← card_residueField_eq, FiniteField.pow_card]

/-! ### The isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` and the Weil group -/

/-- `residueAction` surjects onto (all of) `Gal(kbar/𝓀[K])`, i.e. `frobenius K` (which really is
an element of `Gal(kbar/𝓀[K])`, not just of `RingAut kbar`, by `frobenius_fixes` -- though
packaging that fact as membership in a `Gal(kbar/𝓀[K])`-as-subgroup-of-`RingAut kbar` is itself
not yet set up here) lies in the image of `G_K`. This is *not* a fact about finite fields at all
(unlike `exists_residueGaloisGroup_equiv_Zhat` below, whose remaining content specializes to
finite fields once this is granted): it is the genuinely local-field-theoretic input that, for a
Henselian complete field, the residue extension of an algebraic extension is again Galois with
Galois group a quotient of `G_K` -- concretely, that every automorphism of `kbar/𝓀[K]` lifts to an
automorphism of `K̄/K` stabilizing `valuationSubringExtension K` (this uses that unramified
extensions of `K` exist and are classified by, and lift automorphisms of, their residue
extensions -- a Hensel's-lemma-flavoured existence/lifting theorem, not merely a
statement about `Gal(K̄/K)`'s finite quotients). Mathlib's `InfiniteGalois.restrictNormalHom_surjective`
is surjectivity of a *different* map (restriction between two normal subextensions of one fixed
Galois extension) and does not apply: `residueAction` is not a restriction map, it is induced by
the (a priori unrelated) action on the residue field of `valuationSubringExtension K`. Not yet in
Mathlib, and not proved here. -/
theorem frobenius_mem_residueAction_range : frobenius K ∈ (residueAction K).range := by
  sorry

/-- The classical computation of the (profinite) absolute Galois group of a finite field: it is
topologically generated by Frobenius, and (as an abstract group) isomorphic to `ℤ̂`, via
`Multiplicative.ofAdd 1 ↦ frobenius K`. This is a deep theorem (not yet in Mathlib) about the
structure of `Gal(k̄/k)` for `k` finite; we record only the existence of *some* group isomorphism
with the stated behavior on Frobenius, as an abstract `MulEquiv` (i.e. we do not yet assert it is
a homeomorphism for the Krull topology on the left and the profinite topology on the right).

Ingredients now available in Mathlib towards this (none yet connected up into a full proof):
`kbar/𝓀[K]` is Galois (`residueField_isGalois`, added above from `IsAlgClosure.normal` +
`Algebra.IsAlgebraic.isSeparable_of_perfectField`); for every `n`, `Gal(GaloisField p (m*n) /
GaloisField p m)` is cyclic of order `n` generated by the Frobenius `FiniteField.Extension.frob`
(`FiniteField.Extension.natCard_algEquiv_extension`, `.exists_frob_pow_eq`, and
`FiniteField.exists_forall_apply_eq_pow` for the corresponding statement against an arbitrary
finite extension of `𝓀[K]`, all in `Mathlib.FieldTheory.Finite.Extension`); and `Zhat` satisfies
the universal property `ProfiniteGrp.ProfiniteCompletion.homEquiv` / `.lift` of the profinite
completion of `ℤ` (`Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion`). What is missing to
assemble these into the isomorphism: (1) packaging `Gal(kbar/𝓀[K])` (equivalently, via
`frobenius_mem_residueAction_range` and `residueAction_ker`, `(residueAction K).range`) as an
object of the `ProfiniteGrp` category compatible with its Krull topology, and (2) identifying its
open normal subgroups with exactly the kernels of restriction to the finite subfields
`GaloisField p (m*n) ≤ kbar`, matched up (via `finrank_zmod_extension`-style bookkeeping on
degrees) with the finite-index-normal-subgroup diagram `n ↦ ℤ ⧸ nℤ` defining `Zhat`; only then does
`ProfiniteGrp.ProfiniteCompletion.lift` applied to `Multiplicative ℤ →* (residueAction K).range`,
`1 ↦ ⟨frobenius K, frobenius_mem_residueAction_range K⟩` become the desired isomorphism (rather
than merely *a* continuous homomorphism `Zhat → (residueAction K).range`, whose bijectivity is the
real remaining content). -/
theorem exists_residueGaloisGroup_equiv_Zhat :
    ∃ e : (residueAction K).range ≃* Zhat,
      e ⟨frobenius K, frobenius_mem_residueAction_range K⟩ = toZhat (Multiplicative.ofAdd 1) := by
  sorry

/-- A fixed choice of isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` from
`exists_residueGaloisGroup_equiv_Zhat`, identifying the image of `residueAction K` (i.e. the
Galois group of the residue field extension) with the profinite completion of `ℤ`. -/
def residueGaloisGroupEquivZhat : (residueAction K).range ≃* Zhat :=
  (exists_residueGaloisGroup_equiv_Zhat K).choose

/-- The composite homomorphism `G_K →* ℤ̂` sending `σ` to the (profinite) power of Frobenius that
`σ` induces on the residue field. -/
def toZhatHom : Field.absoluteGaloisGroup K →* Zhat :=
  (residueGaloisGroupEquivZhat K).toMonoidHom.comp (residueAction K).rangeRestrict

/-- The **Weil group** `W_K` of `K`: the subgroup of `σ ∈ G_K` inducing an *integer* power of
Frobenius on the residue field, i.e. the preimage of `ℤ ≤ ℤ̂` (`integerSubgroup`) under
`toZhatHom`. -/
def WeilGroup : Subgroup (Field.absoluteGaloisGroup K) :=
  Subgroup.comap (toZhatHom K) (integerSubgroup)

/-- The inertia subgroup is contained in the Weil group (it maps to `1 ∈ ℤ ≤ ℤ̂`). -/
theorem inertiaSubgroup_le_weilGroup : inertiaSubgroup K ≤ WeilGroup K := by
  rw [← residueAction_ker]
  intro x hx
  rw [MonoidHom.mem_ker] at hx
  simp only [WeilGroup, Subgroup.mem_comap, toZhatHom, MonoidHom.coe_comp, Function.comp_apply]
  rw [show (residueAction K).rangeRestrict x = 1 from Subtype.ext hx, map_one]
  exact Subgroup.one_mem _

/-- `inertiaSubgroup K` is normal in `G_K`: it is (via `residueAction_ker`) the kernel of
`residueAction K`, and kernels of group homomorphisms are always normal. -/
instance inertiaSubgroup_normal : (inertiaSubgroup K).Normal := by
  rw [← residueAction_ker]; infer_instance

/-- The **Artin map** (or "art" map, or valuation map) `W_K →* ℤ`: every `σ ∈ W_K` induces an
*integer* power of Frobenius on the residue field (by definition of `WeilGroup`), and this is that
integer, packaged via the isomorphism `ℤ ≃* integerSubgroup` (`integerSubgroupEquiv`). Its kernel
is `I_K` (`toArt_ker`). -/
def toArt : WeilGroup K →* Multiplicative ℤ :=
  integerSubgroupEquiv.symm.toMonoidHom.comp
    (((toZhatHom K).restrict (WeilGroup K)).codRestrict integerSubgroup
      fun w => Subgroup.mem_comap.mp w.2)

/-- The kernel of `toZhatHom` is `I_K`: `σ` induces the trivial power of Frobenius iff it acts
trivially on the residue field, i.e. lies in the kernel of `residueAction` (which is `I_K` by
`residueAction_ker`). -/
theorem toZhatHom_ker : (toZhatHom K).ker = inertiaSubgroup K := by
  unfold toZhatHom
  rw [MonoidHom.ker_comp_of_injective _ _ (residueGaloisGroupEquivZhat K).injective,
    MonoidHom.ker_rangeRestrict, residueAction_ker]

theorem toArt_ker : (toArt K).ker = (inertiaSubgroup K).subgroupOf (WeilGroup K) := by
  unfold toArt
  rw [MonoidHom.ker_comp_of_injective _ _ integerSubgroupEquiv.symm.injective,
    MonoidHom.ker_codRestrict, MonoidHom.ker_restrict, toZhatHom_ker]

/-! ### The topology on `W_K` -/

/-- The "basic neighborhood of `1`" subgroup of `W_K` associated to an open subgroup `U` of `G_K`:
elements of `W_K` lying in both `U` and the inertia subgroup. As `U` ranges over open subgroups of
`G_K`, these form a filter basis at `1` for the topology on `W_K` (`WeilGroup.groupFilterBasis`)
making `I_K` open -- *not* the subspace topology from `G_K`, under which `I_K` is not open since
`⟨Frob⟩ ≅ ℤ` is dense in `Gal(kbar/𝓀[K]) ≅ ℤ̂`. -/
def basicSubgroup (U : OpenSubgroup (Field.absoluteGaloisGroup K)) : Subgroup (WeilGroup K) :=
  (U.toSubgroup ⊓ inertiaSubgroup K).subgroupOf (WeilGroup K)

/-- The `GroupFilterBasis` on `W_K` whose basic neighborhoods of `1` are `basicSubgroup K U` for
`U` an open subgroup of `G_K`. This realizes the topology described in the module docstring:
`I_K = basicSubgroup K ⊤` is open, and multiplication/inversion/conjugation are continuous because
they already are in `G_K` (whose topology `I_K`'s basic neighborhoods are built from). -/
@[implicit_reducible]
def groupFilterBasis : GroupFilterBasis (WeilGroup K) where
  sets := Set.range fun U : OpenSubgroup (Field.absoluteGaloisGroup K) =>
    (basicSubgroup K U : Set (WeilGroup K))
  nonempty := Set.range_nonempty _
  inter_sets := by
    rintro _ _ ⟨U, rfl⟩ ⟨V, rfl⟩
    refine ⟨_, Set.mem_range_self (⟨U.toSubgroup ⊓ V.toSubgroup, U.isOpen.inter V.isOpen⟩ :
      OpenSubgroup (Field.absoluteGaloisGroup K)), fun w hw => ?_⟩
    simp only [basicSubgroup, SetLike.mem_coe, Subgroup.mem_subgroupOf, Subgroup.mem_inf,
      OpenSubgroup.mem_toSubgroup, Set.mem_inter_iff] at hw ⊢
    tauto
  one' := by rintro _ ⟨U, rfl⟩; exact (basicSubgroup K U).one_mem
  mul' := by
    rintro _ ⟨U, rfl⟩
    exact ⟨_, Set.mem_range_self U, fun w ⟨a, ha, b, hb, hab⟩ => hab ▸ Subgroup.mul_mem _ ha hb⟩
  inv' := by
    rintro _ ⟨U, rfl⟩
    exact ⟨_, Set.mem_range_self U, fun w hw => Subgroup.inv_mem _ hw⟩
  conj' := by
    rintro x₀ _ ⟨U, rfl⟩
    refine ⟨_, Set.mem_range_self (U.comap (MulAut.conj (x₀ : Field.absoluteGaloisGroup K)).toMonoidHom
      (IsTopologicalGroup.continuous_conj _)), fun w hw => ?_⟩
    simp only [Set.mem_preimage, basicSubgroup, SetLike.mem_coe, Subgroup.mem_subgroupOf,
      Subgroup.mem_inf] at hw ⊢
    have hcoe : ((x₀ * w * x₀⁻¹ : WeilGroup K) : Field.absoluteGaloisGroup K) =
        (x₀ : Field.absoluteGaloisGroup K) * (w : Field.absoluteGaloisGroup K) *
          (x₀ : Field.absoluteGaloisGroup K)⁻¹ := by
      simp [Subgroup.coe_mul]
    rw [hcoe]
    refine ⟨?_, (inertiaSubgroup_normal K).conj_mem _ hw.2 _⟩
    simpa [OpenSubgroup.mem_comap, MulAut.conj_apply] using hw.1

/-- The topology on `W_K` making `I_K` an open subgroup, transported from `G_K`'s Krull topology
along the filter basis `groupFilterBasis`. This is the topology described in the module docstring,
*not* the subspace topology `W_K` would inherit directly from `G_K`. -/
instance instTopologicalSpace : TopologicalSpace (WeilGroup K) := (groupFilterBasis K).topology

/-- `W_K`, with the topology `instTopologicalSpace`, is a topological group. -/
instance instIsTopologicalGroup : IsTopologicalGroup (WeilGroup K) :=
  (groupFilterBasis K).isTopologicalGroup

/-- `I_K` (viewed as a subgroup of `W_K`) is open in `W_K`'s topology: this is the defining feature
of the Weil group topology, distinguishing it from the subspace topology from `G_K`. -/
theorem isOpen_inertiaSubgroupOf :
    IsOpen ((inertiaSubgroup K).subgroupOf (WeilGroup K) : Set (WeilGroup K)) := by
  have hmem : ((inertiaSubgroup K).subgroupOf (WeilGroup K) : Set (WeilGroup K)) ∈
      groupFilterBasis K := ⟨⊤, by simp [basicSubgroup, OpenSubgroup.toSubgroup_top]⟩
  exact Subgroup.isOpen_of_mem_nhds _ ((groupFilterBasis K).mem_nhds_one hmem)

/-- The quotient `W_K / I_K` is discrete: since `I_K` is open (`isOpen_inertiaSubgroupOf`), its
cosets partition `W_K` into open sets, so the quotient topology is discrete. Combined with
`toArt_ker`, this says the induced map `W_K / I_K → ℤ` (an isomorphism, via `toArt`) matches the
discrete topology on `ℤ` against the quotient topology on `W_K / I_K`. -/
theorem discreteTopology_quotient_inertiaSubgroupOf :
    DiscreteTopology (WeilGroup K ⧸ (inertiaSubgroup K).subgroupOf (WeilGroup K)) :=
  QuotientGroup.discreteTopology (isOpen_inertiaSubgroupOf K)

end LocalField
