import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.NumberTheory.LocalField.Basic
import Mathlib.RingTheory.Valuation.RamificationGroup
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion

/-!
# The Weil group of a nonarchimedean local field

Let `K` be a nonarchimedean local field, with ring of integers `𝒪[K]`, maximal ideal `𝓂[K]`
and (finite) residue field `𝓀[K]`. Let `K̄` be an algebraic closure of `K` and
`G_K = Gal(K̄/K) = Field.absoluteGaloisGroup K` its absolute Galois group.

Choosing a valuation subring `𝒪[K̄]` of `K̄` extending `𝒪[K]` (Chevalley's extension theorem;
unique up to `G_K`-conjugacy, and since `K` is complete, in fact the *decomposition subgroup* of
`𝒪[K̄]` -- the stabilizer of `𝒪[K̄]` inside `G_K` -- is all of `G_K`), we get:

* a residue field `𝓀[K̄] := IsLocalRing.ResidueField 𝒪[K̄]`, an algebraic closure of `𝓀[K]`;
* the *inertia subgroup* `I_K ≤ G_K`, the kernel of the induced action of `G_K` on `𝓀[K̄]`;
* the induced action `ρ : G_K →* RingAut 𝓀[K̄]`, whose image is (all of) the profinite Galois
  group `Gal(𝓀[K̄]/𝓀[K])`, generated topologically by the (arithmetic) Frobenius
  `x ↦ x ^ #𝓀[K]` and abstractly isomorphic to `ℤ̂`, the profinite completion of `ℤ`.

This gives the exact sequence `1 → I_K → G_K → Gal(𝓀[K̄]/𝓀[K]) → 1`, and, transporting along
the (highly nontrivial, and currently `sorry`-ed) isomorphism `Gal(𝓀[K̄]/𝓀[K]) ≃ ℤ̂`, a
homomorphism `G_K →* ℤ̂` whose kernel is `I_K`.

The **Weil group** `W_K` is defined as the preimage of the copy of `ℤ` inside `ℤ̂` (the image of
`ℤ̂`'s canonical dense map `ℤ → ℤ̂`) under this homomorphism. Equivalently, `W_K` is the subgroup
of `σ ∈ G_K` whose image in `Gal(𝓀[K̄]/𝓀[K])` is an *integer* power of Frobenius (as opposed to
an arbitrary element of the profinite closure `ℤ̂` of the subgroup generated by Frobenius).

`W_K` is given the topology making `I_K` an *open* subgroup of `W_K` (with its subspace/profinite
topology from `G_K`), rather than the subspace topology from `G_K` -- under the latter, `I_K`
would still be closed but not open, since `⟨Frob⟩ ≅ ℤ` sits densely inside `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂`.
Concretely: `W_K ≅ I_K ⋊ ℤ` as topological groups, where `ℤ` is discrete and `I_K` carries its
profinite topology, and the topology on `W_K` is the one transported along this splitting.

## Main definitions

* `LocalField.valuationSubringExtension K` : a choice of valuation subring `𝒪[K̄]` of (a fixed
  algebraic closure of) `K` extending `𝒪[K]`.
* `LocalField.decompositionSubgroup_eq_top` : the decomposition subgroup of
  `valuationSubringExtension K` is all of `G_K` (uses completeness of `K`).
* `LocalField.inertiaSubgroup K` : the inertia subgroup `I_K ≤ G_K`, transported along
  `decompositionSubgroup_eq_top` from `ValuationSubring.inertiaSubgroup`.
* `LocalField.residueAction K` : the homomorphism `G_K →* RingAut 𝓀[K̄]` induced by the action
  on the residue field, with kernel `I_K`.
* `LocalField.Zhat` : the profinite completion `ℤ̂` of `ℤ` (as a profinite group, multiplicatively
  written), built from Mathlib's general categorical profinite completion of groups.
* `LocalField.frobenius K` : the arithmetic Frobenius `x ↦ x ^ #𝓀[K]` on `𝓀[K̄]`, as an element
  of `RingAut 𝓀[K̄]`.
* `LocalField.residueGaloisGroup_equiv_Zhat` : the (`sorry`-ed) isomorphism identifying the image
  of `residueAction K` with `ℤ̂`, sending Frobenius to (the image of) `1`.
* `LocalField.WeilGroup K` : the Weil group `W_K ≤ G_K`, the preimage of `ℤ ≤ ℤ̂` under (the
  composite of `residueAction K` with) `residueGaloisGroup_equiv_Zhat`.
* `LocalField.WeilGroup.topologicalSpace` : the topology on `W_K` making `I_K` open, built by
  transporting the product topology on `I_K × ℤ` (with `ℤ` discrete) along the (`sorry`-ed)
  splitting `W_K ≃ I_K × ℤ`.

## Implementation notes

Several ingredients used here are genuinely deep theorems that are not (yet) in Mathlib, and are
recorded as `sorry`s rather than proved:

* `exists_valuationSubring_extends` : Chevalley's theorem that every valuation on a field extends
  to any algebraic (or indeed arbitrary) field extension.
* `decompositionSubgroup_eq_top` : uniqueness of the extension of the valuation of a complete
  (Henselian) field to an algebraic extension.
* `residueField_isAlgClosed` / `residueField_isAlgebraic` : the residue field of `𝒪[K̄]` is an
  algebraic closure of `𝓀[K]`.
* `residueGaloisGroup_equiv_Zhat` : the identification `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂` via Frobenius, i.e.
  the classical computation of the absolute Galois group of a finite field. This is stated as an
  abstract group isomorphism sending Frobenius to `1`; upgrading it to a homeomorphism (matching
  the Krull topology on the left against the profinite topology on the right) is left for later.
* `WeilGroup.splitting` : the (set-theoretic, not just group-theoretic) splitting
  `W_K ≃ I_K × ℤ` used to transport the topology onto `W_K`.

None of these are needed for the *definitions* of `inertiaSubgroup`, `residueAction`, `Zhat`,
`frobenius`, or `WeilGroup` themselves to typecheck; they are only needed for the expected
*properties* of these objects (e.g. that `I_K` really is the kernel of `G_K → Gal(k̄/k)`, that
`Zhat` really is (topologically) generated by the image of `1`, etc.), which is why the
definitions are considered the primary deliverable of this file.

## References
* J-P. Serre, *Local Fields*, chapter XII (definition of the Weil group).
* J. Tate, *Number theoretic background*, §1, in *Automorphic forms, representations, and
  L-functions* (Corvallis proceedings).
-/

noncomputable section

open ValuativeRel Valuation IsLocalRing CategoryTheory

namespace LocalField

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- A fixed algebraic closure of `K`. -/
local notation "L" => AlgebraicClosure K

/-! ### The valuation subring of `K̄` extending `𝒪[K]` -/

/-- **Chevalley's extension theorem** (not yet in Mathlib): every valuation on a field extends to
an algebraic closure. We record the existence of a valuation subring of `L = AlgebraicClosure K`
lying over `𝒪[K] = (valuation K).valuationSubring` as a `sorry`-ed fact, and fix a choice of such
an extension via `valuationSubringExtension`. -/
theorem exists_valuationSubring_extends :
    ∃ A : ValuationSubring L, A.comap (algebraMap K L) = (valuation K).valuationSubring := by
  sorry

/-- A choice of valuation subring of `L = AlgebraicClosure K` extending `𝒪[K]`, i.e. "the" ring
of integers `𝒪[K̄]` of the algebraic closure (for our fixed choice of extended valuation). -/
def valuationSubringExtension : ValuationSubring L :=
  (exists_valuationSubring_extends K).choose

@[simp]
theorem valuationSubringExtension_comap :
    (valuationSubringExtension K).comap (algebraMap K L) = (valuation K).valuationSubring :=
  (exists_valuationSubring_extends K).choose_spec

/-! ### The decomposition subgroup is everything -/

/-- Since `K` is complete (hence Henselian), the valuation on `K` extends *uniquely* (up to
equivalence) to any algebraic extension of `K`, so every automorphism of `K̄` over `K` stabilizes
`valuationSubringExtension K`. Equivalently: the decomposition subgroup of
`valuationSubringExtension K` is all of `G_K`. This is a standard fact about Henselian valued
fields, not yet in Mathlib. -/
theorem decompositionSubgroup_eq_top :
    ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) = ⊤ := by
  sorry

/-- The canonical isomorphism `G_K ≃* (decomposition subgroup of `𝒪[K̄]`)`, using
`decompositionSubgroup_eq_top`. -/
def decompositionEquiv :
    Field.absoluteGaloisGroup K ≃*
      ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) :=
  (Subgroup.topEquiv (G := Field.absoluteGaloisGroup K)).symm.trans
    (MulEquiv.subgroupCongr (decompositionSubgroup_eq_top K).symm)

/-! ### The inertia subgroup -/

/-- The inertia subgroup `I_K ≤ G_K`: the kernel of the action of `G_K` on the residue field of
`valuationSubringExtension K`, transported from `ValuationSubring.inertiaSubgroup` along the fact
that the decomposition subgroup of `valuationSubringExtension K` is everything
(`decompositionSubgroup_eq_top`). -/
def inertiaSubgroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (ValuationSubring.inertiaSubgroup K (valuationSubringExtension K)).map
    (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)).subtype

/-! ### The residue field extension and the induced Galois action -/

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄] = valuationSubringExtension K`, i.e. the restriction of
`algebraMap K L` to rings of integers; well-defined by `valuationSubringExtension_comap`. -/
def integersAlgebraMap : ↥(𝒪[K]) →+* valuationSubringExtension K :=
  ((algebraMap K L).comp (𝒪[K]).subtype).codRestrict _ fun x => by
    have hx : (x : K) ∈ (valuation K).valuationSubring :=
      (Valuation.mem_valuationSubring_iff _ _).mpr ((Valuation.mem_integer_iff _ _).mp x.2)
    rw [← valuationSubringExtension_comap K] at hx
    exact (ValuationSubring.mem_comap).mp hx

instance : Algebra ↥(𝒪[K]) (valuationSubringExtension K) := (integersAlgebraMap K).toAlgebra

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄]` is a local homomorphism: since both are valuation subrings and
the inclusion is the restriction of the (injective, field-valued) map `algebraMap K L` compatible
with the valuations, it reflects units. Not yet proved here. -/
instance : IsLocalHom (algebraMap ↥(𝒪[K]) (valuationSubringExtension K)) := by
  sorry

/-- The residue field of the algebraic-closure integers `valuationSubringExtension K`: this is
(a `sorry`-ed fact away from being, via `residueField_isAlgClosed` / `residueField_isAlgebraic`)
an algebraic closure `𝓀[K]bar` of the (finite) residue field `𝓀[K]`. -/
local notation "kbar" => IsLocalRing.ResidueField (valuationSubringExtension K)

/-- The residue field `kbar` of `valuationSubringExtension K` is algebraically closed. This
reflects the general fact that the residue field of a valuation ring inside an algebraically
closed field is algebraically closed; not yet in Mathlib. -/
theorem residueField_isAlgClosed : IsAlgClosed kbar := by
  sorry

/-- The residue field `kbar` of `valuationSubringExtension K` is algebraic over `𝓀[K]`. -/
theorem residueField_isAlgebraic : Algebra.IsAlgebraic 𝓀[K] kbar := by
  sorry

/-- The action of the decomposition subgroup (i.e., via `decompositionEquiv`, of all of `G_K`) on
`valuationSubringExtension K` induces an action on its residue field `kbar`, giving a
homomorphism `G_K →* RingAut kbar`. Its kernel is `inertiaSubgroup K` and its image is (all of,
though this is not recorded here) the Galois group `Gal(kbar/𝓀[K])`. -/
def residueAction : Field.absoluteGaloisGroup K →* RingAut kbar :=
  (MulSemiringAction.toRingAut
      (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)) kbar).comp
    (decompositionEquiv K).toMonoidHom

theorem residueAction_ker : (residueAction K).ker = inertiaSubgroup K := by
  sorry

/-! ### The profinite completion `ℤ̂` and Frobenius -/

/-- The profinite completion `ℤ̂` of `ℤ`, written multiplicatively (as the profinite completion,
in the sense of `ProfiniteGrp.ProfiniteCompletion`, of the multiplicative group `Multiplicative
ℤ`). This carries its `Group`, `TopologicalSpace`, and `IsTopologicalGroup` (in fact
`CompactSpace` and `TotallyDisconnectedSpace`) instances via the `CoeSort` on `ProfiniteGrp`. -/
abbrev Zhat : Type := ProfiniteGrp.ProfiniteCompletion.completion (GrpCat.of (Multiplicative ℤ))

/-- The canonical dense homomorphism `ℤ → ℤ̂` (written multiplicatively). -/
def toZhat : Multiplicative ℤ →* Zhat :=
  (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (Multiplicative ℤ))).hom

theorem denseRange_toZhat : DenseRange (toZhat) :=
  ProfiniteGrp.ProfiniteCompletion.denseRange (GrpCat.of (Multiplicative ℤ))

/-- The subgroup `ℤ ≤ ℤ̂` given by the (injective, since `ℤ̂` is `sorry`-ed to be its profinite
completion faithfully) image of `toZhat`. -/
def integerSubgroup : Subgroup Zhat := (toZhat).range

/-- The (arithmetic) Frobenius automorphism `x ↦ x ^ #𝓀[K]` of `kbar`, generating (topologically)
the Galois group `Gal(kbar/𝓀[K])`. Well-definedness as a ring automorphism (as opposed to merely
an endomorphism) uses that `kbar` is algebraically closed, hence perfect
(`residueField_isAlgClosed`), so that the (injective, since `kbar` is a field) Frobenius
endomorphism is also surjective. -/
def frobenius : RingAut kbar := by
  sorry

/-- Frobenius fixes `𝓀[K]` pointwise: elements of the residue field of `𝒪[K]` satisfy
`x ^ #𝓀[K] = x`, by Lagrange / Fermat's little theorem for the finite field `𝓀[K]`. -/
theorem frobenius_fixes (x : 𝓀[K]) :
    frobenius K (algebraMap 𝓀[K] kbar x) = algebraMap 𝓀[K] kbar x := by
  sorry

/-! ### The isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` and the Weil group -/

/-- The classical computation of the (profinite) absolute Galois group of a finite field: it is
topologically generated by Frobenius, and (as an abstract group) isomorphic to `ℤ̂`, via
`Multiplicative.ofAdd 1 ↦ frobenius K`. This is a deep theorem (not yet in Mathlib) about the
structure of `Gal(k̄/k)` for `k` finite; we record only the existence of *some* group isomorphism
with the stated behavior on Frobenius, as an abstract `MulEquiv` (i.e. we do not yet assert it is
a homeomorphism for the Krull topology on the left and the profinite topology on the right). -/
theorem exists_residueGaloisGroup_equiv_Zhat :
    ∃ e : (residueAction K).range ≃* Zhat,
      e ⟨frobenius K, (residueAction K).mem_range.mpr sorry⟩ = toZhat (Multiplicative.ofAdd 1) := by
  sorry

/-- A fixed choice of isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` from
`exists_residueGaloisGroup_equiv_Zhat`, identifying the image of `residueAction K` (i.e. the
Galois group of the residue field extension) with the profinite completion of `ℤ`. -/
def residueGaloisGroupEquivZhat : (residueAction K).range ≃* Zhat :=
  (exists_residueGaloisGroup_equiv_Zhat K).choose

/-- The composite homomorphism `G_K →* ℤ̂` sending `σ` to the (profinite) power of Frobenius that
`σ` induces on the residue field. -/
def toZhatHom : Field.absoluteGaloisGroup K →* Zhat :=
  (residueGaloisGroupEquivZhat K).toMonoidHom.comp (residueAction K).rangeRestrict

/-- The **Weil group** `W_K` of `K`: the subgroup of `σ ∈ G_K` inducing an *integer* power of
Frobenius on the residue field, i.e. the preimage of `ℤ ≤ ℤ̂` (`integerSubgroup`) under
`toZhatHom`. -/
def WeilGroup : Subgroup (Field.absoluteGaloisGroup K) :=
  Subgroup.comap (toZhatHom K) (integerSubgroup)

/-- The inertia subgroup is contained in the Weil group (it maps to `1 ∈ ℤ ≤ ℤ̂`). -/
theorem inertiaSubgroup_le_weilGroup : inertiaSubgroup K ≤ WeilGroup K := by
  sorry

end LocalField
