import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.NumberTheory.LocalField.Basic
import Mathlib.RingTheory.Valuation.RamificationGroup
import Mathlib.RingTheory.Valuation.Extension
import Mathlib.RingTheory.Valuation.LocalSubring
import Langlands.CyclicGaloisSubfields
import Langlands.HenselianValuation
import Langlands.ResidueField
import Langlands.UnramifiedExtension
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.FieldTheory.Finite.Extension
import Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion
import Mathlib.FieldTheory.IsSepClosed
import Mathlib.FieldTheory.PurelyInseparable.Basic
import Mathlib.FieldTheory.Galois.Profinite
import Mathlib.Algebra.CharP.Reduced

/-!
# The Weil group of a nonarchimedean local field

Let `K` be a nonarchimedean local field, with ring of integers `𝒪[K]`, maximal ideal `𝓂[K]`
and (finite) residue field `𝓀[K]`. Let `K̄` be an algebraic closure of `K` and
`G_K = Gal(K̄/K) = Field.absoluteGaloisGroup K` its absolute Galois group.

Choosing a valuation subring `𝒪[K̄]` of `K̄` extending `𝒪[K]` (Chevalley's extension theorem;
unique up to `G_K`-conjugacy, and since `K` is complete, in fact the *decomposition subgroup* of
`𝒪[K̄]` -- the stabilizer of `𝒪[K̄]` inside `G_K` -- is all of `G_K`), we get:

* a residue field `𝓀[K̄] := IsLocalRing.ResidueField 𝒪[K̄]`, an algebraic closure of `𝓀[K]`;
* the *inertia subgroup* `I_K ≤ G_K`, the kernel of the induced action of `G_K` on `𝓀[K̄]`;
* the induced action `ρ : G_K →* RingAut 𝓀[K̄]`, whose image is (all of) the profinite Galois
  group `Gal(𝓀[K̄]/𝓀[K])`, generated topologically by the (arithmetic) Frobenius
  `x ↦ x ^ #𝓀[K]` and abstractly isomorphic to `ℤ̂`, the profinite completion of `ℤ`.

This gives the exact sequence `1 → I_K → G_K → Gal(𝓀[K̄]/𝓀[K]) → 1`, and, transporting along
the (highly nontrivial, and currently `sorry`-ed) isomorphism `Gal(𝓀[K̄]/𝓀[K]) ≃ ℤ̂`, a
homomorphism `G_K →* ℤ̂` whose kernel is `I_K`.

The **Weil group** `W_K` is defined as the preimage of the copy of `ℤ` inside `ℤ̂` (the image of
`ℤ̂`'s canonical dense map `ℤ → ℤ̂`) under this homomorphism. Equivalently, `W_K` is the subgroup
of `σ ∈ G_K` whose image in `Gal(𝓀[K̄]/𝓀[K])` is an *integer* power of Frobenius (as opposed to
an arbitrary element of the profinite closure `ℤ̂` of the subgroup generated by Frobenius).

`W_K` is given the topology making `I_K` an *open* subgroup of `W_K` (with its subspace/profinite
topology from `G_K`), rather than the subspace topology from `G_K` -- under the latter, `I_K`
would still be closed but not open, since `⟨Frob⟩ ≅ ℤ` sits densely inside `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂`.
Concretely: `W_K ≅ I_K ⋊ ℤ` as topological groups, where `ℤ` is discrete and `I_K` carries its
profinite topology. Rather than building this topology by transporting the product topology along
a set-theoretic splitting `W_K ≃ I_K × ℤ`, we build it directly as a `GroupFilterBasis` (see
`WeilGroup.groupFilterBasis`) whose basic neighborhoods of `1` are the intersections of `I_K` with
(the restriction to `W_K` of) open subgroups of `G_K` -- this makes `I_K` open by construction,
without needing the splitting itself, and continuity of multiplication/inversion/conjugation
follows directly from the fact that they already hold in `G_K`. The projection `W_K →* ℤ`
(`WeilGroup.toArt`, the local Artin/"art" map) is defined directly from `toZhatHom`, with kernel
`I_K` (`WeilGroup.toArt_ker`); it is *not* yet shown to be continuous for this topology (nor is
the fully set-theoretic splitting `W_K ≃ I_K × ℤ` constructed), which is left for later.

## Main definitions

* `LocalField.valuationSubringExtension K` : a choice of valuation subring `𝒪[K̄]` of (a fixed
  algebraic closure of) `K` extending `𝒪[K]`.
* `LocalField.decompositionSubgroup_eq_top` : the decomposition subgroup of
  `valuationSubringExtension K` is all of `G_K` (uses completeness of `K`).
* `LocalField.inertiaSubgroup K` : the inertia subgroup `I_K ≤ G_K`, transported along
  `decompositionSubgroup_eq_top` from `ValuationSubring.inertiaSubgroup`.
* `LocalField.residueAction K` : the homomorphism `G_K →* RingAut 𝓀[K̄]` induced by the action
  on the residue field, with kernel `I_K`.
* `LocalField.Zhat` : the profinite completion `ℤ̂` of `ℤ` (as a profinite group, multiplicatively
  written), built from Mathlib's general categorical profinite completion of groups.
* `LocalField.frobenius K` : the arithmetic Frobenius `x ↦ x ^ #𝓀[K]` on `𝓀[K̄]`, as an element
  of `RingAut 𝓀[K̄]`.
* `LocalField.frobeniusAlgEquiv K` : `frobenius K` repackaged as a genuine element of
  `Gal(𝓀[K̄]/𝓀[K])`, i.e. of `𝓀[K̄] ≃ₐ[𝓀[K]] 𝓀[K̄]`.
* `LocalField.exists_frobenius_pow_eq` : every automorphism of a *finite* subextension of
  `𝓀[K̄]/𝓀[K]` is a power of the finite-field Frobenius `x ↦ x ^ #𝓀[K]`, via
  `FiniteField.exists_forall_apply_eq_pow`.
* `LocalField.residueGaloisGroup_equiv_Zhat` : the (`sorry`-ed) isomorphism identifying the image
  of `residueAction K` with `ℤ̂`, sending Frobenius to (the image of) `1`.
* `LocalField.WeilGroup K` : the Weil group `W_K ≤ G_K`, the preimage of `ℤ ≤ ℤ̂` under (the
  composite of `residueAction K` with) `residueGaloisGroup_equiv_Zhat`.
* `LocalField.toZhat_injective` : `toZhat : ℤ → ℤ̂` is injective (`ℤ` is residually finite), so
  `ℤ ≤ ℤ̂` (`integerSubgroup`) really is (a copy of) `ℤ` (`integerSubgroupEquiv`).
* `LocalField.WeilGroup.toArt` : the Artin ("art") map `W_K →* ℤ`, with kernel `I_K`
  (`WeilGroup.toArt_ker`).
* `LocalField.WeilGroup.groupFilterBasis` : the `GroupFilterBasis` on `W_K` making `I_K` open,
  whose basic neighborhoods of `1` are intersections of `I_K` with open subgroups of `G_K`.
* `LocalField.WeilGroup.instTopologicalSpace` / `instIsTopologicalGroup` : the resulting topology
  on `W_K` and the fact that it makes `W_K` a topological group.
* `LocalField.WeilGroup.isOpen_inertiaSubgroupOf` : `I_K` is open in `W_K` for this topology.

## Implementation notes

Several ingredients used here are genuinely deep theorems that are not (yet) in Mathlib, and are
recorded as `sorry`s rather than proved:

* `exists_valuationSubring_extends` : Chevalley's theorem that every valuation on a field extends
  to any algebraic (or indeed arbitrary) field extension.
* `decompositionSubgroup_eq_top` : uniqueness of the extension of the valuation of a complete
  (Henselian) field to an algebraic extension. Unlike the other four items in this list,
  `decompositionSubgroup_eq_top` itself is *not* `sorry`-ed: it is proved from
  `LocalField.valuationSubring_eq_of_comap_eq` (in `Langlands.HenselianValuation`), a real theorem
  built on Mathlib's `spectralNorm_unique_field_norm_ext`. That file's own remaining gap,
  `LocalField.exists_rankOne_absoluteValue_extends` (bridging the `ValuationSubring`/`ValuativeRel`
  formalism used here with the `NormedField`/`AbsoluteValue` formalism
  `spectralNorm_unique_field_norm_ext` needs: rank preservation of a valuation under an algebraic
  extension, and compatible normalization of the extended rank-one embedding into `ℝ≥0`), is now
  **fully proved, no `sorry`** — closed via the two general-purpose lemmas
  `Valuation.exists_pow_eq_of_isAlgebraic` and `Valuation.exists_rpow_eq_of_isEquiv` (see that
  file's module docstring for details). So this item, too, has no remaining `sorry` anywhere in its
  dependency chain.
* `frobenius_mem_residueAction_range` : `residueAction` surjects onto `Gal(𝓀[K̄]/𝓀[K])`, i.e.
  `frobenius K` lies in `(residueAction K).range`. **Now proved outright** from three more
  precisely-scoped facts (no direct `sorry` on this theorem itself):
  `ValuationSubring.exists_restrictNormalHom_decompositionSubgroup_surjective`
  (`Langlands.UnramifiedExtension` -- the genuinely local-field-theoretic, Hensel's-lemma-flavoured
  unramified lifting theorem: every automorphism of a finite Galois subextension of `𝓀[K̄]/𝓀[K]`
  lifts to an automorphism of `K̄/K` stabilizing `valuationSubringExtension K`; not a consequence
  of Mathlib's `InfiniteGalois.restrictNormalHom_surjective`, which is surjectivity of a different
  map), `compactSpace_absoluteGaloisGroup` (`G_K` is profinite -- true in general via `Gal(K̄/K) ≅
  Gal(K_sep/K)`, but not yet bridged to Mathlib's `IsGalois`-gated `CompactSpace` instance), and
  `continuous_residueAction'` (continuity of the residue action for the two Krull topologies
  involved). The formal glue combining these three (via the Galois correspondence for
  `Gal(𝓀[K̄]/𝓀[K])`, `InfiniteGalois.restrict_fixedField` / `fixingSubgroup_fixedField`) is real,
  checked Lean code, not `sorry`-ed.
* `exists_residueGaloisGroup_equiv_Zhat` : the identification `Gal(𝓀[K̄]/𝓀[K]) ≅ ℤ̂` via Frobenius,
  i.e. the classical computation of the absolute Galois group of a finite field. This is stated as
  an abstract group isomorphism sending Frobenius to `1`; upgrading it to a homeomorphism (matching
  the Krull topology on the left against the profinite topology on the right) is left for later.
  `Gal(L/k)` for *any* Galois `L/k` is a `ProfiniteGrp` matching the limit of its finite Galois
  subextensions' groups, via `InfiniteGalois.profiniteGalGrp` /
  `InfiniteGalois.profiniteGalGrpIsoLimit` in `Mathlib.FieldTheory.Galois.Profinite` -- so packaging
  `Gal(kbar/𝓀[K])` itself as a `ProfiniteGrp` is now off-the-shelf. **Topological generation is now
  fully proved**: `frobenius_apply` (`frobenius K` raises *every* element of `kbar`, not just
  `𝓀[K]`-fixed ones, to the `#𝓀[K]`-th power), `restrictNormalHom_frobenius_apply` /
  `restrictNormalHom_frobenius_pow_apply` (this restricts correctly to any finite Galois
  subextension), `frobeniusZpowersHom` (`Multiplicative ℤ →* Gal(kbar/𝓀[K])`, `n ↦ frobeniusAlgEquiv
  K ^ n`), and (combining these with `exists_frobenius_pow_eq` and the Krull-topology neighbourhood
  basis `InfiniteGalois.krullTopology_mem_nhds_one_iff_of_isGalois`) `denseRange_frobeniusZpowersHom`:
  the subgroup generated by Frobenius is dense in `Gal(kbar/𝓀[K])`. What remains is now two
  genuinely separate gaps (see the docstring of `exists_residueGaloisGroup_equiv_Zhat` for full
  detail): (1) a **universe obstruction**, discovered while trying to apply
  `ProfiniteGrp.ProfiniteCompletion.lift` to `frobeniusZpowersHom` bundled via
  `InfiniteGalois.profiniteGalGrp` -- `Zhat` is hardwired to universe `0` while `kbar` lives in
  `K`'s own (`variable`-bound, arbitrary) universe, and Mathlib's categorical profinite-completion
  API requires matching universes, so a `ULift` bridge (not attempted here) is needed for general
  `K`; density above would then give surjectivity for free. (2) **Injectivity**, the deeper
  content: `IsCyclic.existsUnique_subgroup_card_eq` (`Langlands.CyclicSubgroups`) and its Galois-
  theoretic translation `IsGalois.existsUnique_intermediateField_finrank_eq`
  (`Langlands.CyclicGaloisSubfields`) are now available and specialized here
  (`isCyclic_gal_of_finite_normal`, `exists_intermediateField_finrank_eq`), giving cyclicity of
  every finite `Gal(M/𝓀[K])` and *existence* of a degree-`n` subfield of `kbar` for every `n`; still
  missing is *global* uniqueness of that subfield across all of `kbar` (not just within one fixed
  finite Galois subextension) and the final assembly against `Zhat`'s defining diagram.
The full set-theoretic splitting `W_K ≃ I_K × ℤ` (as opposed to just the topology, which is built
directly via `WeilGroup.groupFilterBasis` without needing it) and continuity of `WeilGroup.toArt`
for that topology are not yet constructed either; both are left for later.

Everything else that depends on these five facts *only* formally -- `residueAction_ker`, the
`IsLocalHom` instance for `algebraMap 𝒪[K] 𝒪[K̄]`, `inertiaSubgroup_le_weilGroup`, and the
definitions of `frobenius` / `frobenius_fixes` (via `residueField_isAlgClosed` giving `kbar`
`PerfectField`, hence `PerfectRing kbar p` for `p` the residue characteristic, hence a genuine
`iterateFrobeniusEquiv`) -- is proved outright, not `sorry`-ed. `residueAction_ker` in particular
needs no input beyond `MonoidHom.ker` algebra: `residueAction` is `ValuationSubring.inertiaSubgroup`
composed with the (bijective, value-preserving) `decompositionEquiv`, so its kernel is literally
`inertiaSubgroup K` regardless of which valuation subring extension was chosen. Likewise the
`IsLocalHom` instance is proved directly from `Submonoid.isUnit_iff_and` and
`valuationSubringExtension_comap`, without needing Chevalley's theorem's *content* (only its
statement, `valuationSubringExtension_comap`, which is definitional once a choice is fixed).

None of these are needed for the *definitions* of `inertiaSubgroup`, `residueAction`, `Zhat`,
`frobenius`, or `WeilGroup` themselves to typecheck; they are only needed for the expected
*properties* of these objects (e.g. that `I_K` really is the kernel of `G_K → Gal(k̄/k)`, that
`Zhat` really is (topologically) generated by the image of `1`, etc.), which is why the
definitions are considered the primary deliverable of this file.

## References
* J-P. Serre, *Local Fields*, chapter XII (definition of the Weil group).
* J. Tate, *Number theoretic background*, §1, in *Automorphic forms, representations, and
  L-functions* (Corvallis proceedings).
-/

noncomputable section

open ValuativeRel Valuation IsLocalRing CategoryTheory
open scoped Pointwise Topology

namespace LocalField

variable (K : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- A fixed algebraic closure of `K`. -/
local notation "L" => AlgebraicClosure K

/-! ### The valuation subring of `K̄` extending `𝒪[K]` -/

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- **Chevalley's extension theorem** (not yet in Mathlib): every valuation on a field extends to
an algebraic closure. We record the existence of a valuation subring of `L = AlgebraicClosure K`
lying over `𝒪[K] = (valuation K).valuationSubring` as a `sorry`-ed fact, and fix a choice of such
an extension via `valuationSubringExtension`. -/
theorem exists_valuationSubring_extends :
    ∃ A : ValuationSubring L, A.comap (algebraMap K L) = (valuation K).valuationSubring := by
  set O := (valuation K).valuationSubring with hO
  set f : ↥O →+* L := (algebraMap K L).comp O.subtype with hf
  obtain ⟨A, hA, hloc⟩ := IsLocalRing.exists_factor_valuationRing f
  haveI : IsLocalHom (f.codRestrict A.toSubring hA) := hloc
  refine ⟨A, ValuationSubring.ext _ _ fun x => ?_⟩
  rw [ValuationSubring.mem_comap]
  constructor
  · intro hx
    by_contra hxO
    -- `x ∉ O`, so `x⁻¹ ∈ O` (and `x⁻¹` is a non-unit in `O`, since otherwise `x ∈ O`).
    have hx0 : x ≠ 0 := fun h => hxO (h ▸ O.zero_mem)
    have hxinv : x⁻¹ ∈ O := (O.mem_or_inv_mem x).resolve_left hxO
    set b : ↥O := ⟨x⁻¹, hxinv⟩ with hb
    have hfb : f b ∈ A.toSubring := hA b
    have hfb' : f b = (algebraMap K L x)⁻¹ := by
      show (algebraMap K L) x⁻¹ = (algebraMap K L x)⁻¹
      exact map_inv₀ _ _
    -- both `algebraMap K L x` and its inverse lie in `A`, so it (equivalently, `f b`) is a unit.
    have hne : algebraMap K L x ≠ 0 := (map_ne_zero_iff (algebraMap K L) (algebraMap K L).injective).mpr hx0
    have hub : IsUnit (f.codRestrict A.toSubring hA b) := by
      refine isUnit_iff_exists_inv.mpr ⟨⟨algebraMap K L x, hx⟩, Subtype.ext ?_⟩
      show f b * algebraMap K L x = 1
      rw [hfb', inv_mul_cancel₀ hne]
    have hbunit : IsUnit b := IsLocalHom.map_nonunit b hub
    -- but then `x = (x⁻¹)⁻¹ ∈ O`, contradicting `hxO`.
    obtain ⟨c, hc⟩ := isUnit_iff_exists_inv.mp hbunit
    have hcx : (c : K) = x := by
      have hbc : (b : K) * (c : K) = 1 := congrArg Subtype.val hc
      rw [hb] at hbc
      show (c : K) = x
      field_simp at hbc
      rw [hbc]
    exact hxO (hcx ▸ c.2)
  · intro hxO
    exact hA ⟨x, hxO⟩

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- A choice of valuation subring of `L = AlgebraicClosure K` extending `𝒪[K]`, i.e. "the" ring
of integers `𝒪[K̄]` of the algebraic closure (for our fixed choice of extended valuation). -/
def valuationSubringExtension : ValuationSubring L :=
  (exists_valuationSubring_extends K).choose

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
@[simp]
theorem valuationSubringExtension_comap :
    (valuationSubringExtension K).comap (algebraMap K L) = (valuation K).valuationSubring :=
  (exists_valuationSubring_extends K).choose_spec

/-! ### The decomposition subgroup is everything -/

/-- Since `K` is complete (hence Henselian), the valuation on `K` extends *uniquely* (up to
equivalence) to any algebraic extension of `K`, so every automorphism of `K̄` over `K` stabilizes
`valuationSubringExtension K`. Equivalently: the decomposition subgroup of
`valuationSubringExtension K` is all of `G_K`. This is a standard fact about Henselian valued
fields, not yet in Mathlib as such (searched thoroughly: `Mathlib.RingTheory.Henselian` only has
the local lifting property, not a statement about uniqueness of extension of a valuation/norm to
an algebraic extension; `Mathlib.RingTheory.Valuation.LocalSubring` /
`Mathlib.RingTheory.Valuation.Extension` only give *existence* of extensions, which is what
powers `exists_valuationSubring_extends` above, not uniqueness).

The proof is bridged through the *normed-field* side, via `Langlands.HenselianValuation`:
`Mathlib.Analysis.Normed.Unbundled.SpectralNorm.spectralNorm_unique_field_norm_ext` shows that for
`K` a complete nonarchimedean normed field and `L / K` algebraic, *any* multiplicative norm on `L`
extending the norm on `K` equals the spectral norm, i.e. the norm extension is unique. We transport
`K`'s `ValuativeRel`/rank-≤-1 valuation to a `NontriviallyNormedField` structure (via
`Valued.toNontriviallyNormedField`, from the automatic `Valuation.RankOne (valuation K)` instance
for `IsNonarchimedeanLocalField K`, and a `Valued K _` instance built from a local right-uniformity
on `K`'s topology) together with the `CompleteSpace K` instance already available for that
uniformity (`IsNonarchimedeanLocalField.instCompleteSpace`), and apply
`LocalField.valuationSubring_eq_of_comap_eq` to `valuationSubringExtension K` and its `σ`-translate
for `σ` ranging over `G_K` (using `ValuationSubring.comap_smul_eq`, a purely formal fact that
`σ`-translates restrict to the same subring of `K` since `σ` fixes `K` pointwise).
`LocalField.exists_rankOne_absoluteValue_extends`, which packages: (1) rank preservation of a
valuation under an algebraic extension, and (2) compatible normalization of the extended embedding
into `ℝ≥0` -- see its docstring for details -- is now **fully proved, no remaining `sorry`**: (1) is
`Valuation.exists_pow_eq_of_isAlgebraic` and (2) is `Valuation.exists_rpow_eq_of_isEquiv`, both
general-purpose lemmas new to this project and not otherwise in Mathlib. None of this bridging work
existed in Mathlib before; it is now complete here. -/
theorem decompositionSubgroup_eq_top :
    ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) = ⊤ := by
  letI := IsTopologicalAddGroup.rightUniformSpace K
  haveI := isUniformAddGroup_of_addCommGroup (G := K)
  letI : (Valued.v (R := K)).RankOne :=
    { hom' := IsRankLeOne.nonempty.some.emb (R := K).comp MonoidWithZeroHom.ValueGroup₀.embedding
      strictMono' := IsRankLeOne.nonempty.some.strictMono.comp
          MonoidWithZeroHom.ValueGroup₀.embedding_strictMono }
  letI : NontriviallyNormedField K := Valued.toNontriviallyNormedField K (ValueGroupWithZero K)
  haveI : IsUltrametricDist K := inferInstance
  haveI : CompleteSpace K := inferInstance
  -- The `NontriviallyNormedField K` structure above is built *from* `Valued.v = valuation K`
  -- (via `Valued.toNontriviallyNormedField`/`Valued.toNormedField`), so its own
  -- `NormedField.valuation` agrees with `Valued.v` on the nose
  -- (`Valued.coe_valuation_eq_rankOne_hom_comp_valuation`), giving the `Compatible` instance
  -- `LocalField.valuationSubring_eq_of_comap_eq` now requires.
  have hnorm : ∀ x : K, (NormedField.valuation x : NNReal)
      = RankOne.hom (Valued.v (R := K)) ((Valued.v (R := K)).restrict x) := fun x =>
    congrFun (Valued.coe_valuation_eq_rankOne_hom_comp_valuation K (ValueGroupWithZero K)) x
  haveI : (NormedField.valuation (K := K)).Compatible :=
    NormedField.valuation_compatible_of_eq_rankOne_hom_comp_restrict (Valued.v (R := K)) hnorm
  rw [Subgroup.eq_top_iff']
  intro σ
  rw [MulAction.mem_stabilizer_iff]
  apply LocalField.valuationSubring_eq_of_comap_eq (K := K)
  · rw [ValuationSubring.comap_smul_eq]
    exact valuationSubringExtension_comap K
  · exact valuationSubringExtension_comap K

/-- The canonical isomorphism `G_K ≃* (decomposition subgroup of `𝒪[K̄]`)`, using
`decompositionSubgroup_eq_top`. -/
def decompositionEquiv :
    Field.absoluteGaloisGroup K ≃*
      ValuationSubring.decompositionSubgroup K (valuationSubringExtension K) :=
  (Subgroup.topEquiv (G := Field.absoluteGaloisGroup K)).symm.trans
    (MulEquiv.subgroupCongr (decompositionSubgroup_eq_top K).symm)

/-! ### The inertia subgroup -/

/-- The inertia subgroup `I_K ≤ G_K`: the kernel of the action of `G_K` on the residue field of
`valuationSubringExtension K`, transported from `ValuationSubring.inertiaSubgroup` along the fact
that the decomposition subgroup of `valuationSubringExtension K` is everything
(`decompositionSubgroup_eq_top`). -/
def inertiaSubgroup : Subgroup (Field.absoluteGaloisGroup K) :=
  (ValuationSubring.inertiaSubgroup K (valuationSubringExtension K)).map
    (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)).subtype

/-! ### The residue field extension and the induced Galois action -/

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄] = valuationSubringExtension K`, i.e. the restriction of
`algebraMap K L` to rings of integers; well-defined by `valuationSubringExtension_comap`. -/
def integersAlgebraMap : ↥(𝒪[K]) →+* valuationSubringExtension K :=
  ((algebraMap K L).comp (𝒪[K]).subtype).codRestrict _ fun x => by
    have hx : (x : K) ∈ (valuation K).valuationSubring :=
      (Valuation.mem_valuationSubring_iff _ _).mpr ((Valuation.mem_integer_iff _ _).mp x.2)
    rw [← valuationSubringExtension_comap K] at hx
    exact (ValuationSubring.mem_comap).mp hx

instance : Algebra ↥(𝒪[K]) (valuationSubringExtension K) := (integersAlgebraMap K).toAlgebra

/-- The inclusion `𝒪[K] ↪ 𝒪[K̄]` is a local homomorphism: since both are valuation subrings and
the inclusion is the restriction of the (injective, field-valued) map `algebraMap K L` compatible
with the valuations, it reflects units. Not yet proved here. -/
instance : IsLocalHom (algebraMap ↥(𝒪[K]) (valuationSubringExtension K)) := by
  refine ⟨fun a ha => ?_⟩
  set A := valuationSubringExtension K
  have hcoe : ((algebraMap ↥(𝒪[K]) A a : A) : L) = algebraMap K L (a : K) := rfl
  rw [Submonoid.isUnit_iff_and, hcoe] at ha
  obtain ⟨hne0, hinv⟩ := ha
  rw [Submonoid.isUnit_iff_and]
  refine ⟨fun h => hne0 (by rw [h]; simp), ?_⟩
  rw [← map_inv₀] at hinv
  have hmem : (a : K)⁻¹ ∈ (valuation K).valuationSubring := by
    rw [← valuationSubringExtension_comap K]
    exact ValuationSubring.mem_comap.mpr hinv
  exact (Valuation.mem_integer_iff _ _).mpr ((Valuation.mem_valuationSubring_iff _ _).mp hmem)

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- The algebra structure on `valuationSubringExtension K` over `↥(𝒪[K])` is compatible with the
ambient inclusions `↥(𝒪[K]) → K → L`: this is exactly the fact that `integersAlgebraMap` is (the
restriction to integers of) `algebraMap K L`, and is needed to invoke the generic lemmas of
`Langlands.UnramifiedExtension` (`decompositionSubgroup_smul_algebraMap_residueField`,
`exists_restrictNormalHom_decompositionSubgroup_surjective`) with `A := valuationSubringExtension
K`. Recorded as a plain lemma (rather than an `IsScalarTower` instance) since those two lemmas
take this compatibility as an explicit hypothesis instead of a typeclass -- see the implementation
notes in `Langlands.UnramifiedExtension` for why. -/
theorem integersAlgebraMap_compat (a : ↥(𝒪[K])) :
    (algebraMap ↥(𝒪[K]) (valuationSubringExtension K) a : L) = algebraMap K L (a : K) := rfl

/-- The residue field of the algebraic-closure integers `valuationSubringExtension K`: this is
(via `residueField_isAlgClosed` / `residueField_isAlgebraic`, proved in `Langlands.ResidueField`)
an algebraic closure `𝓀[K]bar` of the (finite) residue field `𝓀[K]`. -/
local notation "kbar" => IsLocalRing.ResidueField (valuationSubringExtension K)

omit [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- The residue field `kbar` of `valuationSubringExtension K` is algebraically closed. This
reflects the general fact that the residue field of a valuation ring inside an algebraically
closed field is algebraically closed (`ValuationSubring.residueField_isAlgClosed`, proved in
`Langlands.ResidueField` for an arbitrary valuation subring of an algebraically closed field, not
needing anything about `K` or `decompositionSubgroup_eq_top`). -/
theorem residueField_isAlgClosed : IsAlgClosed kbar :=
  ValuationSubring.residueField_isAlgClosed (valuationSubringExtension K)

/-- The residue field `kbar` of `valuationSubringExtension K` is algebraic over `𝓀[K]`. Every
`x : kbar` is the residue of some `b : valuationSubringExtension K`; `b` is integral over `𝒪[K]`
by `ValuationSubring.isIntegralElem_of_decompositionSubgroup_eq_top` (using
`decompositionSubgroup_eq_top`), and the residue of an integral element is algebraic over the
residue field of the base (`IsIntegral.isAlgebraic_residue`). -/
theorem residueField_isAlgebraic : Algebra.IsAlgebraic 𝓀[K] kbar := by
  set A := valuationSubringExtension K with hAdef
  refine ⟨fun x => ?_⟩
  obtain ⟨b, rfl⟩ := IsLocalRing.residue_surjective (R := A) x
  -- `b`, viewed inside `L`, is integral over `A.comap (algebraMap K L)`.
  have hbint : RingHom.IsIntegralElem
      ((algebraMap K L).comp (algebraMap (A.comap (algebraMap K L)) K)) (b : L) :=
    ValuationSubring.isIntegralElem_of_decompositionSubgroup_eq_top A
      (decompositionSubgroup_eq_top K) b.2
  rw [valuationSubringExtension_comap K] at hbint
  -- The "long way" `𝒪[K] → K → L` and the "short way" `𝒪[K] → A → L` agree (definitionally),
  -- so `hbint` already has the type needed to descend along the (injective) map `A → L`.
  have hAL_inj : Function.Injective (algebraMap A L) := IsFractionRing.injective A L
  have hbint' : RingHom.IsIntegralElem (algebraMap ↥(𝒪[K]) A) b :=
    RingHom.IsIntegralElem.of_map hAL_inj hbint
  exact IsIntegral.isAlgebraic_residue hbint'

instance : Fact (IsAlgClosed kbar) := ⟨residueField_isAlgClosed K⟩

instance : Algebra.IsAlgebraic 𝓀[K] kbar := residueField_isAlgebraic K

/-- `kbar` is an algebraic closure of `𝓀[K]`, packaging `residueField_isAlgClosed` and
`residueField_isAlgebraic` into the `IsAlgClosure` typeclass. This is what lets us invoke the
general theory of algebraic closures (`IsAlgClosure.normal`, giving `Normal 𝓀[K] kbar`) below,
rather than reproving normality of `kbar/𝓀[K]` by hand. -/
instance : IsAlgClosure 𝓀[K] kbar where
  isAlgClosed := residueField_isAlgClosed K
  isAlgebraic := residueField_isAlgebraic K

/-- `kbar/𝓀[K]` is Galois: it is normal (`IsAlgClosure.normal`, since `kbar` is an algebraic
closure of `𝓀[K]`) and separable (`Algebra.IsAlgebraic.isSeparable_of_perfectField`, since `𝓀[K]`
is finite, hence perfect, and `kbar/𝓀[K]` is algebraic). Unlike the general
`IsAlgClosure.separable` instance in Mathlib, this does not need `CharZero 𝓀[K]` (which would be
false: `𝓀[K]` has positive characteristic), only that `𝓀[K]` is perfect. -/
instance residueField_isGalois : IsGalois 𝓀[K] kbar := ⟨⟩

/-- The action of the decomposition subgroup (i.e., via `decompositionEquiv`, of all of `G_K`) on
`valuationSubringExtension K` induces an action on its residue field `kbar`, giving a
homomorphism `G_K →* RingAut kbar`. Its kernel is `inertiaSubgroup K` and its image is (all of,
though this is not recorded here) the Galois group `Gal(kbar/𝓀[K])`. -/
def residueAction : Field.absoluteGaloisGroup K →* RingAut kbar :=
  (MulSemiringAction.toRingAut
      (ValuationSubring.decompositionSubgroup K (valuationSubringExtension K)) kbar).comp
    (decompositionEquiv K).toMonoidHom

theorem residueAction_ker : (residueAction K).ker = inertiaSubgroup K := by
  ext x
  simp only [residueAction, inertiaSubgroup, MonoidHom.mem_ker, MonoidHom.coe_comp,
    Function.comp_apply, MulEquiv.coe_toMonoidHom, Subgroup.mem_map]
  constructor
  · intro hx
    exact ⟨decompositionEquiv K x, hx, rfl⟩
  · rintro ⟨y, hy, hxy⟩
    have hyx : decompositionEquiv K x = y := by
      apply Subtype.ext
      rw [← hxy]; rfl
    rwa [hyx]

/-! ### The profinite completion `ℤ̂` and Frobenius -/

/-- The profinite completion `ℤ̂` of `ℤ`, written multiplicatively (as the profinite completion,
in the sense of `ProfiniteGrp.ProfiniteCompletion`, of the multiplicative group `Multiplicative
ℤ`). This carries its `Group`, `TopologicalSpace`, and `IsTopologicalGroup` (in fact
`CompactSpace` and `TotallyDisconnectedSpace`) instances via the `CoeSort` on `ProfiniteGrp`. -/
abbrev Zhat : Type := ProfiniteGrp.ProfiniteCompletion.completion (GrpCat.of (Multiplicative ℤ))

/-- The canonical dense homomorphism `ℤ → ℤ̂` (written multiplicatively). -/
def toZhat : Multiplicative ℤ →* Zhat :=
  (ProfiniteGrp.ProfiniteCompletion.eta (GrpCat.of (Multiplicative ℤ))).hom

theorem denseRange_toZhat : DenseRange (toZhat) :=
  ProfiniteGrp.ProfiniteCompletion.denseRange (GrpCat.of (Multiplicative ℤ))

/-- `Multiplicative ℤ` is residually finite: given `g ≠ 1`, i.e. `n := g.toAdd ≠ 0`, reduction mod
any modulus exceeding `|n|` is a homomorphism to a finite group not killing `g`. This is what makes
`toZhat` injective (`toZhat_injective`), i.e. makes `ℤ̂` genuinely contain (a copy of) `ℤ`. -/
instance : Group.ResiduallyFinite (Multiplicative ℤ) := by
  apply Group.residuallyFinite_of_forall_exists_finite_monoidHom
  intro g hg
  set n : ℤ := g.toAdd with hn
  have hn0 : n ≠ 0 := fun h => hg (toAdd_eq_zero.mp h)
  refine ⟨Multiplicative (ZMod (n.natAbs + 1)), inferInstance, inferInstance,
    (Int.castAddHom (ZMod (n.natAbs + 1))).toMultiplicative, fun h => hn0 ?_⟩
  have h' : (n : ZMod (n.natAbs + 1)) = 0 := by
    simpa [AddMonoidHom.toMultiplicative, ← hn, toAdd_eq_zero] using h
  rw [ZMod.intCast_zmod_eq_zero_iff_dvd] at h'
  have h'' : ((n.natAbs + 1 : ℕ) : ℤ) ∣ (n.natAbs : ℤ) := Int.dvd_natAbs.mpr h'
  have hpos : (0 : ℤ) < (n.natAbs : ℤ) := by exact_mod_cast Int.natAbs_pos.mpr hn0
  have hle := Int.le_of_dvd hpos h''
  omega

/-- `toZhat` is injective: `ℤ` really does embed into its profinite completion `ℤ̂`. -/
theorem toZhat_injective : Function.Injective (toZhat) :=
  (ProfiniteGrp.ProfiniteCompletion.etaFn_injective_iff_residuallyFinite
    (GrpCat.of (Multiplicative ℤ))).mpr inferInstance

/-- The subgroup `ℤ ≤ ℤ̂` given by the (injective, by `toZhat_injective`) image of `toZhat`. -/
def integerSubgroup : Subgroup Zhat := (toZhat).range

/-- The isomorphism `ℤ ≃* integerSubgroup`, i.e. `ℤ ≤ ℤ̂` really is (a copy of) `ℤ` and not some
quotient of it, using injectivity of `toZhat`. -/
def integerSubgroupEquiv : Multiplicative ℤ ≃* integerSubgroup :=
  MonoidHom.ofInjective toZhat_injective

instance : Fintype 𝓀[K] := Fintype.ofFinite _

/-- The residue characteristic `p` of `𝓀[K]` (and, transported along `algebraMap 𝓀[K] kbar`, of
`kbar`). -/
def residueCharP : ℕ := ringChar 𝓀[K]

instance : CharP 𝓀[K] (residueCharP K) := ringChar.charP _

instance residueCharP_fact : Fact (residueCharP K).Prime :=
  ⟨CharP.char_is_prime 𝓀[K] _⟩

/-- The degree `n` of `𝓀[K]` over its prime field, i.e. `#𝓀[K] = p ^ n` (`card_residueField_eq`). -/
def residueDegree : ℕ+ := (FiniteField.card 𝓀[K] (residueCharP K)).choose

theorem card_residueField_eq :
    Fintype.card 𝓀[K] = (residueCharP K) ^ (residueDegree K : ℕ) :=
  (FiniteField.card 𝓀[K] (residueCharP K)).choose_spec.2

instance : CharP kbar (residueCharP K) :=
  charP_of_injective_algebraMap (algebraMap 𝓀[K] kbar).injective _

instance : ExpChar 𝓀[K] (residueCharP K) := .prime (residueCharP_fact K).out

instance : ExpChar kbar (residueCharP K) := .prime (residueCharP_fact K).out

/-- The (arithmetic) Frobenius automorphism `x ↦ x ^ #𝓀[K]` of `kbar`, generating (topologically)
the Galois group `Gal(kbar/𝓀[K])`. Well-definedness as a ring automorphism (as opposed to merely
an endomorphism) uses that `kbar` is algebraically closed, hence perfect
(`residueField_isAlgClosed`), so that the (injective, since `kbar` is a field) Frobenius
endomorphism is also surjective. -/
def frobenius : RingAut kbar :=
  haveI : PerfectField kbar := @IsAlgClosed.perfectField kbar _ (residueField_isAlgClosed K)
  haveI : PerfectRing kbar (residueCharP K) := PerfectField.toPerfectRing (residueCharP K)
  iterateFrobeniusEquiv kbar (residueCharP K) (residueDegree K : ℕ)

/-- Frobenius fixes `𝓀[K]` pointwise: elements of the residue field of `𝒪[K]` satisfy
`x ^ #𝓀[K] = x`, by Lagrange / Fermat's little theorem for the finite field `𝓀[K]`. -/
theorem frobenius_fixes (x : 𝓀[K]) :
    frobenius K (algebraMap 𝓀[K] kbar x) = algebraMap 𝓀[K] kbar x := by
  haveI : PerfectField kbar := @IsAlgClosed.perfectField kbar _ (residueField_isAlgClosed K)
  haveI : PerfectRing kbar (residueCharP K) := PerfectField.toPerfectRing (residueCharP K)
  show iterateFrobeniusEquiv kbar (residueCharP K) (residueDegree K : ℕ)
      (algebraMap 𝓀[K] kbar x) = algebraMap 𝓀[K] kbar x
  rw [iterateFrobeniusEquiv_def, ← map_pow, ← card_residueField_eq, FiniteField.pow_card]

/-- `frobenius K`, packaged as a genuine element of `Gal(kbar/𝓀[K]) = kbar ≃ₐ[𝓀[K]] kbar` (rather
than merely of `RingAut kbar`), using `frobenius_fixes` to see that it commutes with
`algebraMap 𝓀[K] kbar`. This is the object that should ultimately generate (topologically) the
Galois group `Gal(kbar/𝓀[K])` in `exists_residueGaloisGroup_equiv_Zhat`. -/
def frobeniusAlgEquiv : kbar ≃ₐ[𝓀[K]] kbar :=
  AlgEquiv.ofRingEquiv (f := frobenius K) (frobenius_fixes K)

@[simp]
theorem frobeniusAlgEquiv_apply (x : kbar) : frobeniusAlgEquiv K x = frobenius K x := rfl

/-- **The finite-field input to `exists_residueGaloisGroup_equiv_Zhat`, now fully available**:
for any *finite* subextension `L` of `kbar/𝓀[K]` (e.g. a `FiniteGaloisIntermediateField 𝓀[K]
kbar`), every automorphism of `L/𝓀[K]` is *some* power of the (finite-field) Frobenius `x ↦
x ^ #𝓀[K]`. This is `FiniteField.exists_forall_apply_eq_pow`, specialized to `k := 𝓀[K]`; unlike
that general statement it is genuinely a fact about finite fields only (no local-field input),
and is exactly the "each finite subextension's Galois group is cyclic, generated by Frobenius"
ingredient the module docstring lists as already available in Mathlib but not yet connected up.

Combined with a fact relating `frobeniusAlgEquiv K` restricted to any finite Galois subextension
`L ≤ kbar` to this finite-field Frobenius (not yet stated here: it needs `AlgEquiv.restrictNormalHom`
applied to `frobeniusAlgEquiv K`, together with `AlgEquiv.restrictNormal_commutes` unwinding what
the restriction does on `L`), this identifies, for every finite Galois subextension `L`, the image
of `frobeniusAlgEquiv K` in `Gal(L/𝓀[K])` as a generator -- the remaining gap for
`exists_residueGaloisGroup_equiv_Zhat` is assembling this level-by-level statement into a genuine
isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` (i.e. matching the open-subgroup diagrams, per the module
docstring, using e.g. `InfiniteGalois.profiniteGalGrp` and `ProfiniteGrp.ProfiniteCompletion.lift`),
not this finite-field input itself. -/
theorem exists_frobenius_pow_eq {M : Type*} [Field M] [Algebra 𝓀[K] M] [Finite M]
    (g : M ≃ₐ[𝓀[K]] M) : ∃ i : ℕ, ∀ x : M, g x = x ^ (Fintype.card 𝓀[K]) ^ i := by
  obtain ⟨i, hi⟩ := FiniteField.exists_forall_apply_eq_pow (k := 𝓀[K]) (p := residueCharP K)
    (l := M) g
  exact ⟨i, fun x => by simpa [Nat.card_eq_fintype_card] using hi x⟩

/-! ### Compactness, density, and the range of `residueAction` -/

/-- `residueAction`, repackaged as a homomorphism directly into `Gal(kbar/𝓀[K]) = kbar ≃ₐ[𝓀[K]]
kbar` rather than merely into `RingAut kbar`. Well-defined because `residueAction K σ` (which
unfolds to the residue action of `decompositionEquiv K σ`) fixes `𝓀[K]` pointwise, by
`ValuationSubring.decompositionSubgroup_smul_algebraMap_residueField`
(`Langlands.UnramifiedExtension`). This is the map whose range we show is everything, via
compactness of `G_K` and the Galois correspondence for `Gal(kbar/𝓀[K])`. -/
def residueAction' : Field.absoluteGaloisGroup K →* (kbar ≃ₐ[𝓀[K]] kbar) where
  toFun σ := AlgEquiv.ofRingEquiv (f := residueAction K σ) (fun x => by
    show (decompositionEquiv K σ) • algebraMap 𝓀[K] kbar x = algebraMap 𝓀[K] kbar x
    exact ValuationSubring.decompositionSubgroup_smul_algebraMap_residueField
      (K := K) (valuationSubringExtension K) (integersAlgebraMap_compat K)
      (decompositionEquiv K σ) x)
  map_one' := AlgEquiv.ext fun x => by
    show residueAction K 1 x = x
    simp
  map_mul' a b := AlgEquiv.ext fun x => by
    show residueAction K (a * b) x = residueAction K a (residueAction K b x)
    simp

@[simp]
theorem residueAction'_apply (σ : Field.absoluteGaloisGroup K) (x : kbar) :
    residueAction' K σ x = residueAction K σ x := by
  simp [residueAction', AlgEquiv.ofRingEquiv]

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K] in
/-- **Not yet in Mathlib and not proved here**: `Field.absoluteGaloisGroup K = Gal(K̄/K)` is
compact for the Krull topology. This is true (it is a standard fact that the absolute Galois group
of any field is profinite, via `Gal(K̄/K) ≅ Gal(K_sep/K)` -- an isomorphism holding even when `K`
is imperfect, since a `K`-automorphism of the algebraic closure `K̄` is determined by, and
corresponds bijectively to, its restriction to the separable closure `K_sep`, purely inseparable
extensions admitting a *unique* embedding extending any given one), but Mathlib's
`CompactSpace Gal(L/k)` instance (`FieldTheory.Galois.Profinite`) currently requires `[IsGalois k
L]`, i.e. `L/k` separable, which can fail for `K̄/K` when `K` has positive characteristic and is
not perfect (e.g. `𝔽_q((t))`, a genuine non-archimedean local field). Bridging this gap (matching
`Gal(K̄/K)` against `Gal(K_sep/K)` as topological groups) is not carried out here. -/
theorem compactSpace_absoluteGaloisGroup : CompactSpace (Field.absoluteGaloisGroup K) := by
  classical
  haveI hNormalL : Normal K L := IsAlgClosure.normal K L
  set Ksep : IntermediateField K L := separableClosure K L with hKsepdef
  haveI : IsGalois K Ksep := by rw [hKsepdef]; exact separableClosure.isGalois K L
  set φ : Field.absoluteGaloisGroup K →* (Ksep ≃ₐ[K] Ksep) :=
    AlgEquiv.restrictNormalHom (F := K) (K₁ := L) Ksep with hφdef
  have hφcont : Continuous φ := InfiniteGalois.restrictNormalHom_continuous Ksep
  have hφsurj : Function.Surjective φ :=
    AlgEquiv.restrictNormalHom_surjective (F := K) (K₁ := Ksep) (E := L)
  haveI hpi : IsPurelyInseparable Ksep L := by
    rw [hKsepdef]; exact separableClosure.isPurelyInseparable K L
  have hφinj : Function.Injective φ := by
    rw [injective_iff_map_eq_one]
    intro σ hσ
    have hfix := (AlgEquiv.restrictNormal_eq_one_iff Ksep σ).1 hσ
    let e : L →ₐ[Ksep] L := ⟨σ.toAlgHom.toRingHom, fun x => hfix x x.2⟩
    have he : e = IsScalarTower.toAlgHom Ksep L L := Subsingleton.elim _ _
    have : (e : L → L) = id := by
      have := AlgHom.ext_iff.1 he
      funext x
      simpa using this x
    exact AlgEquiv.ext fun x => congrFun this x
  have hφbij : Function.Bijective φ := ⟨hφinj, hφsurj⟩
  let ψ : Field.absoluteGaloisGroup K ≃* (Ksep ≃ₐ[K] Ksep) := MulEquiv.ofBijective φ hφbij
  have hψsymm_cont : Continuous ψ.symm := by
    apply continuous_of_continuousAt_one _ (continuousAt_def.mpr _)
    intro W hW
    rw [map_one] at hW
    -- `Field.absoluteGaloisGroup K` is a `def`, not reducible, so `rw` cannot see through it to
    -- match `krullTopology_mem_nhds_one_iff`'s `Gal(L/K)`-shaped statement even though the two
    -- are defeq (and share the same Krull topology, since `absoluteGaloisGroup` derives its
    -- `TopologicalSpace` instance from exactly this identification). Applying the `Iff` directly
    -- (rather than `rw`) lets ordinary defeq-checking bridge the gap.
    obtain ⟨M, hMfd, hMW⟩ := (krullTopology_mem_nhds_one_iff K L W).mp hW
    haveI : FiniteDimensional K M := hMfd
    -- `N0` = separable closure of `K` in `M`.
    set N0 : IntermediateField K M := separableClosure K M with hN0def
    haveI hpiN0 : IsPurelyInseparable N0 M := by
      rw [hN0def]; exact separableClosure.isPurelyInseparable K M
    -- push `N0` into `Ksep` along the inclusion `M ↪ L`.
    let ι : M →ₐ[K] L := IsScalarTower.toAlgHom K M L
    have hle : N0.map ι ≤ Ksep := separableClosure.map_le_of_algHom ι
    let N' : IntermediateField K Ksep := IntermediateField.restrict hle
    haveI hN0fd : FiniteDimensional K N0 := inferInstance
    haveI hN0mapfd : FiniteDimensional K (N0.map ι) :=
      Module.Finite.equiv (N0.equivMap ι).toLinearEquiv
    haveI hN'fd : FiniteDimensional K N' :=
      Module.Finite.equiv (IntermediateField.restrict_algEquiv hle).toLinearEquiv
    rw [krullTopology_mem_nhds_one_iff]
    refine ⟨N', hN'fd, fun σ hσ => ?_⟩
    rw [SetLike.mem_coe, IntermediateField.mem_fixingSubgroup_iff] at hσ
    have hliftM : σ.liftNormal L ∈ M.fixingSubgroup := by
      rw [IntermediateField.mem_fixingSubgroup_iff]
      intro y hyM
      set ym : M := ⟨y, hyM⟩ with hymdef
      obtain ⟨n, a, ha⟩ := IsPurelyInseparable.pow_mem N0 (ringExpChar K) ym
      -- `aKsep : Ksep` is the image of `a` under `M ↪ L`, landing in `N'` by construction.
      have haMap : ι (a : M) ∈ N0.map ι := N0.mem_map.2 ⟨a, a.2, rfl⟩
      set aKsep : Ksep := ⟨ι (a : M), hle haMap⟩ with haKsepdef
      have haKsep : aKsep ∈ N' := (IntermediateField.mem_restrict hle aKsep).2 haMap
      have hfixed : σ aKsep = aKsep := hσ aKsep haKsep
      -- `liftNormal` commutes with `algebraMap Ksep L`.
      have hcomm : σ.liftNormal L (algebraMap Ksep L aKsep) =
          algebraMap Ksep L (σ aKsep) := AlgEquiv.liftNormal_commutes σ L aKsep
      have hcommL : σ.liftNormal L ((a : M) : L) = ((a : M) : L) := by
        have hcoe : algebraMap Ksep L aKsep = ((a : M) : L) := rfl
        rw [hcoe, hfixed, hcoe] at hcomm
        exact hcomm
      -- `(a : M) : L = ym ^ q ^ n = y ^ q ^ n`, so `liftNormal` fixes `y ^ q ^ n`.
      have hpow : ((ym : M) : L) ^ (ringExpChar K) ^ n = ((a : M) : L) := by
        have h1 : (a : M) = ym ^ (ringExpChar K) ^ n := ha
        have h2 : ((a : M) : L) = ((ym ^ (ringExpChar K) ^ n : M) : L) := by rw [h1]
        rw [h2]; push_cast; ring
      have hy : y ^ (ringExpChar K) ^ n = ((a : M) : L) := by
        rw [← hpow]
      have hfixpow : σ.liftNormal L y ^ (ringExpChar K) ^ n = y ^ (ringExpChar K) ^ n := by
        have hstep : σ.liftNormal L (y ^ (ringExpChar K) ^ n) = y ^ (ringExpChar K) ^ n := by
          rw [hy]; exact hcommL
        rwa [map_pow] at hstep
      haveI hExpCharL : ExpChar L (ringExpChar K) :=
        expChar_of_injective_algebraMap (algebraMap K L).injective (ringExpChar K)
      have hinj : Function.Injective
          (iterateFrobenius L (ringExpChar K) n) := iterateFrobenius_inj L (ringExpChar K) n
      have : iterateFrobenius L (ringExpChar K) n (σ.liftNormal L y) =
          iterateFrobenius L (ringExpChar K) n y := by
        simpa [iterateFrobenius_def] using hfixpow
      exact hinj this
    have hkey : ψ.symm σ = σ.liftNormal L := by
      have hφeq : φ (σ.liftNormal L) = σ := σ.restrict_liftNormal L
      conv_lhs => rw [← hφeq]
      exact ψ.symm_apply_apply _
    rw [Set.mem_preimage, hkey]
    exact hMW hliftM
  let e : (Ksep ≃ₐ[K] Ksep) ≃ₜ Field.absoluteGaloisGroup K :=
    { toEquiv := ψ.symm.toEquiv, continuous_toFun := hψsymm_cont, continuous_invFun := hφcont }
  exact e.compactSpace

/-- **Not yet in Mathlib and not proved here**: `residueAction' K` (equivalently `residueAction
K`) is continuous, for the Krull topology on `G_K` and the Krull topology on `Gal(kbar/𝓀[K])`.
Plausible (the residue action of an open subgroup of `G_K` fixing a large enough subfield of `K̄`
should fix correspondingly many finite subextensions of `kbar/𝓀[K]`), but the precise
"correspondingly many" comparison between ramification-theoretic and Krull-topology neighborhoods
is genuinely local-field-theoretic content (related to, but not identical with, the unramified
lifting theorem `ValuationSubring.exists_restrictNormalHom_decompositionSubgroup_surjective`) that
is not assembled here. -/
theorem continuous_residueAction' : Continuous (residueAction' K) := by
  sorry

/-- `(residueAction' K).range` is a closed subgroup of `Gal(kbar/𝓀[K])`: the continuous
(`continuous_residueAction'`) image of the compact (`compactSpace_absoluteGaloisGroup`) group
`G_K`, hence compact, hence closed since `Gal(kbar/𝓀[K])` is Hausdorff (`krullTopology_t2`, using
`Algebra.IsAlgebraic 𝓀[K] kbar`, i.e. `residueField_isAlgebraic`). -/
def residueAction'ClosedRange : ClosedSubgroup (kbar ≃ₐ[𝓀[K]] kbar) where
  toSubgroup := (residueAction' K).range
  isClosed' := by
    haveI := compactSpace_absoluteGaloisGroup K
    haveI : T2Space (kbar ≃ₐ[𝓀[K]] kbar) := krullTopology_t2
    have hcompact : IsCompact (Set.range (residueAction' K)) :=
      isCompact_range (continuous_residueAction' K)
    rw [show (residueAction' K).range.carrier = Set.range (residueAction' K) from
      MonoidHom.coe_range (residueAction' K)]
    exact hcompact.isClosed

/-- **The key surjectivity-onto-finite-quotients fact**, transported from
`ValuationSubring.exists_restrictNormalHom_decompositionSubgroup_surjective`
(`Langlands.UnramifiedExtension`) along the bijection `decompositionEquiv K` and the definitional
unfolding of `residueAction'`: for every finite Galois `M ≤ kbar` over `𝓀[K]`, every automorphism
of `M/𝓀[K]` is the restriction of `residueAction' K σ` for some `σ ∈ G_K`. -/
theorem surjective_restrictNormalHom_comp_residueAction'
    (M : IntermediateField 𝓀[K] kbar) [FiniteDimensional 𝓀[K] M] [Normal 𝓀[K] M] :
    Function.Surjective fun σ : Field.absoluteGaloisGroup K =>
      AlgEquiv.restrictNormalHom (F := 𝓀[K]) M (residueAction' K σ) := by
  intro g
  obtain ⟨τ, hτ⟩ :=
    ValuationSubring.exists_restrictNormalHom_decompositionSubgroup_surjective
      (K := K) (valuationSubringExtension K) (integersAlgebraMap_compat K) M g
  refine ⟨(decompositionEquiv K).symm τ, ?_⟩
  rw [← hτ]
  congr 1

/-- `(residueAction' K).range` is everything, i.e. `residueAction' K` is surjective: combining
`surjective_restrictNormalHom_comp_residueAction'` (surjectivity onto every finite Galois
quotient) with the Galois correspondence for `Gal(kbar/𝓀[K])`
(`InfiniteGalois.restrict_fixedField`, `InfiniteGalois.fixingSubgroup_fixedField`) and closedness
of the range (`residueAction'ClosedRange`) shows the fixed field of the range is `⊥` (i.e. `𝓀[K]`
itself), hence (the range being closed) the range is the fixing subgroup of `⊥`, i.e. everything.
-/
theorem surjective_residueAction' : Function.Surjective (residueAction' K) := by
  have hfixed : IntermediateField.fixedField (residueAction'ClosedRange K).toSubgroup = ⊥ := by
    apply le_antisymm _ bot_le
    intro x hx
    -- `x` lies in some finite Galois subextension `M` of `kbar/𝓀[K]`.
    obtain ⟨M, hMfd, hMnormal, hxM⟩ :
        ∃ M : IntermediateField 𝓀[K] kbar, FiniteDimensional 𝓀[K] M ∧ Normal 𝓀[K] M ∧ x ∈ M := by
      classical
      haveI := residueField_isGalois K
      let L' := FiniteGaloisIntermediateField.adjoin 𝓀[K] ({x} : Set kbar)
      exact ⟨L'.toIntermediateField, L'.finiteDimensional, L'.isGalois.to_normal,
        FiniteGaloisIntermediateField.subset_adjoin 𝓀[K] ({x} : Set kbar) rfl⟩
    haveI := hMfd; haveI := hMnormal
    haveI : IsGalois 𝓀[K] M := ⟨⟩
    have hsurj : (residueAction'ClosedRange K).toSubgroup.map (AlgEquiv.restrictNormalHom M) = ⊤ := by
      rw [eq_top_iff]
      intro g _
      obtain ⟨σ, hσ⟩ := surjective_restrictNormalHom_comp_residueAction' K M g
      exact ⟨residueAction' K σ, ⟨σ, rfl⟩, hσ⟩
    have hM : IntermediateField.fixedField (residueAction'ClosedRange K).toSubgroup ⊓ M =
        IntermediateField.lift (IntermediateField.fixedField
          ((residueAction'ClosedRange K).toSubgroup.map (AlgEquiv.restrictNormalHom M))) :=
      InfiniteGalois.restrict_fixedField _ M
    rw [hsurj, InfiniteGalois.fixedField_bot] at hM
    simp only [IntermediateField.lift_bot] at hM
    have hxM' : x ∈ IntermediateField.fixedField (residueAction'ClosedRange K).toSubgroup ⊓ M :=
      ⟨hx, hxM⟩
    rw [hM] at hxM'
    exact hxM'
  have hclosed :
      (residueAction'ClosedRange K).toSubgroup = ⊤ :=
    (InfiniteGalois.fixingSubgroup_fixedField (residueAction'ClosedRange K)).symm.trans
      (by rw [hfixed]; exact IntermediateField.fixingSubgroup_bot)
  intro g
  have : g ∈ (⊤ : Subgroup (kbar ≃ₐ[𝓀[K]] kbar)) := Subgroup.mem_top g
  rw [← hclosed] at this
  exact this

/-! ### The isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` and the Weil group -/

/-- `residueAction` surjects onto (all of) `Gal(kbar/𝓀[K])`, i.e. `frobenius K` (which really is
an element of `Gal(kbar/𝓀[K])`, not just of `RingAut kbar`, by `frobenius_fixes` -- though
packaging that fact as membership in a `Gal(kbar/𝓀[K])`-as-subgroup-of-`RingAut kbar` is itself
not yet set up here) lies in the image of `G_K`. This is *not* a fact about finite fields at all
(unlike `exists_residueGaloisGroup_equiv_Zhat` below, whose remaining content specializes to
finite fields once this is granted): it is the genuinely local-field-theoretic input that, for a
Henselian complete field, the residue extension of an algebraic extension is again Galois with
Galois group a quotient of `G_K` -- concretely, that every automorphism of `kbar/𝓀[K]` lifts to an
automorphism of `K̄/K` stabilizing `valuationSubringExtension K` (this uses that unramified
extensions of `K` exist and are classified by, and lift automorphisms of, their residue
extensions -- a Hensel's-lemma-flavoured existence/lifting theorem, not merely a
statement about `Gal(K̄/K)`'s finite quotients). Mathlib's `InfiniteGalois.restrictNormalHom_surjective`
is surjectivity of a *different* map (restriction between two normal subextensions of one fixed
Galois extension) and does not apply: `residueAction` is not a restriction map, it is induced by
the (a priori unrelated) action on the residue field of `valuationSubringExtension K`. Not yet in
Mathlib, and not proved here. -/
theorem frobenius_mem_residueAction_range : frobenius K ∈ (residueAction K).range := by
  obtain ⟨σ, hσ⟩ := surjective_residueAction' K (frobeniusAlgEquiv K)
  refine ⟨σ, RingEquiv.ext fun x => ?_⟩
  have := AlgEquiv.ext_iff.mp hσ x
  simpa [residueAction'_apply] using this

/-! ### Assembling `Gal(kbar/𝓀[K]) ≅ ℤ̂` -/

/-- `frobenius K`, applied to *any* element of `kbar` (not just one already fixed by `𝓀[K]`), is
raising to the `#𝓀[K]`-th power. This is definitional (`frobenius` is `iterateFrobeniusEquiv`,
whose defining equation `iterateFrobeniusEquiv_def` is exactly this, up to identifying
`(residueCharP K) ^ (residueDegree K : ℕ)` with `Fintype.card 𝓀[K]` via `card_residueField_eq`). -/
theorem frobenius_apply (x : kbar) : frobenius K x = x ^ Fintype.card 𝓀[K] := by
  haveI : PerfectField kbar := @IsAlgClosed.perfectField kbar _ (residueField_isAlgClosed K)
  haveI : PerfectRing kbar (residueCharP K) := PerfectField.toPerfectRing (residueCharP K)
  show iterateFrobeniusEquiv kbar (residueCharP K) (residueDegree K : ℕ) x = x ^ Fintype.card 𝓀[K]
  rw [iterateFrobeniusEquiv_def, card_residueField_eq]

/-- The restriction of `frobenius` to any finite Galois subextension `M ≤ kbar` of `𝓀[K]` is the
finite-field Frobenius `x ↦ x ^ #𝓀[K]` on `M`. Proved by descending `frobenius_apply` along the
(injective, since `M` is a field) inclusion `M ↪ kbar`, using
`AlgEquiv.restrictNormalHom_apply` to identify the restriction with the action on `kbar` itself. -/
theorem restrictNormalHom_frobenius_apply (M : IntermediateField 𝓀[K] kbar) [Normal 𝓀[K] M]
    (x : M) :
    AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K) x = x ^ Fintype.card 𝓀[K] := by
  have h := AlgEquiv.restrictNormalHom_apply M (frobeniusAlgEquiv K) x
  rw [frobeniusAlgEquiv_apply, frobenius_apply] at h
  exact_mod_cast h

/-- Iterating `restrictNormalHom_frobenius_apply`: the restriction of `frobenius ^ i` to a finite
Galois subextension `M ≤ kbar` of `𝓀[K]` is `x ↦ x ^ (#𝓀[K]) ^ i`. Proved by induction on `i`,
mirroring `FiniteField.Extension.frob_iterate_apply`. -/
theorem restrictNormalHom_frobenius_pow_apply (M : IntermediateField 𝓀[K] kbar) [Normal 𝓀[K] M]
    (i : ℕ) (x : M) :
    AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K ^ i) x =
      x ^ (Fintype.card 𝓀[K]) ^ i := by
  induction i generalizing x with
  | zero => simp
  | succ i ih =>
    rw [pow_succ, map_mul, AlgEquiv.mul_apply, restrictNormalHom_frobenius_apply, ih, ← pow_mul,
      ← pow_succ']

/-- **Every finite Galois subextension `M` of `kbar/𝓀[K]` has cyclic Galois group**, generated by
the restriction of Frobenius. Unlike `exists_frobenius_pow_eq` (which only gives that a *given*
`h : Gal(M/𝓀[K])` is *some* power of Frobenius restricted), this packages that fact as
`IsCyclic`. Applying `exists_frobenius_pow_eq` directly to `h` (rather than lifting it to an
automorphism of all of `kbar` first, which is unnecessary since `exists_frobenius_pow_eq` already
works for arbitrary finite algebras over `𝓀[K]`) gives `i` with `h` and `restrictNormalHom M
(frobeniusAlgEquiv K) ^ i` agreeing on all of `M`
(`restrictNormalHom_frobenius_pow_apply`), hence equal. -/
instance isCyclic_gal_of_finite_normal (M : IntermediateField 𝓀[K] kbar)
    [FiniteDimensional 𝓀[K] M] [Normal 𝓀[K] M] : IsCyclic (M ≃ₐ[𝓀[K]] M) := by
  haveI : Finite M := Module.finite_of_finite 𝓀[K]
  rw [isCyclic_iff_exists_zpowers_eq_top]
  refine ⟨AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K),
    (Subgroup.eq_top_iff' _).mpr fun h => ?_⟩
  obtain ⟨i, hi⟩ := exists_frobenius_pow_eq K h
  refine ⟨(i : ℤ), ?_⟩
  show AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K) ^ (i : ℤ) = h
  rw [zpow_natCast, ← map_pow]
  apply AlgEquiv.ext
  intro x
  rw [restrictNormalHom_frobenius_pow_apply]
  exact (hi x).symm

/-- The homomorphism `Multiplicative ℤ →* Gal(kbar/𝓀[K])` sending `1` to `frobeniusAlgEquiv K`,
i.e. `n ↦ (frobeniusAlgEquiv K) ^ n`. This is the map whose profinite completion (via
`ProfiniteGrp.ProfiniteCompletion.lift`) is the desired isomorphism `ℤ̂ ≅ Gal(kbar/𝓀[K])`. -/
def frobeniusZpowersHom : Multiplicative ℤ →* (kbar ≃ₐ[𝓀[K]] kbar) :=
  zpowersHom _ (frobeniusAlgEquiv K)

@[simp]
theorem frobeniusZpowersHom_apply (n : Multiplicative ℤ) :
    frobeniusZpowersHom K n = frobeniusAlgEquiv K ^ n.toAdd := rfl

/-- **Topological generation**: the subgroup generated by `frobeniusAlgEquiv K` is dense in
`Gal(kbar/𝓀[K])`. The proof needs no classification of the finite Galois subextensions of
`kbar/𝓀[K]` (unlike injectivity below): given `g` and a neighbourhood `t` of `g`, translate to a
neighbourhood of `1` (`map_mul_left_nhds_one`), find a finite Galois `M` with
`M.fixingSubgroup ⊆` that neighbourhood (`InfiniteGalois.krullTopology_mem_nhds_one_iff_of_isGalois`),
use `exists_frobenius_pow_eq` to match `g`'s restriction to `M` against some power of Frobenius's
restriction (`restrictNormalHom_frobenius_pow_apply`), and conclude that power of `frobeniusAlgEquiv
K` lies in `t`. -/
theorem denseRange_frobeniusZpowersHom : Dense (Set.range (frobeniusZpowersHom K)) := by
  rw [dense_iff_closure_eq]
  refine Set.eq_univ_of_forall fun g => mem_closure_iff_nhds.mpr fun t ht => ?_
  have hW : (g * ·) ⁻¹' t ∈ 𝓝 (1 : kbar ≃ₐ[𝓀[K]] kbar) := by
    rw [← Filter.mem_map, map_mul_left_nhds_one]; exact ht
  obtain ⟨M, hM⟩ := (InfiniteGalois.krullTopology_mem_nhds_one_iff_of_isGalois
    ((g * ·) ⁻¹' t)).mp hW
  haveI : Normal 𝓀[K] M.toIntermediateField := M.isGalois.to_normal
  haveI : Finite M.toIntermediateField := Module.finite_of_finite 𝓀[K]
  obtain ⟨i, hi⟩ := exists_frobenius_pow_eq K
    (AlgEquiv.restrictNormalHom M.toIntermediateField g)
  have hker : AlgEquiv.restrictNormalHom M.toIntermediateField
      (g⁻¹ * frobeniusAlgEquiv K ^ i) = 1 := by
    rw [map_mul, _root_.map_inv, inv_mul_eq_one]
    exact AlgEquiv.ext fun x =>
      (hi x).trans (restrictNormalHom_frobenius_pow_apply K M.toIntermediateField i x).symm
  have hmem : g⁻¹ * frobeniusAlgEquiv K ^ i ∈ M.fixingSubgroup := by
    rw [← IntermediateField.restrictNormalHom_ker]; exact hker
  have hmem_t : frobeniusAlgEquiv K ^ i ∈ t := by
    have := hM hmem
    simpa using this
  exact ⟨frobeniusAlgEquiv K ^ i, hmem_t,
    ⟨Multiplicative.ofAdd (i : ℤ), by simp⟩⟩

/-- **Existence of a degree-`n` subfield of `kbar` over `𝓀[K]`, for every `n ≥ 1`**: embed the
abstract `FiniteField.Extension 𝓀[K] (residueCharP K) n` (a concrete finite extension of `𝓀[K]` of
degree exactly `n`, by `FiniteField.finrank_extension`) into the algebraically closed `kbar` via
`IsAlgClosed.lift`, and take its (degree-preserving, since it's injective) field range. Existence
only; *uniqueness* of the degree-`n` subfield of `kbar` (as opposed to of a fixed finite Galois
subextension, which `IsGalois.existsUnique_intermediateField_finrank_eq` already gives) needs
comparing two arbitrary such subfields inside their compositum (or another common finite Galois
subextension containing both, e.g. via the `Lattice (FiniteGaloisIntermediateField 𝓀[K] kbar)`
structure) and is not done here. -/
theorem exists_intermediateField_finrank_eq (n : ℕ) [NeZero n] :
    ∃ M : IntermediateField 𝓀[K] kbar, Module.finrank 𝓀[K] M = n := by
  haveI := residueField_isAlgClosed K
  let f : FiniteField.Extension 𝓀[K] (residueCharP K) n →ₐ[𝓀[K]] kbar := IsAlgClosed.lift
  refine ⟨f.fieldRange, ?_⟩
  rw [← LinearEquiv.finrank_eq f.equivFieldRange.toLinearEquiv]
  exact FiniteField.finrank_extension 𝓀[K] (residueCharP K) n

/-- **Global uniqueness of the degree-`n` subfield of `kbar`**: any two finite Galois subextensions
`M₁ M₂ ≤ kbar` of `𝓀[K]` of the same degree over `𝓀[K]` coincide. Compares `M₁`, `M₂` inside their
sup `L := M₁ ⊔ M₂` (finite-dimensional and normal over `𝓀[K]` by `IntermediateField.finiteDimensional_sup`
/ `.normal_sup`, hence Galois since `𝓀[K]` is finite hence perfect, and cyclic Galois group by
`isCyclic_gal_of_finite_normal`): restricting `M₁`, `M₂` to `L` via `IntermediateField.comap L.val`
(degree-preserving, `IntermediateField.finrank_comap_val_of_le`) gives two degree-`n` subfields of
`L`, which agree by `IsGalois.existsUnique_intermediateField_finrank_eq`; mapping back via
`IntermediateField.map_comap_eq_self` recovers `M₁ = M₂`. -/
theorem eq_of_finrank_eq (M1 M2 : IntermediateField 𝓀[K] kbar)
    [FiniteDimensional 𝓀[K] M1] [Normal 𝓀[K] M1] [FiniteDimensional 𝓀[K] M2] [Normal 𝓀[K] M2]
    (h : Module.finrank 𝓀[K] M1 = Module.finrank 𝓀[K] M2) : M1 = M2 := by
  set n := Module.finrank 𝓀[K] M1 with hn
  set S := M1 ⊔ M2 with hS
  haveI : FiniteDimensional 𝓀[K] S := IntermediateField.finiteDimensional_sup M1 M2
  haveI : Normal 𝓀[K] S := IntermediateField.normal_sup 𝓀[K] kbar M1 M2
  haveI : IsGalois 𝓀[K] S := ⟨⟩
  have hM1L : M1 ≤ S := le_sup_left
  have hM2L : M2 ≤ S := le_sup_right
  set N1 := IntermediateField.comap S.val M1 with hN1
  set N2 := IntermediateField.comap S.val M2 with hN2
  have hN1card : Module.finrank 𝓀[K] N1 = n :=
    IntermediateField.finrank_comap_val_of_le hM1L
  have hN2card : Module.finrank 𝓀[K] N2 = n := by
    rw [hN2, IntermediateField.finrank_comap_val_of_le hM2L]
    exact h.symm
  have hdvd : n ∣ Module.finrank 𝓀[K] S := by
    rw [← hN1card]
    exact ⟨Module.finrank N1 S, (Module.finrank_mul_finrank 𝓀[K] N1 S).symm⟩
  obtain ⟨N, -, hNuniq⟩ := IsGalois.existsUnique_intermediateField_finrank_eq hdvd
  have hN1eq : N1 = N := hNuniq N1 hN1card
  have hN2eq : N2 = N := hNuniq N2 hN2card
  have hNeq : N1 = N2 := hN1eq.trans hN2eq.symm
  have hmap1 : IntermediateField.map S.val N1 = M1 :=
    IntermediateField.map_comap_eq_self (by rw [IntermediateField.fieldRange_val]; exact hM1L)
  have hmap2 : IntermediateField.map S.val N2 = M2 :=
    IntermediateField.map_comap_eq_self (by rw [IntermediateField.fieldRange_val]; exact hM2L)
  rw [← hmap1, ← hmap2, hNeq]

/-- The `AlgHom` witness underlying `exists_intermediateField_finrank_eq`, exposed on its own so
that its `FiniteDimensional`/`Normal` properties (inherited from `FiniteField.Extension`, via
`AlgHom.equivFieldRange`) can be transported to its field range. -/
noncomputable def frobeniusExtensionAlgHom (n : ℕ) [NeZero n] :
    FiniteField.Extension 𝓀[K] (residueCharP K) n →ₐ[𝓀[K]] kbar :=
  haveI := residueField_isAlgClosed K
  IsAlgClosed.lift

/-- **The canonical degree-`n` subfield of `kbar` over `𝓀[K]`**, for `n ≥ 1`: the field range of
`frobeniusExtensionAlgHom`. Unlike the bare existential `exists_intermediateField_finrank_eq`, this
comes with `FiniteDimensional`/`Normal`/`IsGalois` instances, all inherited from
`FiniteField.Extension 𝓀[K] (residueCharP K) n` (which is `Module.Finite` and, being a splitting
field, `Normal`) via the algebra isomorphism `AlgHom.equivFieldRange`. -/
noncomputable def canonicalDegreeSubfield (n : ℕ) [NeZero n] : IntermediateField 𝓀[K] kbar :=
  (frobeniusExtensionAlgHom K n).fieldRange

instance canonicalDegreeSubfield.instFiniteDimensional (n : ℕ) [NeZero n] :
    FiniteDimensional 𝓀[K] (canonicalDegreeSubfield K n) :=
  Module.Finite.equiv (frobeniusExtensionAlgHom K n).equivFieldRange.toLinearEquiv

instance canonicalDegreeSubfield.instNormal (n : ℕ) [NeZero n] :
    Normal 𝓀[K] (canonicalDegreeSubfield K n) :=
  Normal.of_algEquiv (frobeniusExtensionAlgHom K n).equivFieldRange

instance canonicalDegreeSubfield.instIsGalois (n : ℕ) [NeZero n] :
    IsGalois 𝓀[K] (canonicalDegreeSubfield K n) := ⟨⟩

theorem finrank_canonicalDegreeSubfield (n : ℕ) [NeZero n] :
    Module.finrank 𝓀[K] (canonicalDegreeSubfield K n) = n := by
  show Module.finrank 𝓀[K] (frobeniusExtensionAlgHom K n).fieldRange = n
  rw [← LinearEquiv.finrank_eq (frobeniusExtensionAlgHom K n).equivFieldRange.toLinearEquiv]
  exact FiniteField.finrank_extension 𝓀[K] (residueCharP K) n

/-- Any finite Galois subextension of `kbar/𝓀[K]` of degree `n` equals `canonicalDegreeSubfield K
n`: combines `eq_of_finrank_eq` (global uniqueness) with `finrank_canonicalDegreeSubfield`. -/
theorem eq_canonicalDegreeSubfield (M : IntermediateField 𝓀[K] kbar)
    [FiniteDimensional 𝓀[K] M] [Normal 𝓀[K] M] {n : ℕ} [NeZero n]
    (hM : Module.finrank 𝓀[K] M = n) : M = canonicalDegreeSubfield K n :=
  eq_of_finrank_eq K M (canonicalDegreeSubfield K n) (hM.trans (finrank_canonicalDegreeSubfield K n).symm)

/-- **Every finite Galois subextension has Frobenius (restricted) as a generator of its Galois
group.** This is the content of `isCyclic_gal_of_finite_normal`'s proof, exposed as a standalone
membership fact so it can be fed to `mulEquivOfGenerators`. -/
theorem zpowers_restrictNormalHom_frobeniusAlgEquiv_eq_top (M : IntermediateField 𝓀[K] kbar)
    [FiniteDimensional 𝓀[K] M] [Normal 𝓀[K] M] (h : M ≃ₐ[𝓀[K]] M) :
    h ∈ Subgroup.zpowers (AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K)) := by
  haveI : Finite M := Module.finite_of_finite 𝓀[K]
  obtain ⟨i, hi⟩ := exists_frobenius_pow_eq K h
  refine ⟨(i : ℤ), ?_⟩
  show AlgEquiv.restrictNormalHom M (frobeniusAlgEquiv K) ^ (i : ℤ) = h
  rw [zpow_natCast, ← map_pow]
  apply AlgEquiv.ext
  intro x
  rw [restrictNormalHom_frobenius_pow_apply]
  exact (hi x).symm

/-- **The per-level isomorphism**: the quotient of `Multiplicative ℤ` by a finite-index normal
subgroup `H` of index `n` is isomorphic to the Galois group of the canonical degree-`n` subfield,
matching the canonical generators on both sides (the image of `Multiplicative.ofAdd 1` on the left,
Frobenius restricted on the right). Built from `mulEquivOfGenerators`
(`Langlands.CyclicSubgroups`). -/
noncomputable def levelMulEquiv (H : FiniteIndexNormalSubgroup (Multiplicative ℤ)) :
    haveI : NeZero H.toSubgroup.index := ⟨Subgroup.FiniteIndex.index_ne_zero⟩
    Multiplicative ℤ ⧸ H.toSubgroup ≃*
      (canonicalDegreeSubfield K H.toSubgroup.index ≃ₐ[𝓀[K]] canonicalDegreeSubfield K H.toSubgroup.index) :=
  haveI : NeZero H.toSubgroup.index := ⟨Subgroup.FiniteIndex.index_ne_zero⟩
  mulEquivOfGenerators
    (g := QuotientGroup.mk' H.toSubgroup (Multiplicative.ofAdd (1 : ℤ)))
    (g' := AlgEquiv.restrictNormalHom (canonicalDegreeSubfield K H.toSubgroup.index) (frobeniusAlgEquiv K))
    (zpowers_quotientGroupMk'_eq_top_of_zpowers_eq_top
      (fun x : Multiplicative ℤ => ⟨x.toAdd, by simp [← ofAdd_zsmul]⟩) H.toSubgroup)
    (zpowers_restrictNormalHom_frobeniusAlgEquiv_eq_top K _)
    (by
      rw [← Subgroup.index_eq_card, IsGalois.card_aut_eq_finrank, finrank_canonicalDegreeSubfield])

/-- **Divisibility of degree gives containment of `canonicalDegreeSubfield`s**: for `m ∣ n`,
`canonicalDegreeSubfield K m ≤ canonicalDegreeSubfield K n`. Applies
`IsGalois.existsUnique_intermediateField_finrank_eq` inside `canonicalDegreeSubfield K n` (finite
cyclic, hence abelian, Galois of degree `n`) to get a degree-`m` subfield `N` -- automatically
`Normal 𝓀[K] N` by `IsGalois.normal_of_isMulCommutative` (`Langlands.CyclicGaloisSubfields`), since
`Gal(canonicalDegreeSubfield K n / 𝓀[K])` is abelian -- then transports it into `kbar` via
`IntermediateField.map`, identifying the (degree-`m`, `FiniteDimensional`, `Normal`) image with
`canonicalDegreeSubfield K m` via `eq_canonicalDegreeSubfield`. -/
theorem canonicalDegreeSubfield_le_of_dvd {m n : ℕ} [NeZero m] [NeZero n] (h : m ∣ n) :
    canonicalDegreeSubfield K m ≤ canonicalDegreeSubfield K n := by
  set E := canonicalDegreeSubfield K n with hE
  haveI : IsCyclic Gal(E/𝓀[K]) := isCyclic_gal_of_finite_normal K E
  haveI : IsMulCommutative Gal(E/𝓀[K]) := IsCyclic.isMulCommutative
  have hmn : m ∣ Module.finrank 𝓀[K] E := by
    rw [finrank_canonicalDegreeSubfield]; exact h
  obtain ⟨N, hNcard, -⟩ := IsGalois.existsUnique_intermediateField_finrank_eq hmn
  haveI hNnormal : Normal 𝓀[K] N := IsGalois.normal_of_isMulCommutative N
  set M' := IntermediateField.map E.val N with hM'
  have hequiv : N ≃ₐ[𝓀[K]] M' := N.equivMap E.val
  haveI hM'fd : FiniteDimensional 𝓀[K] M' := Module.Finite.equiv hequiv.toLinearEquiv
  haveI hM'normal : Normal 𝓀[K] M' := Normal.of_algEquiv hequiv
  have hM'card : Module.finrank 𝓀[K] M' = m := by
    rw [← LinearEquiv.finrank_eq hequiv.toLinearEquiv]; exact hNcard
  have hM'eq : M' = canonicalDegreeSubfield K m := eq_canonicalDegreeSubfield K M' hM'card
  rw [← hM'eq, hM']
  intro x hx
  obtain ⟨y, -, rfl⟩ := N.mem_map.mp hx
  exact y.2

/-- **Injectivity input**: an automorphism of `kbar/𝓀[K]` restricting to the identity on every
`canonicalDegreeSubfield K n` is itself the identity. Every `x : kbar` lies in some finite Galois
`M` (its `FiniteGaloisIntermediateField.adjoin`, mirroring `surjective_residueAction'`'s proof),
and `M = canonicalDegreeSubfield K d` for `d := [M : 𝓀[K]]` by `eq_canonicalDegreeSubfield`; since
`g` restricts to the identity there, `g` fixes `x`. -/
theorem eq_one_of_forall_restrictNormalHom_canonicalDegreeSubfield_eq_one
    (g : kbar ≃ₐ[𝓀[K]] kbar)
    (hg : ∀ (n : ℕ) [NeZero n], AlgEquiv.restrictNormalHom (canonicalDegreeSubfield K n) g = 1) :
    g = 1 := by
  apply AlgEquiv.ext
  intro x
  obtain ⟨M, hMfd, hMnormal, hxM⟩ : ∃ M : IntermediateField 𝓀[K] kbar,
      FiniteDimensional 𝓀[K] M ∧ Normal 𝓀[K] M ∧ x ∈ M := by
    classical
    haveI := residueField_isGalois K
    let L' := FiniteGaloisIntermediateField.adjoin 𝓀[K] ({x} : Set kbar)
    exact ⟨L'.toIntermediateField, L'.finiteDimensional, L'.isGalois.to_normal,
      FiniteGaloisIntermediateField.subset_adjoin 𝓀[K] ({x} : Set kbar) rfl⟩
  haveI := hMfd; haveI := hMnormal
  haveI : NeZero (Module.finrank 𝓀[K] M) := ⟨Module.finrank_pos.ne'⟩
  have hMeq : M = canonicalDegreeSubfield K (Module.finrank 𝓀[K] M) :=
    eq_canonicalDegreeSubfield K M rfl
  have hxM' : x ∈ canonicalDegreeSubfield K (Module.finrank 𝓀[K] M) := hMeq ▸ hxM
  have hgM : AlgEquiv.restrictNormalHom (canonicalDegreeSubfield K (Module.finrank 𝓀[K] M)) g = 1 :=
    hg (Module.finrank 𝓀[K] M)
  have := AlgEquiv.restrictNormalHom_apply (canonicalDegreeSubfield K (Module.finrank 𝓀[K] M)) g
    ⟨x, hxM'⟩
  rw [hgM] at this
  simpa using this.symm

/-- The classical computation of the (profinite) absolute Galois group of a finite field: it is
topologically generated by Frobenius, and (as an abstract group) isomorphic to `ℤ̂`, via
`Multiplicative.ofAdd 1 ↦ frobenius K`. This is a deep theorem (not yet in Mathlib) about the
structure of `Gal(k̄/k)` for `k` finite; we record only the existence of *some* group isomorphism
with the stated behavior on Frobenius, as an abstract `MulEquiv` (i.e. we do not yet assert it is
a homeomorphism for the Krull topology on the left and the profinite topology on the right).

Ingredients now available in Mathlib towards this: `kbar/𝓀[K]` is Galois (`residueField_isGalois`,
added above from `IsAlgClosure.normal` + `Algebra.IsAlgebraic.isSeparable_of_perfectField`); for
every `n`, `Gal(GaloisField p (m*n) / GaloisField p m)` is cyclic of order `n` generated by the
Frobenius `FiniteField.Extension.frob` (`FiniteField.Extension.natCard_algEquiv_extension`,
`.exists_frob_pow_eq`, and `FiniteField.exists_forall_apply_eq_pow` for the corresponding statement
against an arbitrary finite extension of `𝓀[K]`, all in `Mathlib.FieldTheory.Finite.Extension`,
specialized here to `exists_frobenius_pow_eq`); `Zhat` satisfies the universal property
`ProfiniteGrp.ProfiniteCompletion.homEquiv` / `.lift` of the profinite completion of `ℤ`
(`Mathlib.Topology.Algebra.Category.ProfiniteGrp.Completion`); and `Gal(K/k)` for any `IsGalois k K`
is packaged as a `ProfiniteGrp` matching the limit of its finite Galois subextensions' groups, via
`InfiniteGalois.profiniteGalGrp` (`Mathlib.FieldTheory.Galois.Profinite`) -- so item (1) of the
previous version of this note (packaging `Gal(kbar/𝓀[K])` as a `ProfiniteGrp`) is now off-the-shelf,
via `InfiniteGalois.profiniteGalGrp 𝓀[K] kbar`.

**Now proved, unconditionally on `K`'s universe, no `sorry`**: `frobenius_apply` (`frobenius K`
raises *every* element of `kbar` to the `#𝓀[K]`-th power, not just `𝓀[K]`-fixed ones);
`restrictNormalHom_frobenius_apply` / `restrictNormalHom_frobenius_pow_apply` (the restriction of
`frobeniusAlgEquiv K ^ i` to any finite Galois subextension `M ≤ kbar` of `𝓀[K]` is `x ↦ x ^
(#𝓀[K])^i`, via `AlgEquiv.restrictNormalHom_apply`); `frobeniusZpowersHom` (`Multiplicative ℤ →*
Gal(kbar/𝓀[K])`, `n ↦ frobeniusAlgEquiv K ^ n`); and, combining these with
`exists_frobenius_pow_eq` and the neighbourhood-basis description of the Krull topology
(`InfiniteGalois.krullTopology_mem_nhds_one_iff_of_isGalois`), **`denseRange_frobeniusZpowersHom`**:
the subgroup generated by `frobeniusAlgEquiv K` is dense in `Gal(kbar/𝓀[K])`. This settles
"topological generation" without needing any classification of `kbar/𝓀[K]`'s finite subextensions.

What remains, in two genuinely separate parts:

1. **A universe obstruction, discovered while attempting to invoke `ProfiniteGrp.ProfiniteCompletion.lift`
   directly on `InfiniteGalois.profiniteGalGrp 𝓀[K] kbar`.** `Zhat` is `abbrev Zhat : Type := ...`,
   hardwired to (the completion of `Multiplicative ℤ : Type`, i.e.) universe `0`, whereas `kbar`
   lives in the same (arbitrary, `variable`-bound) universe as `K` itself. Mathlib's categorical
   `ProfiniteGrp.Hom`/`lift`/`homEquiv` all require source and target in `ProfiniteGrp.{u}` for the
   *same* `u`, so `ProfiniteGrp.ProfiniteCompletion.lift` cannot be applied directly to
   `frobeniusZpowersHom` bundled at `InfiniteGalois.profiniteGalGrp 𝓀[K] kbar : ProfiniteGrp.{u}`
   against `Zhat : ProfiniteGrp.{0}` unless `K : Type` (universe `0`) specifically -- which would
   silently de-generalize every downstream declaration in this file. Bridging this for general `K`
   needs a `ULift` argument (e.g. transporting along `ProfiniteGrp.ProfiniteCompletion.completion
   (GrpCat.of (ULift.{u} (Multiplicative ℤ)))`, itself abstractly isomorphic to `Zhat` since
   `ULift.moduleEquiv`-style equivalences make `ULift (Multiplicative ℤ) ≃* Multiplicative ℤ` and
   profinite completion should transport along that, though this transport is not yet spelled out
   anywhere) -- genuine additional plumbing, not attempted here. (With that bridge in hand,
   density above gives *surjectivity* of the resulting map `Zhat → Gal(kbar/𝓀[K])` for free: its
   range is compact, hence closed since `Gal(kbar/𝓀[K])` is Hausdorff (`krullTopology_t2`), and
   contains the dense range of `frobeniusZpowersHom`.)
2. **Injectivity**, which is unaffected by the universe question and is the deeper content: it
   needs identifying the open normal subgroups of `Gal(kbar/𝓀[K])` with exactly the kernels of
   restriction to the finite subfields `GaloisField p (m*n) ≤ kbar`, matched up (via
   `finrank_zmod_extension`-style bookkeeping on degrees) with the finite-index-normal-subgroup
   diagram `n ↦ ℤ ⧸ nℤ` defining `Zhat`. Several general-purpose (non-`Langlands`-specific) pieces
   of this are now proved from scratch and committed: `IsCyclic.existsUnique_subgroup_card_eq`
   (`Langlands.CyclicSubgroups`, pure group theory -- a finite cyclic group has a unique subgroup
   of each order dividing its own), its field-theoretic translation through the Galois
   correspondence `IsGalois.existsUnique_intermediateField_finrank_eq` (a *finite* cyclic Galois
   extension `E/F` has a unique subfield of each degree dividing `[E:F]`), and the general "restrict
   an intermediate field to a smaller ambient intermediate field, preserving degree"
   `IntermediateField.finrank_comap_val_of_le` (all three in `Langlands.CyclicGaloisSubfields`; the
   third was initially reported missing from Mathlib by a Loogle search that only tried
   "restrict"-flavoured names, then found on searching by *type shape* -- it assembles from
   `IntermediateField.comap`/`.map_comap_eq_self`/`.equivMap`, all pre-existing). Specialized here:
   `isCyclic_gal_of_finite_normal` (an `instance`) shows `Gal(M/𝓀[K])` is cyclic (generated by
   Frobenius restricted) for *every* finite Galois `M ≤ kbar`; `exists_intermediateField_finrank_eq`
   gives *existence* of a degree-`n` subfield of `kbar` for every `n` (embedding `FiniteField.Extension
   𝓀[K] (residueCharP K) n` into `kbar` via `IsAlgClosed.lift`); and **`eq_of_finrank_eq`** now closes
   *global* uniqueness: any two finite Galois `M₁ M₂ ≤ kbar` of equal degree over `𝓀[K]` coincide,
   by comparing their restrictions to the sup `M₁ ⊔ M₂` (finite-dimensional/normal/Galois/cyclic by
   `IntermediateField.finiteDimensional_sup` / `.normal_sup` / perfectness of `𝓀[K]` /
   `isCyclic_gal_of_finite_normal`) via `IsGalois.existsUnique_intermediateField_finrank_eq` there,
   then mapping back. Together, existence + this uniqueness give: *the* degree-`n` subfield of `kbar`
   over `𝓀[K]`, for every `n`, is well-defined. What remains is only the **final assembly**: turning
   this into the order-isomorphism between finite Galois subextensions of `kbar/𝓀[K]` and `(ℕ, ∣)`,
   and then a map to/from `Zhat` (whose defining diagram is indexed by
   `FiniteIndexNormalSubgroup (Multiplicative ℤ)`, itself not yet related to `(ℕ, ∣)` here) -- either
   via the universe-obstructed categorical route in item 1 above, or a bare-hands construction of
   `Zhat`'s limit elements directly; neither attempted. -/
theorem exists_residueGaloisGroup_equiv_Zhat :
    ∃ e : (residueAction K).range ≃* Zhat,
      e ⟨frobenius K, frobenius_mem_residueAction_range K⟩ = toZhat (Multiplicative.ofAdd 1) := by
  sorry

/-- A fixed choice of isomorphism `Gal(kbar/𝓀[K]) ≅ ℤ̂` from
`exists_residueGaloisGroup_equiv_Zhat`, identifying the image of `residueAction K` (i.e. the
Galois group of the residue field extension) with the profinite completion of `ℤ`. -/
def residueGaloisGroupEquivZhat : (residueAction K).range ≃* Zhat :=
  (exists_residueGaloisGroup_equiv_Zhat K).choose

/-- The composite homomorphism `G_K →* ℤ̂` sending `σ` to the (profinite) power of Frobenius that
`σ` induces on the residue field. -/
def toZhatHom : Field.absoluteGaloisGroup K →* Zhat :=
  (residueGaloisGroupEquivZhat K).toMonoidHom.comp (residueAction K).rangeRestrict

/-- The **Weil group** `W_K` of `K`: the subgroup of `σ ∈ G_K` inducing an *integer* power of
Frobenius on the residue field, i.e. the preimage of `ℤ ≤ ℤ̂` (`integerSubgroup`) under
`toZhatHom`. -/
def WeilGroup : Subgroup (Field.absoluteGaloisGroup K) :=
  Subgroup.comap (toZhatHom K) (integerSubgroup)

/-- The inertia subgroup is contained in the Weil group (it maps to `1 ∈ ℤ ≤ ℤ̂`). -/
theorem inertiaSubgroup_le_weilGroup : inertiaSubgroup K ≤ WeilGroup K := by
  rw [← residueAction_ker]
  intro x hx
  rw [MonoidHom.mem_ker] at hx
  simp only [WeilGroup, Subgroup.mem_comap, toZhatHom, MonoidHom.coe_comp, Function.comp_apply]
  rw [show (residueAction K).rangeRestrict x = 1 from Subtype.ext hx, map_one]
  exact Subgroup.one_mem _

/-- `inertiaSubgroup K` is normal in `G_K`: it is (via `residueAction_ker`) the kernel of
`residueAction K`, and kernels of group homomorphisms are always normal. -/
instance inertiaSubgroup_normal : (inertiaSubgroup K).Normal := by
  rw [← residueAction_ker]; infer_instance

/-- The **Artin map** (or "art" map, or valuation map) `W_K →* ℤ`: every `σ ∈ W_K` induces an
*integer* power of Frobenius on the residue field (by definition of `WeilGroup`), and this is that
integer, packaged via the isomorphism `ℤ ≃* integerSubgroup` (`integerSubgroupEquiv`). Its kernel
is `I_K` (`toArt_ker`). -/
def toArt : WeilGroup K →* Multiplicative ℤ :=
  integerSubgroupEquiv.symm.toMonoidHom.comp
    (((toZhatHom K).restrict (WeilGroup K)).codRestrict integerSubgroup
      fun w => Subgroup.mem_comap.mp w.2)

/-- The kernel of `toZhatHom` is `I_K`: `σ` induces the trivial power of Frobenius iff it acts
trivially on the residue field, i.e. lies in the kernel of `residueAction` (which is `I_K` by
`residueAction_ker`). -/
theorem toZhatHom_ker : (toZhatHom K).ker = inertiaSubgroup K := by
  unfold toZhatHom
  rw [MonoidHom.ker_comp_of_injective _ _ (residueGaloisGroupEquivZhat K).injective,
    MonoidHom.ker_rangeRestrict, residueAction_ker]

theorem toArt_ker : (toArt K).ker = (inertiaSubgroup K).subgroupOf (WeilGroup K) := by
  unfold toArt
  rw [MonoidHom.ker_comp_of_injective _ _ integerSubgroupEquiv.symm.injective,
    MonoidHom.ker_codRestrict, MonoidHom.ker_restrict, toZhatHom_ker]

/-! ### The topology on `W_K` -/

/-- The "basic neighborhood of `1`" subgroup of `W_K` associated to an open subgroup `U` of `G_K`:
elements of `W_K` lying in both `U` and the inertia subgroup. As `U` ranges over open subgroups of
`G_K`, these form a filter basis at `1` for the topology on `W_K` (`WeilGroup.groupFilterBasis`)
making `I_K` open -- *not* the subspace topology from `G_K`, under which `I_K` is not open since
`⟨Frob⟩ ≅ ℤ` is dense in `Gal(kbar/𝓀[K]) ≅ ℤ̂`. -/
def basicSubgroup (U : OpenSubgroup (Field.absoluteGaloisGroup K)) : Subgroup (WeilGroup K) :=
  (U.toSubgroup ⊓ inertiaSubgroup K).subgroupOf (WeilGroup K)

/-- The `GroupFilterBasis` on `W_K` whose basic neighborhoods of `1` are `basicSubgroup K U` for
`U` an open subgroup of `G_K`. This realizes the topology described in the module docstring:
`I_K = basicSubgroup K ⊤` is open, and multiplication/inversion/conjugation are continuous because
they already are in `G_K` (whose topology `I_K`'s basic neighborhoods are built from). -/
@[implicit_reducible]
def groupFilterBasis : GroupFilterBasis (WeilGroup K) where
  sets := Set.range fun U : OpenSubgroup (Field.absoluteGaloisGroup K) =>
    (basicSubgroup K U : Set (WeilGroup K))
  nonempty := Set.range_nonempty _
  inter_sets := by
    rintro _ _ ⟨U, rfl⟩ ⟨V, rfl⟩
    refine ⟨_, Set.mem_range_self (⟨U.toSubgroup ⊓ V.toSubgroup, U.isOpen.inter V.isOpen⟩ :
      OpenSubgroup (Field.absoluteGaloisGroup K)), fun w hw => ?_⟩
    simp only [basicSubgroup, SetLike.mem_coe, Subgroup.mem_subgroupOf, Subgroup.mem_inf,
      OpenSubgroup.mem_toSubgroup, Set.mem_inter_iff] at hw ⊢
    tauto
  one' := by rintro _ ⟨U, rfl⟩; exact (basicSubgroup K U).one_mem
  mul' := by
    rintro _ ⟨U, rfl⟩
    exact ⟨_, Set.mem_range_self U, fun w ⟨a, ha, b, hb, hab⟩ => hab ▸ Subgroup.mul_mem _ ha hb⟩
  inv' := by
    rintro _ ⟨U, rfl⟩
    exact ⟨_, Set.mem_range_self U, fun w hw => Subgroup.inv_mem _ hw⟩
  conj' := by
    rintro x₀ _ ⟨U, rfl⟩
    refine ⟨_, Set.mem_range_self (U.comap (MulAut.conj (x₀ : Field.absoluteGaloisGroup K)).toMonoidHom
      (IsTopologicalGroup.continuous_conj _)), fun w hw => ?_⟩
    simp only [Set.mem_preimage, basicSubgroup, SetLike.mem_coe, Subgroup.mem_subgroupOf,
      Subgroup.mem_inf] at hw ⊢
    have hcoe : ((x₀ * w * x₀⁻¹ : WeilGroup K) : Field.absoluteGaloisGroup K) =
        (x₀ : Field.absoluteGaloisGroup K) * (w : Field.absoluteGaloisGroup K) *
          (x₀ : Field.absoluteGaloisGroup K)⁻¹ := by
      simp [Subgroup.coe_mul]
    rw [hcoe]
    refine ⟨?_, (inertiaSubgroup_normal K).conj_mem _ hw.2 _⟩
    simpa [OpenSubgroup.mem_comap, MulAut.conj_apply] using hw.1

/-- The topology on `W_K` making `I_K` an open subgroup, transported from `G_K`'s Krull topology
along the filter basis `groupFilterBasis`. This is the topology described in the module docstring,
*not* the subspace topology `W_K` would inherit directly from `G_K`. -/
instance instTopologicalSpace : TopologicalSpace (WeilGroup K) := (groupFilterBasis K).topology

/-- `W_K`, with the topology `instTopologicalSpace`, is a topological group. -/
instance instIsTopologicalGroup : IsTopologicalGroup (WeilGroup K) :=
  (groupFilterBasis K).isTopologicalGroup

/-- `I_K` (viewed as a subgroup of `W_K`) is open in `W_K`'s topology: this is the defining feature
of the Weil group topology, distinguishing it from the subspace topology from `G_K`. -/
theorem isOpen_inertiaSubgroupOf :
    IsOpen ((inertiaSubgroup K).subgroupOf (WeilGroup K) : Set (WeilGroup K)) := by
  have hmem : ((inertiaSubgroup K).subgroupOf (WeilGroup K) : Set (WeilGroup K)) ∈
      groupFilterBasis K := ⟨⊤, by simp [basicSubgroup, OpenSubgroup.toSubgroup_top]⟩
  exact Subgroup.isOpen_of_mem_nhds _ ((groupFilterBasis K).mem_nhds_one hmem)

/-- The quotient `W_K / I_K` is discrete: since `I_K` is open (`isOpen_inertiaSubgroupOf`), its
cosets partition `W_K` into open sets, so the quotient topology is discrete. Combined with
`toArt_ker`, this says the induced map `W_K / I_K → ℤ` (an isomorphism, via `toArt`) matches the
discrete topology on `ℤ` against the quotient topology on `W_K / I_K`. -/
theorem discreteTopology_quotient_inertiaSubgroupOf :
    DiscreteTopology (WeilGroup K ⧸ (inertiaSubgroup K).subgroupOf (WeilGroup K)) :=
  QuotientGroup.discreteTopology (isOpen_inertiaSubgroupOf K)

end LocalField
